### ISSUE TITLE
Database ORM, Json Serializer.

### ISSUE THREAD

**Issue by MohdFahmiNoorain** [cutelyst/cutelyst#1]
I really like your project, actually I'm using Wt before and it is very good except its lacks file processing tools that I can easily get from Qt QImage, QFile, QXmlStreamReader and etc.

But, Wt also come with pretty good stuff too. The database ORM (Wt:Dbo) which make my job really easy and Dbo::Json that can easily convert Wt::Dbo object to Json. Which is crucial to make Json RESTful service.

Do have any plan to implement such this features in Cutelyst?

**Comment by dantti** [comment]
Database ORM won't be implemented directly in Cutelyst as well as no templating system will be built-in it.

The main concept of Cutelyst is to provide a flexible way for doing such things, as in there is more than one way of doing it. I want to keep Cutelyst at a minimun core fundation to build web apps that you go plugin things that you need.

With Qt there are at least 3 DB ORM implementations:
https://github.com/steckdenis/qtorm and http://www.qxorm.com/qxorm_en/home.html and http://www.codesynthesis.com/products/odb/

At some time I plan to test them and se if it's possible to make some plugin to easy the usage as I have done with Grantlee and Clearsilver.

**Comment by dantti** [comment]
Oh and I actually have plans to create a JSON View similar to Catalyst::ViewJSON taking c->stash() and converting into a JSON reply with the help of QJsonDocument.

Best.

**Comment by dantti** [comment]
And here is your JSON View :)
https://github.com/cutelyst/cutelyst/commit/7b0deaa39b2666660a0f462f0b3f05ec5e71b36d

**Comment by MohdFahmiNoorain** [comment]
Ok, now I understand. And thanks for suggestions :+1:
