### ISSUE TITLE
Generated Root Controller still references c->welcomeMessage()

### ISSUE THREAD

**Issue by simonaw** [cutelyst/cutelyst#10]
@dantti Hi! In commit b5c7b04994bce9604dbe1c8eb675ccd2d0a322ef you removed the welcome message but it is still referenced in the `cutelyst --create-app` generated Root Controller `root.cpp`.

Shall we just serve a static "Hello world!" string instead?

**Comment by dantti** [comment]
Ah yes :( I still need to make the cutelyst executable use the QtCreator templates.
I think for now I'll just do a quick fix serving the static string as it doesn't make sense to have such a useless method available to all Cutelyst applications...

**Comment by simonaw** [comment]
OK, thanks!
