### ISSUE TITLE
Setting up Cutelyst on fedora

### ISSUE THREAD

**Issue by ShahriarSS** [cutelyst/cutelyst#100]
Hi. I install uwsgi and qtbase and clearsilver(not package names just hints) and I compile and install cutelyst successfully. I create the Hello project but when I run cmake .. in the build directory It gives me these:

CMake Error at CMakeLists.txt:16 (find_package):
  By not providing "FindCutelystQt5.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "CutelystQt5", but CMake did not find one.

  Could not find a package configuration file provided by "CutelystQt5" with
  any of the following names:

    CutelystQt5Config.cmake
    cutelystqt5-config.cmake

  Add the installation prefix of "CutelystQt5" to CMAKE_PREFIX_PATH or set
  "CutelystQt5_DIR" to a directory containing one of the above files.  If
  "CutelystQt5" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!

I googled it a bit and set CMAKE_PREFIX_PATH and CutelystQt5_DIR but non helps. the problem still remains

**Comment by dantti** [comment]
Please use 1.x.x branch or tagged releases, as master is Cutelyst 2.0 which is under development.
