### ISSUE TITLE
Setting Up The Cutelyst QtCreator Assistant

### ISSUE THREAD

**Issue by ShahriarSS** [cutelyst/cutelyst#102]
I am sorry but I didn't know any other place to ask this but how can one setup cutelyst's qtcreator assistant? I searched the wiki and didn't find anything there but:

If you are using QtCreator it's easier to setup the Cutelyst QtCreator assistant, and create the project there. The command line tool will be used in this tutorial as not everyone like QtCreator (I love it!).

I googled it but nothing came up. I'm sorry if this is not an issue but you don't have any tutorial for it

**Comment by dantti** [comment]
You can copy the qtcreator directory (or link) into

- /usr/share/qtcreator/templates/wizards - if you are using QtCreator from your distro
- ~/.config/QtProject/qtcreator/templates/wizards - which should work for any kind of QtCreator installation
