### ISSUE TITLE
SIGINT doesn't kill Cutelyst if run with -r option anymore

### ISSUE THREAD

**Issue by louwers** [cutelyst/cutelyst#117]
When I run the cutelyst2 executable with the `-r` option, it keeps running after a `SIGINT` signal (ctrl+C in terminal). Specifically the process that is bound to the terminal is terminated, but the server keeps running.

Please let me know if it's reproducible. I'm running Cutelyst 2.1.0.

**Comment by dantti** [comment]
On Linux?

**Comment by louwers** [comment]
Yes.

**Comment by louwers** [comment]
I can't reproduce it myself anymore...
