### ISSUE TITLE
Add sensible default arguments to CredentialPassword::createPassword?

### ISSUE THREAD

**Issue by louwers** [cutelyst/cutelyst#118]
Hasing passwords properly is hard and the user should be left as little room for error as possible. My suggestion is to add default arguments to the `CredentialPassword::createPassword` function so that users don't have to study this subject themselves (or don't do that, and make their application insecure).

-  https://cryptosense.com/blog/parameter-choice-for-pbkdf2/ (recommends Sha512, mentions NIST guidelines from August 2016, citing a minimum of 10000 PBKDF2 iterations)
- https://security.stackexchange.com/questions/110084/parameters-for-pbkdf2-for-password-hashing (discussion about hash length)
- More info about amount of iterations: https://security.stackexchange.com/questions/3959/recommended-of-iterations-when-using-pkbdf2-sha256

Multiple sources recommend testing the maximum amount of iterations whose performance is still acceptable. But 10000 is probably a sensible default. So something like (magic numbers should probably become static variables):

```cpp
static QByteArray createPassword(const QByteArray &password,
    QCryptographicHash::Algorithm method = QCryptographicHash::Sha512,
    int iterations = 10000, int saltByteSize = 16, int hashByteSize = 16);
```

Adding similar arguments to `CredentialPassword::pbkdf2` is probably a good idea. The tutorial would also need to be updated.

Let me know what you think.

**Comment by dantti** [comment]
I thought of doing this before v2, but gave up on the idea that the user should know what he is doing, but I think you might be right about misuse.
The problem with this now is that I believe such change might break ABI, but not sure.

**Comment by buschmann23** [comment]
As I had the same “issue“ to find the most appropriate values for PBKDF2 - especially the iterations count, I wrote a small test application to try to find the best fitting value for the iterations that would take up to 500ms for the pure algorithm.

See https://github.com/Huessenbergnetz/pbkdf2test

**Comment by louwers** [comment]
##C++ said that adding default arguments won't break ABI on any of the platforms they are aware of since it simply is not part of the ABI. The check for default argument is made at the call site. Furthermore, default arguments are added to the header, so by just swapping out headers without recompiling you could add default arguments.

**Comment by dantti** [comment]
Hmm when I searched for this I found:
https://stackoverflow.com/questions/41763930/does-adding-an-arguments-with-default-values-to-functions-break-abi/41764100

**Comment by dantti** [comment]
An alternative would be a method that hides all arguments but the password, iirc there's a library that does this.
If the default argument is stored by the compilation of the client an update of the values would not reflect on an application unless it's rebuilt, so this option might be a good idea I think.

**Comment by louwers** [comment]
@dantti Adding arguments with default values changes the ABI, this is what the StackOverflow thread is about. But what I proposed is that we add default values for already existing arguments. I don't see any logical way how this can change the ABI. Where you clear on this difference when you asked those people?
