### ISSUE TITLE
[question / missing docs] How to add ClearSilver?

### ISSUE THREAD

**Issue by trsh** [cutelyst/cutelyst#121]
I'm trying to add ClearSilver:

```
target_link_libraries(Hello
    Cutelyst::Core
    Qt5::Core
    Cutelyst::View::ClearSilver
    Qt5::Network
)
```

and getting this:

```
CMake Warning (dev) at src/CMakeLists.txt:9 (add_library):
  Policy CMP0028 is not set: Double colon in target name means ALIAS or
  IMPORTED target.  Run "cmake --help-policy CMP0028" for policy details.
  Use the cmake_policy command to set the policy and suppress this warning.

  Target "Hello" links to target "Cutelyst::View::ClearSilver" but the target
  was not found.  Perhaps a find_package() call is missing for an IMPORTED
  target, or an ALIAS target is missing?
This warning is for project developers.  Use -Wno-dev to suppress it.
```

**Comment by dantti** [comment]
Grantlee is working fine with cutelyst, where did you get that information? The only issue with Grantlee is the lack of maintenance, which is why I'm considering forking it as the author doesn't want to give me commit access nor he reviews pending Pull Requests...

**Comment by trsh** [comment]
@dantti 

https://github.com/cutelyst/cutelyst/wiki/Installing-Cutelyst

`At the moment libgrantlee-dev is build for Qt4 which is incompatible with Cutelyst that requires Qt5, so checkout their web site to build and install before attempting to compile Cutelyst so the proper integration plugin can be built.`

So what are the installation steps?

1) apt-get install something ?
2) cmake .. -DPLUGIN_VIEW_SOETHING

?

**Comment by dantti** [comment]
Hmm, current Debian now ships Grantlee5 for Qt5, I've updated that page, thanks.

**Comment by trsh** [comment]
All went good, except 

`E: Package 'libzmq-dev' has no installation candidate`

tnx

**Comment by trsh** [comment]
Im on ubuntu 17.x

**Comment by dantti** [comment]
This is usually required to build the uWSGI plugin, and on newer distros it has **libzmq3-dev**

**Comment by dantti** [comment]
if you use cutelyst-wsgi you can skip uWSGI dependencies.

**Comment by trsh** [comment]
Ok! Clear.
