### ISSUE TITLE
[feature request] please raise an error for missing templates in debug mode

### ISSUE THREAD

**Issue by trsh** [cutelyst/cutelyst#127]
Right now:

 c->setStash("template", "non_existent_template.html");

is just Ignored, and blank space is returned.

**Comment by dantti** [comment]
Yeah, unfortunately I believe this issue belongs to Grantlee, need to further investigate but IIRC there was no error when templates were missing

**Comment by trsh** [comment]
I also start to think so, as other template engine produces errors. But anyway Grantlee is better way to go for me.

**Comment by dantti** [comment]
Sure, I have some fixes to do to it, and will eventually fork it if it still doesn't get attention from the author... :(

**Comment by trsh** [comment]
@dantti maybe it's time to google / switch to other more _relevant_ tempting engines (if there are some). I can do some research and propose something :) . Maybe create an PR.

**Comment by dantti** [comment]
I already did that, this is very well integrated with Qt, it only lacks maintenance, I did a bunch of improvements there but the slow responses to PR and ISSUES there kills my energy...

**Comment by dantti** [comment]
Please test :)

**Comment by trsh** [comment]
Will do this week
