### ISSUE TITLE
[question] about static files

### ISSUE THREAD

**Issue by trsh** [cutelyst/cutelyst#129]
Depending on user AC, I need to allow or to forbid some static assets. Do not need something very fancy, so I tough maybe it's doable via StaticSimple? Or not?

**Comment by trsh** [comment]
Looked at class. look like not :). Any suggestion. Just roll something similar in project scope?

**Comment by dantti** [comment]
If you are going to use some front end server like NGINX https://www.nginx.com/resources/wiki/start/topics/examples/x-accel/ cutelyst-wsgi static-map or StaticSimple doesn't provide that ATM

**Comment by trsh** [comment]
Clear!

**Comment by trsh** [comment]
@dantti 

But maybe I can clone StaticSimple, and before serving static, call some Check function, that if fails, returns 403 code?

**Comment by dantti** [comment]
>I tried to extend, but the needed func. are private.

Right well that's not the intended use case. You can also open a QFile and set it as c->response->setBody(file);
However this doesn't take care of the content-type, so you would need to set it manually.

**Comment by trsh** [comment]
One more q. How must I run the project to see qDebug() displayed?? It's kind of not, qWarning is

**Comment by dantti** [comment]
you need to configure that using QT_LOGGING_RULES env variable, like
>export QT_LOGGING_RULES=*=true

Will display ALL logging
