### ISSUE TITLE
Static builds

### ISSUE THREAD

**Issue by GorodetskijPavel** [cutelyst/cutelyst#131]
Hello Daniel!
Thanks for your project, it's really good ...
I have two questions:

1. The size of the wsgi-server and all the plugin files is small. You tried to do static builds all in one? This is useful for inserting the server into other applications.
2. You as a wsgi-server developer advise the most effective protocol - HTTP, FastCGI or uWSGI for wsgi-server operation behind Nginx?

Thank you, Aleksey Gorodetsky.

**Comment by dantti** [comment]
1. No, never tried
2. From my benchmarks using Nginx HTTP proxy pass had the best performance, however I use FastCGI due being able to easily get client IP. IMHO now that I know the protocols I believe uwsgi protocol has no benefit over FastCGI as it doesn't support keep-alive, and this is the feature that makes much more difference than sending the request in binary form.

**Comment by GorodetskijPavel** [comment]
On the second question the answer is full.
On the first question I will do static builds myself. If all goes well, accept the changes in CMakeLists.txt?

**Comment by dantti** [comment]
> If all goes well, accept the changes in CMakeLists.txt?

Yes, assuming they don't over complicate the files, still I'm not entirely sure why this is useful.

**Comment by dantti** [comment]
Cutelyst-wsgi is already a lib, so you can build all into a single executable, but at the moment all is built in dynamic way with .dlls or .so or .dynlib depending on the OS

**Comment by GorodetskijPavel** [comment]
Daniel!
I'm looking at the API (http://api.cutelyst.org/) and understand that I can manage the wsgi-server and my web-application. But how do I correctly connect my desktop process (application) to the wsgi-server and my web-application? 
How to replace cutelyst-wsgi2.exe with cutelyst-wsgi2.dll without making changes to the CMakeLists.txt, without replacing add_executable() with add_library()? Need to make changes in the CMakeLists.txt?

**Comment by dantti** [comment]
you just link to cutelyst::wsgi module and call [CWSGI::WSGI::start(ptr to your webapp)](http://api.cutelyst.org/classCWSGI_1_1WSGI.html#ab7340057c3e7e9b4bef0ad1055fc1f92)

**Comment by dantti** [comment]
you do not replace add_executable with add_library(), you just:

```
target_link_libraries(cutelyst-skell
    PRIVATE Qt5::Core
    PRIVATE Qt5::Network
    PRIVATE Cutelyst2Qt5::WSGI
)
```

**Comment by GorodetskijPavel** [comment]
That is, I do the opposite, I insert my application into wsgi-server?

**Comment by dantti** [comment]
If I understood correctly you have a GUI app, and would like the same app binary to have Cutelyst build it, right?
If so, then you just link your GUI app to Cutelyst::WSGI and the other modules you use from Cutelyst, then you setup your Cutelyst::Application subclass with that function I told you.

**Comment by AlekseyGorodetsky** [comment]
Thank you Daniel!
I tried to do static builds.
With Grantlee already all was going well.
Thank you for your very useful work.

Aleksey Gorodetsky

2018-04-19 15:50 GMT+03:00 Daniel Nicoletti <notifications@github.com>:
