### ISSUE TITLE
Problem Building in Xubuntu 18.04

### ISSUE THREAD

**Issue by elros88** [cutelyst/cutelyst#133]
Hi, I'm having this error when trying to build Cutelyst in Xubuntu 18.04 when using `cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ALL=on
`

`CMake Error at Cutelyst/Plugins/View/CMakeLists.txt:21 (find_package):
  By not providing "FindSimpleMailQt5.cmake" in CMAKE_MODULE_PATH this
  project has asked CMake to find a package configuration file provided by
  "SimpleMailQt5", but CMake did not find one.

  Could not find a package configuration file provided by "SimpleMailQt5"
  with any of the following names:

    SimpleMailQt5Config.cmake
    simplemailqt5-config.cmake

  Add the installation prefix of "SimpleMailQt5" to CMAKE_PREFIX_PATH or set
  "SimpleMailQt5_DIR" to a directory containing one of the above files.  If
  "SimpleMailQt5" provides a separate development package or SDK, be sure it
  has been installed.

-- Configuring incomplete, errors occurred!`

I don't know if this is the right place to ask for help, but can't find an answer in google

**Comment by dantti** [comment]
You need to install [SimpleMail](https://github.com/cutelyst/simple-mail) or disable it's plugin with -DPLUGIN_VIEW_EMAIL=off
