### ISSUE TITLE
assert may fail in EventDispatcherEPollPrivate::registerSocketNotifier when compiled in debug mode

### ISSUE THREAD

**Issue by DerSauron** [cutelyst/cutelyst#134]
When compiling cutelyst in debug mode (enabling the `Q_ASSERT` macros). Running CMlyst (for example) may abort at  `Q_ASSERT(!m_notifiers.contains(notifier));` in file EventLoopEPool/socknot_p.cpp.

It fails when a `QSocketNotifier` is registered twice with the same fd on different events. I didn't dig into the code very deeply but from my understandings this is explicitly allowed. So the `Q_ASSERT` will fail in a legal state.

My succession is to replace the `Q_ASSERT` with an `if` so the `SocketNotifierInfo` isn't copied into the hash table when it is already there. Or to omit the line completely and always insert the `SocketNotifierInfo` as it is already the case when compiling in release mode.

Or am I completely wrong?

**Comment by dantti** [comment]
Hmm thanks for you info, I'll need to take a closer look into this because as far as I know it shouldn't be allowed to register an fd twice.

**Comment by dantti** [comment]
hmm thanks, the QSocketNotifier cannot be reused as it has no setFD function, but what will probably happen is that it get's the same pointer address of another unregistered and deleted one, or if one toggles setEnabled().
I'll take a closer look at that part, because it was a fix for another problem so I need to think carefully to avoid another regression...

**Comment by DerSauron** [comment]
If the requests came closely after each other the socket isn't closed after the first request and handles the second one, too. This lead to calls to setEnable(true) and setEnable(false) for each response on the the same wite-QSocketNotifier object.
Nevertheless, even if this is not going to be happen, it still leaves the addresses of disabled and deleted QSocketNotifiers in the hash table.
This is because the read- and the write-notifier of a socket (fd) can be active at the same time and un-registering the write-notifier does not remove it from the hash, because the read-notifier is still active.

**Comment by dantti** [comment]
please test :)

**Comment by DerSauron** [comment]
Ok, that was fast. And it looks good. QSocketNotifier's can be registered multiple times, and it doesn't leaves orphant entries in the hash.
Thanks

**Comment by dantti** [comment]
you welcome
