### ISSUE TITLE
Just a quick question before I start playing with cutelyst

### ISSUE THREAD

**Issue by ShamanTcler** [cutelyst/cutelyst#139]
Can it be built with MSVS 2015, compiler version 14, And Qt 5.9.+

I am afraid I am stuck with these two. Here is a link to MS standards compliance:

https://msdn.microsoft.com/en-us/library/hh567368.aspx

Regards
Carl

**Comment by dantti** [comment]
Yes, though I don't use Windows so I can't help much.
Here is our CI build matrix:
https://ci.appveyor.com/project/dantti/cutelyst/branch/master
