### ISSUE TITLE
Unable to load Grantlee template from examples

### ISSUE THREAD

**Issue by Alko89** [cutelyst/cutelyst#14]
Using Tutorial_02 I get errors when trying to load Grantlee template:

> *** Operational MODE: single process ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 22351)
spawned uWSGI worker 1 (pid: 22352, cores: 1)
cutelyst.uwsgi[debug] Cutelyst loading application: /home/alko/Development/Qt/Capoeira/CutelystSandBox/Hello/build/src/libHello.so
cutelyst.uwsgi[debug] Loaded application: "Hello"
/usr/bin/uwsgi: symbol lookup error: /home/alko/Development/Qt/Capoeira/CutelystSandBox/Hello/build/src/libHello.so: undefined symbol: _ZN8Cutelyst12GrantleeViewC1EP7QObjectRK7QString
DAMN ! worker 1 (pid: 22352) died :( trying respawn ...
Respawned uWSGI worker 1 (new pid: 22353)
cutelyst.uwsgi[debug] Cutelyst loading application: /home/alko/Development/Qt/Capoeira/CutelystSandBox/Hello/build/src/libHello.so
cutelyst.uwsgi[debug] Loaded application: "Hello"
/usr/bin/uwsgi: symbol lookup error: /home/alko/Development/Qt/Capoeira/CutelystSandBox/Hello/build/src/libHello.so: undefined symbol: _ZN8Cutelyst12GrantleeViewC1EP7QObjectRK7QString

Tutorial_03 still has the old ViewEngine, which was removed in 0.10.0

**Comment by dantti** [comment]
I need to review the tutorial then, to fix this you need to link against: Cutelyst::View::Grantlee.

**Comment by dantti** [comment]
This tutorial page has been fixed, thanks

**Comment by dantti** [comment]
Fixed Tutorial_03 too

**Comment by Alko89** [comment]
Great! I can start learning now :)

**Comment by dantti** [comment]
I'm writting the tutorial steps on this repo, so that you can compare if you understand the steps:
https://github.com/cutelyst/cutelyst-tutorial
