### ISSUE TITLE
Instructions for Arch Linux or Manjaro

### ISSUE THREAD

**Issue by Light-Wizzard** [cutelyst/cutelyst#140]
clearsilver was removed from the main repository so the following no longer works.
pacman -S clearsilver
If can be found in use AUR:
yaourt -S clearsilver
Note its flagged as out of date, but it installed for me with no errors.
https://aur.archlinux.org/packages/clearsilver/
It seems only bug fixes are maintained, that could mean its stable.

**Comment by dantti** [comment]
The instructions are in the Wiki which you can edit it yourself :)
It's also an optional dependency.
Thanks
