### ISSUE TITLE
Use Javascript

### ISSUE THREAD

**Issue by pedro-vicente** [cutelyst/cutelyst#142]
I am trying to run some JavaScript into Cutelyst;
I started with a basic generated project, and changed to this code, that uses the 'alert' function to display a variable that was defined in C++ (the all point of using a c++ web framework);

it works  :-)
```

void Root::index(Context *c)
{
  int n = 5;
  std::ostringstream strm;
  strm
    << "<H1>test</H1>"
    << "<script>"
    << "alert('value of n is ' + ";
  strm
    << std::to_string(n);
  strm
    << ")"
    << "</script>";
  c->response()->body() = strm.str().c_str();
}

```

I went to Firefox and used the debugger (key F12) to see the rendered HTML.
Firefox diplays this HTML

`<html><head></head><body><h1>test</h1><script>alert('value of n is ' + 5)</script></body></html>`

My goal is to use the Leaflet library

https://leafletjs.com/

 to display some information stored in the C++ program;
I used this simple example;

however, the map does not render on the browser; below the code is the similar HTML code that can be used to display the map in a browser;

thanks

### the C++ code
```

void Root::index(Context *c)
{
  std::ostringstream strm;
  strm
    << "<link rel='stylesheet' href='https://unpkg.com/leaflet@1.3.4/dist/leaflet.css'/>"
    << "<script src='https://unpkg.com/leaflet@1.3.4/dist/leaflet.js'></script>"
    << "<div id = 'map'></div>"
    << "<style>#map{ height: 100 % ; } html, body {height: 100%;margin: 0;padding: 0;}</style>"
    << "<script>"
    << "var layer_base = L.tileLayer(\n"
    << "'http://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png',{\n"
    << "opacity: 1\n"
    << "});\n"
    << "var map = new L.Map('map', {\n"
    << "center: new L.LatLng(37.0902, -95.7129),\n"
    << "zoom: 5,\n"
    << "layers: [layer_base]\n"
    << "});\n"
    << "</script>";
  c->response()->body() = strm.str().c_str();
}
```

### the HTML code

```
<!DOCTYPE html>
<html>
<head>
<title>Map</title>
<link rel='stylesheet' href='https://unpkg.com/leaflet@1.3.4/dist/leaflet.css' />
<script src='https://unpkg.com/leaflet@1.3.4/dist/leaflet.js'></script>
<style>
#map { height: 100%;}
html, body {
height: 100%;
margin: 0;
padding: 0;
}
</style>
</head>
<body>
<div id='map'></div>
<script>
var layer_base = L.tileLayer(
'http://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png',{
opacity: 1
});

var map = new L.Map('map', {
center: new L.LatLng(37.0902, -95.7129),
zoom: 5,
layers: [layer_base]
});
</script>
</body>
</html>


```

**Comment by dantti** [comment]
You need to set the Content-Type header, I'd also recommend using either QTextStream or Grantlee.
Although for your use-case it seems that you need a static page and send the dynamic data as JSON which would make the code simpler and faster.

**Comment by pedro-vicente** [comment]
yes, a static web page is the way to go; this was just a test;

then the dynamic JavaScript, like the map creation, is done from C++ and calling the web engine sending the script as a C++ string;

I did a similar app with Qt using QWebEngineView, which is Qt's own web engine;
here I'm trying to do the same for a web browser;

in my Qt app I use a HTML "template", that just loads the JavaScript libraries locally, and adds a 'div' to the page , that is needed by Leaflet

this template

```
<!DOCTYPE html>
<html>
<head>
<title>Leaflet</title>
<link rel="stylesheet" href="qrc:///leaflet.css" />
<link rel="stylesheet" href="qrc:///mapbox-gl.css" />
<script src="qrc:///leaflet.js"></script>
<script src="qrc:///mapbox-gl.js"></script>
<script src="qrc:///leaflet-mapbox-gl.js"></script>
<style>
#map { height: 100%;}
html, body {
height: 100%;
margin: 0;
padding: 0;
}
</style>
</head>
<body>
<div id="map"></div>
</body>
</html>

```

that is loaded by Qt like this
```

 m_webview = new WebView(this);
  m_webview->load(QUrl("qrc:///leaflet.html"));
  setCentralWidget(m_webview);
```

how could I achieve the same here,  load the HTML and JavaScript from local files?

**Comment by dantti** [comment]
if you want to serve the file statically, you can:

- Use a front-end HTTP server (NGINX, Apache..)
- Set a StaticMap like setStaticMap({ "/static=/path/to/files" });
- Serve the file in a Controller

To serve a file from a Controller:
you can 
auto file = new QFile("page.html")
or 
auto file = new QFile("qrc:///page.html"); // If it's added to Qt resources
then
file->open();
response->setBody(file);

**Comment by pedro-vicente** [comment]
major success.
happy customer here

```

void Root::index(Context *c)
{
  QString fname = tr("leaflet-cartodb.html");
  QFile file(fname);
  if (!file.open(QIODevice::ReadOnly))
  {
    qDebug() << fname;
  }
  QTextStream in(&file);
  QString body = in.readAll();
  qDebug() << file.size() << "\n" << body;
  file.close();
  c->response()->body() = body.toUtf8();
}
```

**Comment by dantti** [comment]
ok, can we close this one?

About your code, not sure you know but:
tr("...") should only be used for translations, and in Cutelyst it won't work properly if the application needs to serve many languages, (there is a proper way to do that)

if you don't need to inspect the content of the file
then it's better to just c->response()->setBody(file); // QFile must be a pointer here

**Comment by pedro-vicente** [comment]
> ok, can we close this one?

yes, we can close this one, thanks

>>tr("...") should only be used for translation

no , I did not know that. I copied that from some old QT code I had because I could not understand why the simple

QString str = "a string";

is not accepted by Qt (apparently the conversion from char* is private)... go figure.
These days I actually use mostly wxWidgets instead of Qt; wxWidgets also has its own String class.

I still have a small issue with the  path of the HTML file.

In Windows , doing

`QString fname = tr("leaflet-cartodb.html");`

this path is the path where Cmake generated the Visual Studio project;
it would be good if it is possible to specify using the QFile option the path being inside the source, like in /root

I also tried to use QRC

"qrc:///page.html"

but could not figure where the .qrc file should be located and what path does it mean; plus that Cmake has to call the QRC compiler too

**Comment by dantti** [comment]
QString str = "a string";
is fine as long as QT_NO_CAST_FROM_ASCII is not defined, the problem with casting from char * is that it will convert that to UTF-8 everytime which is a bit slow, so QString str = QLatin1String("a string") is a lot faster but QString str = QStringLiteral("a string") is even better.

hope this helps:
https://woboq.com/blog/qstringliteral.html

About the path, the way you did is going to be relative where your executable is running, for QRC I recommend you reading some docs about it as it's also rather simple, especially if you use QtCreator
