### ISSUE TITLE
StaticSimple::setDirs() and StaticCompressed::setDirs() have no effect

### ISSUE THREAD

**Issue by Innokentiy-Alaytsev** [cutelyst/cutelyst#145]
Hello!

It seems like the documentation for the `StaticSimple::setDirs()` and `StaticCompressed::setDirs()` is a bit misleading because as far as I can see in the code the side effect of these member functions call is not used, because the `d_ptr->dirs` member variable value is not used for locating the static files. 

There are two ways out of this problem:

1. Remove the function from the plugin API.

2. Fix the StaticSimple and StaticCompressedPrivate plugins to actually use the `d_ptr->dirs` while looking for the static files.

If I am missing something, please correct me - I might have overlooked something.

Best regards,
Innonentiy

**Comment by dantti** [comment]
Thanks, it should be fixed now, although for StaticSimple I recommend using StaticMap option of WSGI module or even Apache/NGINX file serving features.

**Comment by Innokentiy-Alaytsev** [comment]
Hello!

Thanks a lot for the quick fix and pointing on StaticMap option!

I've considered the option of using NGINX for serving static files but decided to use StaticSimple or StaticCompressed because a heavy load is highly unlikely for the application being developed (Web UI for a single concurrent user) and managing even simple NGINX configuration is another bit of work to do.
