### ISSUE TITLE
How to terminate a chained action?

### ISSUE THREAD

**Issue by starccy** [cutelyst/cutelyst#148]
Image there is a URL like: "http://localhost:3000/foo/v1.0.0/bar".
**"v1.0.0"** in the middle is some API version, and it will be changed often.
the code can be:
```cpp
C_ATTR(foo, :Chained("/") :PathPart("foo") :CaptureArgs(1))
void foo(Context *c, QString version);

C_ATTR(bar, :Chained("foo") :PathPart("bar") :Args(0))
void bar(Context *c);
```
In the **foo** method, I need to get this request version, and compare to my current api version where I defined in a config file. if they are mismatching, I should terminate this action to prevent it execute **bar** action. 

I try to response a 404 code in the **foo** method, however the **bar** action would still be execute.Now I have no idea how to do this.

Please give me some advice.Thanks.

**Comment by dantti** [comment]
IIRC c->detach(); is what you want

**Comment by starccy** [comment]
It works.Thanks!
