### ISSUE TITLE
Documentation for Apache support in Windows.

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#150]
Please, provide documentation on how to use cutelyst-wsgi2.exe in Windows with Apache as a reverse proxy.

**Comment by dantti** [comment]
There's already lots of documentation on how to do that with FastCGI:
https://wiki.apache.org/httpd/HelpOnInstalling/ApacheOnWin32withFastCgi

You can also use mod_proxy:
https://httpd.apache.org/docs/2.4/howto/reverse_proxy.html

For FastCGI you use --fastcgi-socket :3000 to open a FastCGI 3000 port or 
for HTTP you use --http-socket :3000 to open a HTTP 3000 port.

**Comment by arietto** [comment]
Thank you for quick reply.
