### ISSUE TITLE
Request forwarding to remote REST server

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#155]
Hello. Let's assume that we have a REST service tree (distributed system). If some node B receives a certain request from its child node C, it must forward this request to its parent A. How can it be achieved using cutelyst? I'd like to avoid redundant converting raw request body into Qt classes instances.   Should I use QNAM (QNetworkAccessManager) directly in the corresponding `Controller` descendant method?

**Comment by dantti** [comment]
If I understand correctly yes, QNAM would allow you to create a new HTTP request to another service, however due it being ASYNC you will have problems using it.
Once Async is fixed in Cutelyst, the QNAM or any onther async API will be possible.

**Comment by arietto** [comment]
Can you please explain what's wrong with async? I'd like to return `200 OK` after async QNAM request emitting. I won't wait for `QNAM replyFinished` in order to return `200 OK` in `redirector` method.
Do you mean that we can't use signals-slots when we deal with different threads?

**Comment by arietto** [comment]
OK, thanks.
