### ISSUE TITLE
Simultaneous request handling.

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#156]
I've written a dummy `Controller` GET method which calls `QThread::sleep(5);` before responding. I send two requests simultaneously in other Qt-based application using `QNAM` as a REST client. I expect that I receive two replies in 5.x seconds. But I receive the last reply in 10.x seconds. It means sequential handling. `QThread::currentThreadId()` shows the same id in the `Controller` handler. 
I use the following command (4 threads)
`cutelyst-wsgi2 --application d:\projects\current\REST\node_server\build\src\Debug\node_serverd.dll --http-socket localhost:3000 --master -t 4`
What should I do for parallel request handling?

**Comment by dantti** [comment]
On Linux you have SO_REUSEPORT which balances new connections to different threads/forks on Windows there's no such mechanism, and even if there was there is no guarantee that the balancer won't send 2 or more connections to a single thread before sending new connections to other threads.

**Comment by arietto** [comment]
Thank you. But I have more questions, sorry for disturbing. 
1) Is setting thread count without --experimental-thread-balancer senseless for cutelyst-wsgi2.exe?
2) I'd like my service to load some settings from `QSettings` instance. Where should I call it (especially if there are more than 1 process)? I see multiple duplicate log messages, because `Controller` instance is created multiple times, so `Controller` ctor is a bad place for loading settings.
3) What's the purpose of the master mode? When should it be activated (benefits)? 
4) "lazy mode load app in workers instead of master" - Do you mean child processes? lazy mode is senseless if no --master provided?

**Comment by arietto** [comment]
I suppose that loading custom settings can be done in `Application` descendant ctor and not in `init()`. Am I right?

**Comment by dantti** [comment]
> Thank you. But I have more questions, sorry for disturbing.
> 
> 1. Is setting thread count without --experimental-thread-balancer senseless for cutelyst-wsgi2.exe?

The experimental-thread-balancer should do what you want, BUT it was made for UNIX so I'm not sure it works on Windows and since SO_REUSEPORT is a much better option I haven't tested it much.

> 2. I'd like my service to load some settings from `QSettings` instance. Where should I call it (especially if there are more than 1 process)? I see multiple duplicate log messages, because `Controller` instance is created multiple times, so `Controller` ctor is a bad place for loading settings.

Each thread/process instantiate a new Application and child controllers, so when using it on threaded application care must be taken with static member variables.

> 3. What's the purpose of the master mode? When should it be activated (benefits)?

Master is a process that keeps an eye on the child process to restart workers when they die.

> 4. "lazy mode load app in workers instead of master" - Do you mean child processes? lazy mode is senseless if no --master provided?

When --lazy is enabled the Master process will not load the application, it will instead be instantiated in the child, this is always true on Windows since I don't know a fork() alternative. The benefit of not using --lazy on UNIX is that your process will share read only memory thus using less RAM

**Comment by dantti** [comment]
> I suppose that loading custom settings can be done in `Application` descendant ctor and not in `init()`. Am I right?

If you are going to use Cutelyst::Application->config() then use it after init() has been called, just don't use anything that might need thread affinity before postFork() is called, opening QSettings file on ctor is fine, opening DB connection is not.

**Comment by dantti** [comment]
Closing as I believe the questions have been answered.

**Comment by arietto** [comment]
Thank you for the quick and full answer, sir!
