### ISSUE TITLE
cutelyst-wsgi dead loop

### ISSUE THREAD

**Issue by tynqq** [cutelyst/cutelyst#157]
hello!

I go through the file wsgi/protocolhttp2.cpp, and find some issue in line 164. here is the code:
`                        } else {`
`//                            qCDebug(CWSGI_H2) << "Wrong preface";`
`                            ret = sendGoAway(io, request->maxStreamId, ErrorProtocolError);`
`                        }`
the question is do we need a `break;` here?

I ran cutelyst-wsgi with --h2, but I sent a HTTP 1.1 request to test it.
it seems that the cutelyst-wsgi fail to response and run into endless loop when executing `ProtocolHttp2::parse`.

Thanks!

**Comment by dantti** [comment]
--h2 is HTTP2 only, which means a HTTP1.1 request will never be properly answered, about the endless loop do you have a backtrace?
If you want to sever HTTP1.1 on the same socket you must use --upgrade-h2c or when HTTPS is available --https-h2.

**Comment by tynqq** [comment]
yes, you are right. with --h2, the HTTP 1.1 request should not be properly answered; but there should never be a dead loop when handing HTTP 1.1 requests.
please kindly review the method `ProtocolHttp2::parse`

`148             while (request->buf_size && ret == 0) {`

**(1), request-buf_size and ret is checked here**

`149 //                qDebug() << "Current buffer size" << request->connState << request->buf_size;//QByteArray(request->buffer, request->buf_size);`
`150                 if (request->connState == ProtoRequestHttp2::MethodLine) {`
`151                     if (request->buf_size >= PREFACE_SIZE) {`

**(2), condition `request->buf_size >= PREFACE_SIZE` could be satisfied**

`152                         if (memcmp(request->buffer, "PRI * HTTP/2.0\r\n\r\nSM\r\n\r\n", 24) == 0) {`

**(3), this condition should not be met when handing HTTP 1.1**

`153 //                            qCDebug(CWSGI_H2) << "Got MAGIC" << sizeof(struct h2_frame);`
`154                             request->buf_size -= PREFACE_SIZE;`
`155                             memmove(request->buffer, request->buffer + PREFACE_SIZE, size_t(request->buf_size));`
`156                             request->connState = ProtoRequestHttp2::H2Frames;`
`158                             sendSettings(io, {`
`159                                              { SETTINGS_MAX_FRAME_SIZE, m_maxFrameSize },`
`160                                              { SETTINGS_HEADER_TABLE_SIZE, m_headerTableSize },`
`161                                          });`
`162                         } else {`

**(4), so we come to this part**

`163 //                            qCDebug(CWSGI_H2) << "Wrong preface";`
`164                             ret = sendGoAway(io, request->maxStreamId, ErrorProtocolError);`

**(5), ret is 0 when sendGoAway returns, so the loop go back to (1), again and again**
**(6), add a `break` here?**

`165                         }`
`166                     } else {`
`167 //                        qDebug() << "MAGIC needs more data" << bytesAvailable;`
`168                         break;`
`169                     }`
`170                 } else if (request->connState == ProtoRequestHttp2::H2Frames) {`

**Comment by dantti** [comment]
You are right, I just need to remember if there's some special msg I should send back
