### ISSUE TITLE
Empty client address in Context instance

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#158]
Hello! I have a `Controller` descendant. I try to print client address in `Controller` POST handler. `c->req()->addressString()` is empty(). I use some REST test extension in Firefox in order to test my REST service on localhost. I've put some debug messages in `bool ProtocolHttp::processRequest(Socket *sock, QIODevice *io) const` (near 207 row):
    `qDebug() << "ProtocolHttp::processRequest sock" <<  sock->remoteAddress << sock->remotePort    << sock->serverAddress;`
`qDebug() << "ProtocolHttp::processRequest request" << request->remoteAddress <<request->remotePort << request->serverAddress;` .
I've got the following output:
[30-11-2018, 11:04:19] [Debug] <CWSGI::ProtocolHttp::processRequest>:207 ProtocolHttp::processRequest sock QHostAddress("127.0.0.1") 55098 "0.0.0.0:3000"
[30-11-2018, 11:04:19] [Debug] <CWSGI::ProtocolHttp::processRequest>:209 ProtocolHttp::processRequest request QHostAddress("") 0 "localhost:3000"

**Comment by arietto** [comment]
Perhaps, the problem is linked with `ProtoRequestHttp` ctor, it does not fill `EngineRequest `fields (using socket as a source). `ProtoRequestHttp::ProtoRequestHttp(Socket *sock, int bufferSize) : ProtocolData(sock, bufferSize)
{
    startOfRequest = 0;
}`

**Comment by dantti** [comment]
Are you running the last master version? I have fixed an issue related to this recently

**Comment by arietto** [comment]
Yes, sorry, I used an outdated version (tests: Check if multipart/form-data is filling bodyParams 2f3a8d094e6b3bbe50f093474157bc998952f165c).
