### ISSUE TITLE
Web controls

### ISSUE THREAD

**Issue by joeblew99** [cutelyst/cutelyst#16]
I am wondering if a done knows of material design web components that can be code generated from QML ?

The reason I ask this is because at the moment we all use QML to build normal Qt apps, but if we could use the same QML if there was a library to code gen JavaScript from QML for example.

**Comment by dantti** [comment]
Sorry I don't really get what your ISSUE is, Cutelyst ATM is C++ only, there are plans to expose it to a declarative (QML) interface but that's for future.
There is a projejct https://github.com/qmlweb/qmlweb that might be what you are looking for.

**Comment by c-cesar** [comment]
Not reopening, but Silk is a more "web framework"solution for this.
http://silk.qtquick.me/

**Comment by joeblew99** [comment]
@ccesar

thats perfect thanks for the link to Silk & QMLweb
