### ISSUE TITLE
Executing common (shared) tasks in Cutelyst

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#161]
Hello! What good practices can you advise for executing common tasks if we deal with multiple threads mode in Cutelyst?
For example, we have to do some task periodically in a single thread. Where should this method be put? I mean that if we have N threads then we have multiple `Application` and `Controller` instances. Should I use `timerEvent`? I don't want execution duplication.

**Comment by dantti** [comment]
The best place to put a QTimer to run only in one worker is on your Application::postFork() and check for [Engine::isZeroWorker()](https://api.cutelyst.org/classCutelyst_1_1Engine.html#a749b5db511efc55899fc6891906a2840)
it returns true for the first forked process and first thread, of course if you launch 2 cutelyst-wsgi instances this won't work as you expect.

**Comment by arietto** [comment]
Thank you, I use single-process multiple-threads mode for simplicity in my intranet REST service.
