### ISSUE TITLE
Retrieving server port

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#163]
Hown can I retrieve my own port (default is 3000) within `Controller` handler?

**Comment by arietto** [comment]
I use `c->req()->uri().port();` 
Is it OK? I need to pass this port to another REST server (for seldom intercommunication).

**Comment by dantti** [comment]
Yes, this is probably the best way to get the port, as it will still be fine if you are behing Nginx (or apache...) and using FastCGI.

**Comment by arietto** [comment]
OK, thanks.

**Comment by arietto** [comment]
Sorry, I forgot to ask one more related thing. What about other places in `Controller`? For example, I'd like to retrieve my port inside `Controller::postFork()` (when no `Context* c` is available).

**Comment by dantti** [comment]
Then there's no reliable way to do that. The Engine class of WSGI holds that information, although not available to the application but that's not a trusted information, if you are running behind a Nginx with UNIX socket there's not even a local port (as it's UNIX socket).

If you really need some way to get that on postFork() I suggest having it on a config file.

**Comment by arietto** [comment]
OK, I'll consider this workaround.
