### ISSUE TITLE
Thread balancer is not set through ini file

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#164]
I've created ini file.
Its fragment:
[wsgi]
experimental-thread-balancer=true
But d->threadBalancer is set only from cmd line (wsgi.cpp:500).

PS. By the way, what is the purpose of sectioning JSON/INI filename (see below)? What if I pass full path to ini file with colon in Windows? 
Like `cutelyst-wsgi2.exe --ini D:/projects/blabla/wsgi.ini`
void WSGIPrivate::loadConfig(const QString &file, bool json)
{
    QString filename = file;

    QString section = QStringLiteral("wsgi");
    if (filename.contains(QLatin1Char(':'))) {
        section = filename.section(QLatin1Char(':'), -1, 1);
        filename = filename.section(QLatin1Char(':'), 0, -2);
    }

**Comment by dantti** [comment]
Well it's experimental, I don't want to compromise any API as it might even be removed.

The sectioning will indeed break on windows..  could also break on Unix but it's quite rare to use this delimiter in file names.

The purpose is to set the INI section on where to look for configs, say you want to test with both uWSGI and Cutelyst-WSGI using the same config section.

**Comment by arietto** [comment]
If the thread balancer might be deprecated and we have single-process multithreaded mode, what will happen with threads in case of multiple HTTP requests in Linux? Will they be idle except for the first one?

**Comment by dantti** [comment]
On Linux just enable SO_REUSEPORT and the kernel will balance the connections, otherwise the thread that accepts the connection first wins.

**Comment by arietto** [comment]
Thanks.
