### ISSUE TITLE
More settings related documentation required

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#165]
Hello! I've noticed that in order to use custom settings, I have to add section "[Cutelyst]". This hard-coded name is not evident for newcomers, only source analyzing has helped. I mean that it would be nice to have a small separate chapter in the documentation concerning INI/JSON settings and some tiny examples. 
For example, allowed format for "http-socket" property should be mentioned.

**Comment by buschmann23** [comment]
Done in https://github.com/cutelyst/cutelyst/pull/440
