### ISSUE TITLE
reverse proxy support with SSL termination

### ISSUE THREAD

**Issue by sibbi77** [cutelyst/cutelyst#170]
I'm currently using a setup, where I have a reverse proxy with SSL termination and a cutelyst app which listens on an unencrypted http port. The problem with this scenario is: urls are all http:// and not https://.
Catalyst has a specific configuration option for this use case: [Catalyst proxy support](https://metacpan.org/pod/release/FLORA/Catalyst-Runtime-5.90004/lib/Catalyst.pm#PROXY-SUPPORT)

Is it possible to implement s.th. like that in Cutelyst?

**Comment by dantti** [comment]
It's possible by adding some code to WSGI HTTP parse, I usually prefer using FastCGI as this is not an issue there.
It must also be disabled by default to avoid having an user to pretend to be from a different IP in case no front end server is set.

**Comment by sibbi77** [comment]
I tried fastcgi, but it didn't work.
I now tracked it down to ProtoRequestFastCGI::doWrite() returning WSGI_OK, instead of the number of written bytes.

**Comment by sibbi77** [comment]
Just learned that fastcgi cannot handle Websockets...
Back to reverse proxying the http connection. I'll try to come up with a patch to support a reverse proxy.

**Comment by dantti** [comment]
Yup, nor does HTTP/2 which means HTTP/1.1 is likely to never die...
