### ISSUE TITLE
[Feature Request - docs] Lack of docs related to advanced Cutelyst usage & Websockets (especially for new comers)

### ISSUE THREAD

**Issue by mike23456** [cutelyst/cutelyst#177]
Hi there,
First of all, I would like to thank you Daniel for all the amazing and QUALITY work you've done on this framework.

I came to know about Cutelyst only a week ago and the clear tutorials on the wiki helped to set up a REST service in NO TIME! However, I find the docs very lacking especially for more advanced use cases and for newcomers.  Moreover, the wiki docs don't say a thing about the internal workings of WSGI (you have to manually look into source files /API docs, yet that info is not enough). Also the wiki doesn't mention how to use the WSGI server instead of the development server (newcomers have to look into the hello world echo server example which they might not find easily).  

For example, I am currently stuck trying to implement my use case:
I am trying to implement PostgreSQL LISTEN/NOTIFY (Push Notifications) over websockets cuz i have an existing app which is very old school client/server architecture (PosgreSql is the server). I wanna add a middleware (REST API) between the database and the existing (Qt c++ client) so the following questions are on my mind and would be grateful for any help:

1. How to find out the total number of connected clients & identify them if possible?
2. How to broadcast a websocket text message(Qstring) to all connected clients at once?
3. I need to keep a list of all connected clients (through websockets) and keep track of which ones are subscribed to a particular PostgreSQL notifications channel.
4. Does Cutelyst support TLS 1.3? or TLS 1.2? 
5. How to force HTTP1.1?

NOTE: I know how to implement the HTTP REST API using Cutelyst, my problem is with push notifications over websockets as this functionality is critical to the existing app.

The above mentioned tasks can be easily achieved with Node.js using ws or socket.io. However I am C++ programmer and fell in love with Qt at first sight so I would like to avoid using javascript and Node as much as I can. C++ FTW!
 
BTW, i  looked at many Cutelyst sources but couldn't find an answer to those simple questions. 

Regards,

**Comment by mike23456** [comment]
Regarding item 4 (TLS support). I just noticed you are using QSslConfiguration in the file tcpserverbalancer.cpp.

m_sslConfiguration = new QSslConfiguration

This can be used to change the protocol to TLS v1.2 or 1.3. However we dont have access to this object as it's a private member so can you provide an option to set our own QSslConfiguration through WSGI public api? An alternative would be to specify the encryption protocol as a command line argument before launching Cutelyst WSGI server?

**Comment by dantti** [comment]
Sorry, totally forgot to answer this one.

1. Cutelyst doesn't have an API for that, it's a complex subject because you can have the same app on several machines, or in separated process/threads so if you need this it's up to you on how are you going to merge this information
2. Again this is something that depends on your deployment, if you have a single process/thread you can have a signal that get's connected to all websockets clients.
3. Since DB connections must have thread affinity, and we need to keep them openned you will need to create a simple router for DB notifications
4. As you already found out QSslConfiguration is used, I'd like to expose this setting just like uWSGI does, https://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html but need to check how to find out what is HIGH.
5. Well if you don't enable HTTP/2 upgrade that will be the default for --http-socket or --h1

**Comment by dantti** [comment]
For NOTIFY on Application::postFork() after you QSqlDatabase is successfuly openned:

        QSqlDriver *driver = db.driver();
        if (!driver->subscribeToNotification(QStringLiteral("name_of_notification"))) {
            qCWarning(CUTEAPP) << "FAILED to subscribe to notification" << driver->lastError().text();
            return false;
        }
    
        connect(driver, static_cast<void(QSqlDriver::*)(const QString &, QSqlDriver::NotificationSource, const QVariant &)>(&QSqlDriver::notification), this,
                [=] (const QString &name, QSqlDriver::NotificationSource source, const QVariant &payload) {
            qDebug(CUTEAPP) << "DB notification:" << name << source << payload;
            if (name == QLatin1String("name_of_notification")) {
                m_apiV1->sendCommand(payload.toString());
            }
        });

Where m_apiV1 is a pointer to a REST API Controller my application has, this forces the controller to invalidate DB data cache so a subsequent request will have an up to date version, of course this is up to you on how will you use this feature...

**Comment by mike23456** [comment]
Thanks for the reply, much appreciated.
Current deployment:  1 process, and ideal number of threads (8) consequently 8 database connections.
WOW that means 8 notify commands will be sent to all clients at once! what a mess!

Everything you explained is clear except:
m_apiV1->sendCommand(payload.toString());

Can you show an example of how to implement "sendCommand" function in order to send a websocket message to all connected clients? cuz that confuses me the most!

I might consider "creating a simple router for DB notifications" in the future but for now all i really want is to send text notifications to all clients at once just to tell them the data has changed so that clients can request the new data through http REST api.

Therefore, for the time being, i will run a separate Cutelyst process with 1 thread  just for handling websockets and notifications..

Yes item 1 is a complex subject, just forget about it for now.

**Comment by dantti** [comment]
So m_apiV1 is a pointer to a Cutelyst::Controller subclass, sendCommand is a simple method that takes a QString, there you can have something like:

    void ApiV1::sendCommand(const QString &data)
    {
        Q_EMIT broadcast(data);
    }

Then after the webSocketHandshake() method was done you do:

   connect(this, &ApiV1::broadcast, c, &Response::webSocketTextMessage);

**Comment by mike23456** [comment]
Thanks for the help! it worked. I tried it 2 days ago. Its very obvious that m_apiV1 is a pointer to a Cutelyst::Controller subclass. What i needed was the Q_EMIT code and the QObject::connect which you showed in the example above. 

I figured out a solution for sending responses to individual clients but not sure if its a good one:

After the handshake, im saving a pointer to the "c->response" object as well as the "PostgreSQL Channel" the client asks to connect to in a QMap as keys:

` QMap<QPair<Response*,QString>,QPair<QString,quint16>> responseMap;
  
responseMap.insert(QPair<Response*, QString>(c->response(),"example_channel_name"), QPair<QString, quint16>(req->addressString(),req->port()));

`
Another QPair is saved as the value of the QMap and contains the address and the port of the connected websockets client. 

I can iterate over them as follows and send a websocket message only if a channel matches the notification channel. 

```
    for (auto &i : responseMap.keys())
    {
        if (i.second == "notification_channel1")
        {
            i.first->webSocketTextMessage("hi");            
        }
    }
```
 
Furthermore, the address and port of each client are saved in the QMap so i can identify each user as well as find out the total number of connected users per server.

The only problem is that i have to delete the response pointer from the QMap once the connection closes otherwise it will crash. Furthermore must check if the raw pointer is valid before accessing it.

Please let me know your opinion regarding this solution.

**Comment by dantti** [comment]
wow, sorry for the delay... forgot to reply

One important thing about being notified when the client disconnects is to rely on Context::destroyed signal, and that's because, if you explicit close the client connection the webSocketClosed is not emitted and unless you do a cleanup on every wsClose() call you will leak .

Well on my benchmarks I never see QMap being faster than QHash, which is why I usually use QHash, not sure about limits, but you have a 65355 port limit anyway so it's likely you run out of ports before QHash/QMap limits (which size() is a regular int).

**Comment by dantti** [comment]
closing this, feel free to open a new issue or ask questions on the mailing list.
