### ISSUE TITLE
Need help with starting HTTP/2 server

### ISSUE THREAD

**Issue by brano543** [cutelyst/cutelyst#181]
Hi guys,

I am new to Cutelyst and after having tough time to compile it on RHEL (had to compile QT5 Base from source as packages are archaic) I am unable to start CWSGI::WSGI server to listen for HTTP/2, because every time I do it just refuses to send reply. (curl: (52) Empty reply from server), for standard HTTP it works fine and sends HTTP/1.1 response. This is the code of my main program. What am I doing wrong?

```
CWSGI::WSGI *wsgi = new CWSGI::WSGI();
  Cutelyst::Application *myapp = new Hello();
  QCoreApplication app(argc, argv);
  wsgi->setThreads("auto");
  wsgi->setProcesses("1");
  wsgi->setBufferSize(16393);
  // wsgi->setUpgradeH2c(true); -> tried also turning this on and off
  wsgi->setHttp2Socket({QStringLiteral("0.0.0.0:80")});
  wsgi->setSoKeepalive(true);
  wsgi->setReusePort(true);
  wsgi->setMaster(true);
  wsgi->exec(myapp);
```

**Comment by dantti** [comment]
well I don't see anything wrong in there, are you sure your curl has H2 support and is using it?

**Comment by dantti** [comment]
For wsgi->setUpgradeH2c(true); you must open a HTTP/1.1 socket that will upgrade to H2

**Comment by brano543** [comment]
it doesn't even work from browser if I open HTTP2 socket like this.
`wsgi->setHttp2Socket({QStringLiteral("0.0.0.0:80")});`
Output of application
```
Installing EPoll event loop
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:80 fd 9
spawned WSGI master process (pid: 18474)
spawned WSGI worker (and the only) (pid: 18475, cores: 1)
18475:18475 default[debug] HelloWorld::postFork 18475
```
sudo lsof -i -P -n | grep LISTEN
`test    18475    root   13u  IPv4  74493      0t0  TCP *:80 (LISTEN)`
My Root.cpp
```
#include <application/root.h>
#include <unistd.h>

using namespace Cutelyst;

Root::Root(QObject *parent) : Controller(parent)
{
}

Root::~Root()
{
}

void Root::index(Context *c)
{
    c->response()->setContentType("text/plain");
    c->response()->setBody(QByteArrayLiteral("Welcome to Cutelyst lol!"));
    c->response()->setStatus(200);
}

void Root::defaultPage(Context *c)
{
    c->response()->body() = "Page not found!";
    c->response()->setStatus(404);
}
```
Hello.cpp
```
#include <QDebug>
#include <QCoreApplication>

#include <application/hello.h>
#include <application/root.h>
#include <Cutelyst/Plugins/StaticSimple/staticsimple.h>
#include <Cutelyst/Plugins/View/Grantlee/grantleeview.h>

using namespace Cutelyst;

Hello::Hello(QObject *parent) : Application(parent)
{
}

Hello::~Hello()
{
}

bool Hello::init()
{
    new Root(this);

    // new StaticSimple(this);

    // new GrantleeView(this);

    return true;
}

bool Hello::postFork()
{
    qDebug() << "HelloWorld::postFork" << QCoreApplication::applicationPid();

    return true;
}
```

**Comment by dantti** [comment]
No, it will _never_ work on Browsers like that.
No Browser support HTTP2 without SSL.

**Comment by brano543** [comment]
Thanks for the explanation, I will try to use certificate and key and retry. However one question came upon my mind. If I would start Cutelyst server without SSL and put Nginx in front of that to handle the SSL, would I loose the benefit of HTTP/2 at all or Nginx knows how to send "correct headers"?

I will try to build curl locally within virtual machine as I am getting unsupported protocol error
```
curl --http2-prior-knowledge -I 192.168.200.11:80
curl: (1) Unsupported protocol
```
`curl -sI 192.168.200.11

`
returns blank response like no headers anything at all. Curl version is 7.55.1.

**Comment by dantti** [comment]
AFAIK Nginx still doesn't talk HTTP/2 with backends, so you need to either use HTTP/1.1 or FastCGI.
And TBH there isn't a _big_ benefit of using H2, specially for short-lived requests their overhead is likely to possibly be bigger.

**Comment by brano543** [comment]
I am still struggling to use the HTTP/2. I enabled SSL,but it is still sending HTTP/1.1 from within browser (moreover asking me to select certificate as prompt in browser don't know why, never had this problem before) and there is an unsupported protocol error when trying it with curl. The code is quite complex to go fully through, so how does it actually work internally? I got somehow confused also about threads and processes. The postFork method is basically called even when I have 1 process and N threads,so in that case there is a thread pool or does it actually always create a new thread?
```
CWSGI::WSGI *wsgi = new CWSGI::WSGI();
 Cutelyst::Application *myapp = new Hello();
 QCoreApplication app(argc, argv);

 wsgi->setThreads("1");
 wsgi->setProcesses("1");
 wsgi->setHttpsSocket({{QStringLiteral("0.0.0.0:443,/etc/ssl/certs/certificate.crt,/etc/ssl/private/server.key")}});
 wsgi->setHttpsH2(true);
 wsgi->setUpgradeH2c(true);

 wsgi->setBufferSize(16393);
  // wsgi->setHttp2Socket({QStringLiteral("0.0.0.0:443,/etc/ssl/certs/certificate.crt,/etc/ssl/private/server.key")}); tried also this in combination and didn't work
 wsgi->setSoKeepalive(true);
 wsgi->setReusePort(true);

 wsgi->setMaster(true);
 wsgi->exec(myapp);
```

**Comment by dantti** [comment]
Well for that you need to add an exception on you browser or get a certificate signed by a valid authority

**Comment by dantti** [comment]
For the threads question, yes 5 threads are created immediately.
The postFork() method is called even if you have threads but not forks, the idea is to mimic the behavior since it creates a new instance of your application for each thread.

**Comment by brano543** [comment]
> Well for that you need to add an exception on you browser or get a certificate signed by a valid authority
I have a valid certificate signed by our company. The thing is this won't be in the default trusted store by Firefox etc. I am not so familiar with these TLS things, but when I was using H2o library, I initialized SSL with these calls
```
SSL_CTX_use_certificate_chain_file
SSL_CTX_use_PrivateKey_file
```
and it was basically working, I never had to confirm any pop-up from client. The browser even says the certificate is valid even when I press X (close button), not even selecting any certificate, and loads the page successfully, so it seems that default TLS handling in Cutelyst is not taking the whole certificate chain from the file provided. Yes, my certificate contains the whole chain. I had similar problem in another project written in Node.js and there I used a library which added the certificate authority to trusted store and then it worked. So I am still confused what needs to be done for Cutelyst to stop forcing client to provide their certificate, because it works even if they don't, just the pop-up is annoying.

> For the threads question, yes 5 threads are created immediately.
> The postFork() method is called even if you have threads but not forks, the idea is to mimic the behavior since it creates a new instance of your application for each thread.
I am not quite sure I understand, so here is my understanding and correct me please if I am wrong. Initially we have N (lets say 5 in this example) threads. Each thread is basically running an event loop and listening for requests. All threads basically use accept() call on one socket we actually created and SO_REUSEADDR flag tells kernel to manage it for us efficiently to load-balance that. I understand that the postFork is basically a place where I can open up a connection to DB and it will stay open as long as the thread is alive (which never dies unless SIGINT is received which basically stops all threads). Now the question is about your engine itself from the part request is actually being received. Does it mean that on each request you:
1) fork new process to handle it
2.1) have choice to immediately process the request, eg. begin sending file OR
2.2) call detachAsync() function (which spawns new process or thread?) and immediately return thus not blocking the event-loop by longer running processing and then after this finishes setting the request body as in https://github.com/cutelyst/cutelyst/blob/master/examples/hello-world/root.cpp which basically means sending the response from the same thread which originally received the request and terminate this new thread by calling attachAsync() which basically (joins the thread with calling thread/terminates child process?) 

You know, because in C++ there is always the struggle with having threads in long running process, that it is prone to memory fragmentation and it can only be avoided by carefully using block allocators everywhere which is really complicated. Spawning a process for long-running request is actually win here that the memory gets freed, so this is why I am asking to understand the concept.

**Comment by dantti** [comment]
Well SSL isn't my thing too, I mostly wrote the SSL part to mimic uWSGI:
https://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html
But I myself use Nginx because I need virtual hosts...

Yes, postFork is the safe place to open DB connections, it's the function that is guaranteed to be run after the thread started of after the fork was done.

If you set to have 5 process the it will fork 5 times, every thread has it's own event loop that is independent to avoid mutexes, which yes, each will call accept which is why REUSEPORT is important.

DetachAsync allows to return to the engine without it replying to the client and deleting the Context object, the engine then can process other requests and deal with that other at a later time.

I don't know much about this memory fragmentation issue that you say but benchmarks show if you spawn a bunch of process performance is pretty much the same, so usually it is better as you can crash a worker with less impact but it uses more RAM.

**Comment by brano543** [comment]
> Well SSL isn't my thing too, I mostly wrote the SSL part to mimic uWSGI:
> https://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html
> But I myself use Nginx because I need virtual hosts...

I was able to fix the above mentioned issue by #183 . I would also like to kindly ask you to put it as release 2.7.1 as that pop-up was kind of annoying :)

> Yes, postFork is the safe place to open DB connections, it's the function that is guaranteed to be run after the thread started of after the fork was done.
> 
> If you set to have 5 process the it will fork 5 times, every thread has it's own event loop that is independent to avoid mutexes, which yes, each will call accept which is why REUSEPORT is important.

Thanks for the explanation. If I understand correctly then setProcesses controls how many processes to deploy and setThreads controls how many event loop threads to run within each process. Yes in the case of multiple threads listening to same address , it is SO_REUSEPORT and not SO_REUSEADDR which does this for multiple processes, my bad. For processes I believe you handled this by using setMaster which basically listens to all incoming connections and notifies other processes since I don't see anywhere the usage of SO_REUSEADDR. I actually like the way you designed the framework, because postFork method and basically the whole application one writes is initialized nProcess * nThread times.

> DetachAsync allows to return to the engine without it replying to the client and deleting the Context object, the engine then can process other requests and deal with that other at a later time.
> 
> I don't know much about this memory fragmentation issue that you say but benchmarks show if you spawn a bunch of process performance is pretty much the same, so usually it is better as you can crash a worker with less impact but it uses more RAM.

I am not so sure I fully understand the whole picture here. Let's take a whole example. If my understanding above is correct, then let's have 1 master process, 1 application process and 8 threads. Master process listens to requests and forwards them to all child processes, in this case it forwards all requests to one child process. This child process have 8 event loop threads meaning that it should be able to process 8 requests "at once" meaning that if there are 9 requests one of them will be waiting in queue. 

Now without DetachAsync() function we would block this thread until it finishes it's job completely without giving chance of another request to come which might actually start sending the parts of response faster before the more heavy-weight task. In theory we can process 1.5 direct reply scenarios requests by the time the longer blocking request finishes. 

What actually happens when we call DetachAsync()? When I hear the word detached, I would probably say that it would run a separate thread in detached(background mode) and joins with the calling thread when attachAsync() is called. However it can also mean that it will fork another process and wait for the child to finish the same way. Could you please explain this?

Well, I am always having the problems with multi-threaded servers in the terms of memory consumption everytime when I deal with non-POD types like string or vector<string>. What happens to me that initial data that I get for SQL query it's let say 10 MB if I would save it to file directly. However If I decide to store the same data in vector<string> and I tried like everything, pre-allocating it using reserve for both vector and each string, my memory consumption jumped to like 10-times to 100 MB. Since whole of this scenario happened inside thread, there is no way for OS to actually reclaim this memory, so the whole process was increasing its RAM usage over time. For each of these 100 MB requests the total memory the application ever needed was nThreads * 100 MB. If any of requests would temporary store 20 MB of actual data in vector it would be 200 MB * nThreads. IF the detachASync would spawn process instead of thread I think it would solve this. If it doesn't, can you please help me to understand what am I doing wrong and why I have these problems? I have spend many hours on that topic and every time I stumbled upon custom memory allocators which would allocate the memory in big chunks, because the culprit seems to be std::string internally uses new which internally uses malloc.

**Comment by brano543** [comment]
UPDATE
I checked the code and I see that it doesn't spawn anything, so I will implement this as I desire. My question then seems to be related to #184 on how would I check from this thread/process if the client has closed the connection. Would you be able to provide an example on the usage?

**Comment by dantti** [comment]
Master process don't forward requests to clients it just open the port but unregister from notifications of new connections. It's only purpose is to fork crashed workers.

About the memory usage I don't have such issue, also since QString is much nicer than std::string I don't use it, but if you store your data in string you need to know if it's not using 2 bytes utf-16..

DetachAsync() does not spawn a new thread/process it only tell the engine to not send the headers and body, and also break the processing chain

**Comment by dantti** [comment]
can I close this issue?

**Comment by brano543** [comment]
Yes, thank you for explanation :)
