### ISSUE TITLE
Error during components creation

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#186]
Hello! I have the following error during initialization (but I don't use any plugins):
`[Fatal] <Cutelyst::ControllerPrivate::instantiateClass>:558 Could not create component 'Cutelyst::REST*', you can register it with qRegisterMetaType<Cutelyst::REST*>(); or set a proper CUTELYST_PLUGINS_DIR`

Where should I put `qRegisterMetaType<Cutelyst::REST*>();`  ?

**Comment by arietto** [comment]
I am sorry. I've set CUTELYST_PLUGINS_DIR environment variable. The problem was solved.
But it will be better if `"or set a proper CUTELYST_PLUGINS_DIR"` is transformed into `"or set a proper CUTELYST_PLUGINS_DIR environment variable"`, because it's not evident for newcomers.

**Comment by dantti** [comment]
But it's not only an environment variable, it's also a build system variable.
