### ISSUE TITLE
static file with static simple

### ISSUE THREAD

**Issue by MiladR76** [cutelyst/cutelyst#193]
hi.
I am working with qt5.12.1 and i am new in qt. 
I wrote a server client app with qt and cutelyst . now i need static file . 
i have images in /root/static/ImageFiles and i want show this images with static file.
how can i do it?? i read documents and some questions about static file but i dont understand it.
please explain me step by step how can i do it??
how config static file in cutelyst???

thanks

**Comment by dantti** [comment]
It's recommended to use static-map or static-map2, or in case you have a frond-end server use it.
https://uwsgi-docs.readthedocs.io/en/latest/StaticFiles.html?highlight=static-map#mode-3-using-static-file-mount-points
