### ISSUE TITLE
Autorestart after crash

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#194]
Hello. Let's assume that cutelyst-wsgi2 has to load buggy user application (*.so).
I don't want to use Apache and so on for local network REST service. 
It it possible to make cutelyst-wsgi2 autorestart in case of crash?

**Comment by dantti** [comment]
Sure, just use the master mode

**Comment by arietto** [comment]
OK, can cutelyst-wsgi2 be used as Linux daemon?
I also met the following snippet in wsgi.cpp

     #ifdef Q_OS_LINUX
         systemdNotify::install_systemd_notifier(this);
     #endif
What does it do? Is this call mandatory in Linux?

**Comment by dantti** [comment]
It can be used but if you don't use systemd you need to send it to background manually (with & for example).

As the name sayss it install the systemd notifier, if it was started by systemd, if it was started each child cutelyst-wsgi process will notify systemd when it is ready, so the service enters in started state.

**Comment by arietto** [comment]
OK, thank you.
