### ISSUE TITLE
Automatically reconnect connection to the database PostgreSQL

### ISSUE THREAD

**Issue by sanekt197** [cutelyst/cutelyst#195]
How can I automatically reconnect to the database PostgreSQL if the connection is lost or disconnected?
So you have to restart the site service, which is not good

**Comment by dantti** [comment]
I would recommend restarting the process yes, unless you make no use of prepared queries.

If you don't restart prepared queries are likely to be stalled or if they failed to prepare due the connection not available and you are using CPreparedQueries they won't be re-prepared as they are static variables.

Usually restarting the process takes less than a second so it's no big deal.

**Comment by sanekt197** [comment]
how to do it right? How to know the process fell off the connection? It would be nice with the least empty overhead resources)

**Comment by dantti** [comment]
QSqlDatabase doesn't emit a closed signal, I even opened a bug report but it's a complex issue, IMHO the best is to have an Auto method that keeps checking if the connection is open.

I have plans to implement the PostgreSQL protocol on an async driver, sort of a QtSqlAsync module which would be easier to detect the closed socket but I don't have the time to do that yet.

**Comment by sanekt197** [comment]
Yes, things are sad. It is a pity of course that the regular driver QSqlDatabase here is useless: (
We'll have to re-invent something
But if something in this case will be new - please inform

And in the desktop applications, using whatever methods you try to solve this problem ...
It would be convenient if a regular driver QSqlDatabase  could easily catch broken connections.


At the expense of plans for your driver - it would be nice :)

It is a pity that I am not yet such a guru to help with this

**Comment by dantti** [comment]
Once I do that I'll surely post on my blog, but it's not a new driver for QSqlDatabase but a new Sql set of classes to do SQL in async mode, so that it can also perform better using PostgreSQL query pipelining.

**Comment by mike23456** [comment]
@dantti : did you find a better solution to this problem? My team is developing ERP software using Cutelyst and loosing db connection is not acceptable.  I am aware of the existence of  Cutelyst/ASQL but we do not have the time to learn a new library and migrate from QtSql to ASql at the moment so any solution for QtSql?

**Comment by dantti** [comment]
The best option is to have an Auto() method that makes sure the connection is alive before using, but I highly recommend using ASql because it's async and this plays a huge role on bigger systems, and really only you read the README you probably already know how to use it... very easy...

**Comment by sanekt197** [comment]
Yes, ASql is what need, it's worth using it )

**Comment by mike23456** [comment]
@dantti : Thanks for the quick reply.  Just 2 more questions:


1. We currently have a wrapper class for QSqlQuery called MSqlQuery so all we have to do is edit one class (the wrapper class) and all Controllers will use ASql. However, I dont want to migrate immediately as this requires more testing so  I believe we can use both QtSql & ASql together.

Like we could use ASql only for 1 task (for the time being) which is to detect when the db connection is cut and then we manually inform QtSql to reconnect. I believe this logic should go in the postFork() method, **is that correct**? Please provide some clarifications on that cuz we are not good with concurrency... and as you know Cutelyst will initiate a database connection per thread.

2. Also, ASql doesnt seem to have a bindvalue method?  We dont want to rewrite each and every controller code as we  have more than 100 REST classes distributed over several projects in a microservices architecture. 

For example, doing this doesn't help:
db.exec(u"INSERT INTO temp4 VALUE ($1, $2, $3, $4, $5, $6, $7) RETURNING id",
{
     true,
     QStringLiteral("foo"),
     qint64(1234),
     QDateTime::currentDateTime(),
     123456.78,
     QUuid::createUuid(),
     QJsonObject{
          {"foo", true}
     }
}

Appreciate any answers,
Best Regards,

**Comment by dantti** [comment]
1. I don't believe what you want to do is going to work, the QtSql connection will be different from the ASql one, one might drop but not the other, postFork() is run after a thread or a new process is created, so it's the right place to create the connection you can have a timer there, or listen to ASql statusChanged -> closed, but that might not always work, maybe you could grab the connection FD from QtSql and give it to ASql (no API for this here but maybe it's possible to add as a use at your own risk). Also note that if you use prepared queries you must re-prepare them again if you reconnect, ASql connection does this automatically.
2. QtSql rewrites your query replacing all bound values with a string representation, then it sends the query as text, that works but has it's issues, I didn't want to risk a bogus rewrite so ASql rely on PG driver capabilities which is binding values to $1, 2, 3... it works the same way but the query is left intact (easier to see on the logs) and the arguments are send in binary form so it's more efficient, that Uuid and the double for example are sent in it's binary form not as text.

I know rewriting is a pain, I still have services running QtSql but I'm slowly migrating to ASql on important routes

**Comment by mike23456** [comment]
Clear!

1. ya, its right, in rare cases one might drop but the other doesn't and BTW  i already tried adding a timer yesterday but commented it out cuz i couldn't get QtSql to notify the service when the database connection is lost...
However, failure in rare cases is better than failure in all cases.

2. ya... those syntax errors QtSql returns they mean 3 different things.. XD. We were planning to make a logs service that shows the actual PostgreSQL logs to overcome this issue cuz when new backend developers see those errors for the first time, they freak out!

This reply is about to get off topic so ill open another issue in ASql.
