### ISSUE TITLE
Retrieving relevant IP address

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#196]
Hello! Let's assume that REST server has the following socket setting:
:3000.
For example, the node has two available IP addresses. The task is to find out relevant IP address on the server side, TO which the current REST client has emitted its request. cutelyst-wsgi2 is used without Apache.

**Comment by sibbi77** [comment]
Did you try Request::uri() or Request::base()? Both use EngineRequest::serverAddress documentation: "The server address which the server is listening to, usually the 'Host' header but if that's not present should be filled with the server address"

**Comment by arietto** [comment]
OK, thanks.
