### ISSUE TITLE
Freezes in debug mode under Windows

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#197]
Hello. I've noticed that debug version of cutelyst-wsgi2  (built with Visual Studio 2017) often refuses to load *.dll file (with REST controller business logic). After a few cutelyst-wsgi2 restarts it is possible to load my dll file. What's the possible reason of such freezes?

**Comment by dantti** [comment]
No idea, sorry, I have never had such problems on Linux. Nor on mingw builds of it on Windows

**Comment by arietto** [comment]
OK, JFYI:
Quick primary analysis shows that the freeze occurs when 
    `d->listenTcpSockets();` is called in 
`int WSGI::exec(Cutelyst::Application *app)`. The experiment was made for the following setting: 
http-socket=:5555.
So, I suppose that freeze is somewhere in 
`bool WSGIPrivate::listenTcp(const QString &line, Protocol *protocol, bool secure)`
//...
`ret = server->listen(line, protocol, secure); // <= Perhaps, freeze is here.`
I can't catch the exact place in the low-level code at the moment, because freeze occurs not very often.

**Comment by arietto** [comment]
More details: Freeze occurs in `QTcpServer::listen()`, when we ommit IP part in http-socket (debug build).
In good case we have 2 seconds delay in debug mode, but sometimes it can last much longer.
As a workaround, I will assign exact IP for debug.

**Comment by dantti** [comment]
Odd, this I suppose is Windows issue to listen on all interfaces, maybe a firewall analyzing which process is trying to listen on all interfaces. And since this reaches QTcpServer perhaps there is some known or reported bug.

**Comment by dantti** [comment]
Closing this as it's likely to be related to some Windows firewall or be at Qt QTcpServer
