### ISSUE TITLE
Setting custom headers in postprocess stage

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#198]
Hello! I'd like to assign custom headers in postprocess stage for all controllers. Is `End()` method linked with `RenderView` is the only typical way? If I have an empty body, I've got 500 error at `RenderView` stage (thus should I force 204 code in `End()` if I met 20x and empty body?). I suppose that if I use only JSON, then loading `RenderView` plugin is redundant.
 I just wanna postprocess ALL requests in one place without `RenderView` dependency.

**Comment by dantti** [comment]
if you use RenderView and doesn't use JsonView then indeed there's no use for it.
IIRC the End() method in a Root Controller will be the last one to be called, another option is to connect to C::Application::afterDispatch()

**Comment by arietto** [comment]
OK, thank you.
