### ISSUE TITLE
Send Status Code after POST

### ISSUE THREAD

**Issue by sayezz** [cutelyst/cutelyst#200]
Hey guys,

My client sends data via POST to my Server. 
My Server receives the data. This works all fine.

Now I would like to respond with a status code. Right now my server always responses with 405.
How can I response with "Cutelyst::Response::OK" ?

My header method defintion looks like this:
```
C_ATTR(ts_POST, :Path : AutoArgs : ActionClass(REST))
void ts_POST(Context *c);
```

My Source method:
```
void Post::ts_POST(Context *c)
{
     //... here is all the code to receives the data. this works
    
     // this is what I do right now, but nothing happens. still 405
     c->response()->setStatus(Cutelyst::Response::OK);
}
```

Thanks

**Comment by dantti** [comment]
All you did is fine, don't you have a frontend server messing with this? Or a later method that is called in the chain that might be setting another value?

**Comment by sayezz** [comment]
Thanks for the quick reply.

No, I have nothing else running. When I close my server and try to send the POST data with my client nothing happens and I don't get any response. So it must be definitly my server.

I used mostly the "Hello World" example. I added the full source code:
main.cpp
server.cpp and .h
post.cpp and .h

Both applications are small QT projects so I don't use any browser or somthing else.

[RestServer.zip](https://github.com/cutelyst/cutelyst/files/3187177/RestServer.zip)

**Comment by sayezz** [comment]
![cute](https://user-images.githubusercontent.com/30605911/57856525-90b13d80-77ed-11e9-8e9d-fcd6e423fb19.PNG)

I don't know if this helps, but here is a screenshot how my server output looks like afte I started the server and received some data from my client

**Comment by dantti** [comment]
All looks fine, are you using HTTP2?

**Comment by dantti** [comment]
And please enable the debuggin log with this environment variable 

> QT_LOGGING_RULES=*=true

 or something depending on you OS

**Comment by sayezz** [comment]
I don't know if I'm using HTTP2. I'm starting my server on
`localhost:1234`
My client calls
`http://localhost:1234/post`

I will check if I'm using HTTP2 and enable QT_LOGGING_RULES and come back.
Thanks for your help.

**Comment by sayezz** [comment]
Do I have to define somewhere that http://localhost:1234/post in mycase is a POST method.
The name is propably misleading. My endpoint definition ist /post and also I try to send a POST. Maybe something with my endpoint deifnition is worng. Maybe I need to set the http method for this endpoint to POST.

**Comment by dantti** [comment]
Oh yes, that's probably the problem, you are using ActionRest the wrong way.
With ActionRest you need at least two methods a something() and a something_POST(),
something() is always called, then the corresponding _HTTP_METHOD:

see: https://api.cutelyst.org/classCutelyst_1_1ActionREST.html

**Comment by sayezz** [comment]
Thanks! Great! It works now. Two more question:
1. What is ActioRest, I don't understand it. (When) Do I need it? Could you elaborate on it in 2 - 3 sentence? 
2. Can I upload my Client/Server example to your git or can I provide my example to you so you can upload it? Right now there is only a HelloWorld Example which is not bad and helps a lot but I think a complete Client/Server example could also be helpful for some people.

You can close this Issue.
Thanks again for the fast response. Great work, keep it up!

**Comment by dantti** [comment]
1. ActionRest is a helper class that automatically implements OPTIONS method, and will dispatch to the proper something_HTTP_METHOD, you can do REST without it if you like.
2. You can do a PR if you like, but here we don't use qmake, so please adjust to the rest of the code style.
