### ISSUE TITLE
how to change the default host?

### ISSUE THREAD

**Issue by xvlinihao** [cutelyst/cutelyst#205]
hello dantti, thanks for your work. I am a newbie to cutelyst and web framework, and I can find how to change the host from localhost to a specific hostname,  could you plz tell me how to do to it? Many thanks

**Comment by xvlinihao** [comment]
moreover, could you please tell me how to open the server through qt creator?

**Comment by dantti** [comment]
Not sure I understood the question, but --http-socket hostname:port 

open the cmake file in QtCreato

**Comment by xvlinihao** [comment]
> Not sure I understood the question, but --http-socket hostname:port
> 
> open the cmake file in QtCreato

thank you very much
