### ISSUE TITLE
Unable to load Grantlee template in tutorial

### ISSUE THREAD

**Issue by oberluz** [cutelyst/cutelyst#208]
HI,

I installed cutelyst 7977825a8a842d7bf0d5789357b5624d70117ab2 and built it with GrantLee 5.0.0.

I followed the Tutorial_02_CutelystBasics but when I get to https://github.com/cutelyst/cutelyst/wiki/Tutorial_02_CutelystBasics#hello-world-using-a-view-and-a-template it fails to find the hello.html template:

> cutelyst-tutorial/Hello/build$ cutelyst2 -r --server --app-file $PWD/src/libHello.so -- --chdir .. --chdir2 ..
Installing EPoll event loop
11979:11979 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 9
Changing directory to: ..
spawned WSGI master process (pid: 11979)
spawned WSGI worker (and the only) (pid: 11980, cores: 1)
Loading application: /home/naderp/Development/software/cutelyst-tutorial/Hello/build/src/libHello.so
11980:11980 cutelyst.core[debug] Loaded translations for QLocale(English, Latin, United States) from "/usr/local/share/cutelyst2/translations/cutelystcore.en.qm"
11980:11980 cutelyst.core[debug] Loaded translations for QLocale(English, Latin, United States) from "/usr/local/share/cutelyst2/translations/plugin_view_grantlee.en.qm"
Changing directory2 to: /home/naderp/Development/software/cutelyst-tutorial/Hello
11980:11980 cutelyst.core[debug] Loaded Request Data Handlers:
.-----------------------------------.
| application/x-www-form-urlencoded |
| application/json                  |
| multipart/form-data               |
.-----------------------------------.
11980:11980 cutelyst.core[debug] Loaded dispatcher "Cutelyst::Dispatcher"
11980:11980 cutelyst.core[debug] Using engine "CWSGI::CWsgiEngine"
11980:11980 cutelyst.core[debug] Found home "/home/naderp/Development/software/cutelyst-tutorial/Hello"
11980:11980 cutelyst.core[debug] Loaded components:
.---------------------------------+------------.
| Class                           | Type       |
.---------------------------------+------------.
| Root                            | Controller |
| Cutelyst::GrantleeView->execute | View       |
.---------------------------------+------------.
11980:11980 cutelyst.dispatcher[debug] Loaded Private actions:
.-------------------+-------+-------------.
| Private           | Class | Method      |
.-------------------+-------+-------------.
| /root/defaultPage | Root  | defaultPage |
| /root/End         | Root  | End         |
| /root/hello       | Root  | hello       |
| /root/index       | Root  | index       |
.-------------------+-------+-------------.
11980:11980 cutelyst.dispatcher[debug] Loaded Path actions:
.------------+-------------------.
| Path       | Private           |
.------------+-------------------.
| /hello/... | /root/hello       |
| /root/...  | /root/defaultPage |
| /root      | /root/index       |
.------------+-------------------.
11980:11980 cutelyst.dispatcher[debug] 
11980:11980 cutelyst.core[info] cutelyst powered by Cutelyst 2.8.0, Qt 5.12.3.
11980:11980 cutelyst.core[debug] Default Application::postFork called on pid: 11980
11980:11980 cutelyst.request[debug] "GET" request for "hello" from "127.0.0.1"
11980:11980 cutelyst.dispatcher[debug] Path is "hello"
11980:11980 cutelyst.grantlee[debug] Rendering template "hello.html"
11980:11980 cutelyst.core[critical] "Error while rendering template: Template not found, hello.html"
11980:11980 cutelyst.view[critical] "Error while rendering template: Template not found, hello.html"
11980:11980 cutelyst.stats[debug] Response Code: 200; Content-Type: text/html; charset=utf-8; Content-Length: 0
11980:11980 cutelyst.stats[info] Request took: 0.000368s (2720.888/s)
.---------------------------------+-----------.
| Action                          | Time      |
.---------------------------------+-----------.
| /root/hello                     | 0.000026s |
| /root/End                       | 0.000168s |
| Cutelyst::GrantleeView->execute | 0.000143s |
.---------------------------------+-----------.

The browser says:

> Error while rendering template: Template not found, hello.html

I've tried moving hello.html around and restarting the server but haven't been able to get it to load.

Any ideas?

Thanks,
Paul

**Comment by dantti** [comment]
Your issue is probably because you are going two levels up with chdir and chdir2

**Comment by oberluz** [comment]
Hi,

I ran it with both these and still not able to load the template:

cutelyst2 -r --server --app-file $PWD/src/libHello.so -- --chdir2 ..
cutelyst2 -r --server --app-file $PWD/src/libHello.so -- --chdir ..

> cutelyst-tutorial/Hello/build$ cutelyst2 -r --server --app-file $PWD/src/libHello.so -- --chdir ..
Installing EPoll event loop
13010:13010 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 9
Changing directory to: ..
spawned WSGI master process (pid: 13010)
spawned WSGI worker (and the only) (pid: 13011, cores: 1)
Loading application: /home/naderp/Development/software/cutelyst-tutorial/Hello/build/src/libHello.so
13011:13011 cutelyst.core[debug] Loaded translations for QLocale(English, Latin, United States) from "/usr/local/share/cutelyst2/translations/cutelystcore.en.qm"
13011:13011 cutelyst.core[debug] Loaded translations for QLocale(English, Latin, United States) from "/usr/local/share/cutelyst2/translations/plugin_view_grantlee.en.qm"
Changing directory2 to: /home/naderp/Development/software/cutelyst-tutorial/Hello
13011:13011 cutelyst.core[debug] Loaded Request Data Handlers:
.-----------------------------------.
| application/x-www-form-urlencoded |
| application/json                  |
| multipart/form-data               |
.-----------------------------------.
13011:13011 cutelyst.core[debug] Loaded dispatcher "Cutelyst::Dispatcher"
13011:13011 cutelyst.core[debug] Using engine "CWSGI::CWsgiEngine"
13011:13011 cutelyst.core[debug] Found home "/home/naderp/Development/software/cutelyst-tutorial/Hello"
13011:13011 cutelyst.core[debug] Loaded components:
.---------------------------------+------------.
| Class                           | Type       |
.---------------------------------+------------.
| Root                            | Controller |
| Cutelyst::GrantleeView->execute | View       |
.---------------------------------+------------.
13011:13011 cutelyst.dispatcher[debug] Loaded Private actions:
.-------------------+-------+-------------.
| Private           | Class | Method      |
.-------------------+-------+-------------.
| /root/defaultPage | Root  | defaultPage |
| /root/End         | Root  | End         |
| /root/hello       | Root  | hello       |
| /root/index       | Root  | index       |
.-------------------+-------+-------------.
13011:13011 cutelyst.dispatcher[debug] Loaded Path actions:
.------------+-------------------.
| Path       | Private           |
.------------+-------------------.
| /hello/... | /root/hello       |
| /root/...  | /root/defaultPage |
| /root      | /root/index       |
.------------+-------------------.
13011:13011 cutelyst.dispatcher[debug] 
13011:13011 cutelyst.core[info] cutelyst powered by Cutelyst 2.8.0, Qt 5.12.3.
13011:13011 cutelyst.core[debug] Default Application::postFork called on pid: 13011
13011:13011 cutelyst.request[debug] "GET" request for "hello" from "127.0.0.1"
13011:13011 cutelyst.dispatcher[debug] Path is "hello"
13011:13011 cutelyst.grantlee[debug] Rendering template "hello.html"
13011:13011 cutelyst.core[critical] "Error while rendering template: Template not found, hello.html"
13011:13011 cutelyst.view[critical] "Error while rendering template: Template not found, hello.html"
13011:13011 cutelyst.stats[debug] Response Code: 200; Content-Type: text/html; charset=utf-8; Content-Length: 0
13011:13011 cutelyst.stats[info] Request took: 0.000305s (3283.565/s)
.---------------------------------+-----------.
| Action                          | Time      |
.---------------------------------+-----------.
| /root/hello                     | 0.000020s |
| /root/End                       | 0.000166s |
| Cutelyst::GrantleeView->execute | 0.000148s |
.---------------------------------+-----------.



Anyway to enable some tracing to see where it's looking for the template?

**Comment by oberluz** [comment]
some more info: seems launching cutelyst2 creates two processes, both of which are setting on the Hello directory:

> naderp@hector:\~/Development/software/cutelyst-tutorial/Hello/root$ !ps
ps -aef | grep cute
naderp   13094  4728  0 20:21 pts/2    00:00:00 cutelyst2 -r --server --app-file /home/naderp/Development/software/cutelyst-tutorial/Hello/build/src/libHello.so -- --chdir ..
naderp   13095 13094  0 20:21 pts/2    00:00:00 cutelyst2 -r --server --app-file /home/naderp/Development/software/cutelyst-tutorial/Hello/build/src/libHello.so -- --chdir ..
naderp   13129  6406  0 20:23 pts/6    00:00:00 grep --color=auto cute
naderp@hector:\~/Development/software/cutelyst-tutorial/Hello/root$ lsof -p 13094
COMMAND     PID   USER   FD      TYPE             DEVICE SIZE/OFF    NODE NAME
cutelyst2 13094 naderp  cwd       DIR                8,4     4096 6705487 /home/naderp/Development/software/cutelyst-tutorial/Hello
cutelyst2 13094 naderp  rtd       DIR               8,49     4096       2 /
cutelyst2 13094 naderp  txt       REG               8,49   109848  264488 /usr/local/bin/cutelyst2
cutelyst2 13094 naderp  mem       REG               8,49 10219008  270982 /usr/lib/locale/locale-archive
cutelyst2 13094 naderp  mem       REG               8,49   456632  528789 /lib/x86_64-linux-gnu/libpcre.so.3.13.2
cutelyst2 13094 naderp  mem       REG               8,49  1088952  528730 /lib/x86_64-linux-gnu/libm-2.23.so
cutelyst2 13094 naderp  mem       REG               8,49  1115136  524431 /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2
cutelyst2 13094 naderp  mem       REG               8,49     6160  262311 /usr/lib/x86_64-linux-gnu/libgthread-2.0.so.0.4800.2
cutelyst2 13094 naderp  mem       REG               8,49    14608  528684 /lib/x86_64-linux-gnu/libdl-2.23.so
cutelyst2 13094 naderp  mem       REG                8,4 25048256 5474957 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/lib/libicudata.so.56.1
cutelyst2 13094 naderp  mem       REG                8,4  2069136 5474964 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/lib/libicuuc.so.56.1
cutelyst2 13094 naderp  mem       REG                8,4  3368288 5474958 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/lib/libicui18n.so.56.1
cutelyst2 13094 naderp  mem       REG               8,49   104864  528851 /lib/x86_64-linux-gnu/libz.so.1.2.8
cutelyst2 13094 naderp  mem       REG               8,49   138696  528806 /lib/x86_64-linux-gnu/libpthread-2.23.so
cutelyst2 13094 naderp  mem       REG                8,4  2162768 5475121 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/lib/libQt5Network.so.5.12.3
cutelyst2 13094 naderp  mem       REG               8,49    96848  654291 /usr/local/lib/x86_64-linux-gnu/libCutelyst2Qt5EventLoopEpoll.so.2.8.0
cutelyst2 13094 naderp  mem       REG               8,49  1044432  654257 /usr/local/lib/x86_64-linux-gnu/libCutelyst2Qt5.so.2.8.0
cutelyst2 13094 naderp  mem       REG               8,49  1868984  528660 /lib/x86_64-linux-gnu/libc-2.23.so
cutelyst2 13094 naderp  mem       REG               8,49    96616  545469 /lib/x86_64-linux-gnu/libgcc_s.so.1
cutelyst2 13094 naderp  mem       REG               8,49  1607120  262079 /usr/lib/x86_64-linux-gnu/libstdc++.so.6.0.25
cutelyst2 13094 naderp  mem       REG                8,4  6597088 5475116 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/lib/libQt5Core.so.5.12.3
cutelyst2 13094 naderp  mem       REG               8,49   878320  654294 /usr/local/lib/x86_64-linux-gnu/libCutelyst2Qt5Wsgi.so.2.8.0
cutelyst2 13094 naderp  mem       REG               8,49   162632  528632 /lib/x86_64-linux-gnu/ld-2.23.so
cutelyst2 13094 naderp  mem       REG               8,49       23 2159861 /usr/local/share/cutelyst2/translations/cutelystcmd.en.qm
cutelyst2 13094 naderp  mem       REG                8,4       16 4331136 /home/naderp/Development/software/Qt5.12.3/5.12.3/gcc_64/translations/qt_en.qm
cutelyst2 13094 naderp    0u      CHR              136,2      0t0       5 /dev/pts/2
cutelyst2 13094 naderp    1u      CHR              136,2      0t0       5 /dev/pts/2
cutelyst2 13094 naderp    2u      CHR              136,2      0t0       5 /dev/pts/2
cutelyst2 13094 naderp    3r      CHR                1,9      0t0      11 /dev/urandom
cutelyst2 13094 naderp    4u  a_inode               0,13        0   12668 [eventfd]
cutelyst2 13094 naderp    5u  a_inode               0,13        0   12668 [eventpoll]
cutelyst2 13094 naderp    6u  a_inode               0,13        0   12668 [eventfd]
cutelyst2 13094 naderp    7u     unix 0x0000000000000000      0t0  179397 type=STREAM
cutelyst2 13094 naderp    8u     unix 0x0000000000000000      0t0  179398 type=STREAM
cutelyst2 13094 naderp    9u     IPv6             179399      0t0     TCP *:3000 (LISTEN)
cutelyst2 13094 naderp   10r  a_inode               0,13        0   12668 inotify
naderp@hector:~/Development/software/cutelyst-tutorial/Hello/root$

**Comment by oberluz** [comment]
I tried a number of other things none of which fixed the issue:

Uninstalled the grant lee packages (Ubuntu 16.04) and build latest from git.
Rebuilt cutelyst ensuring all plugins were built.

**Comment by dantti** [comment]
have you tried https://github.com/cutelyst/cutelyst-tutorial ?
Perhaps you forgot some step from the tutorial.

**Comment by oberluz** [comment]
Yes, that worked. There are some differences in the files. I'll compare them and let you know what broke.

Thanks!

**Comment by oberluz** [comment]
Yes, I made a mistake and instantiated  GrantleeView in the Hello constructor rather than the init method!

Sorry for the noise!
