### ISSUE TITLE
Missing StaticSimple plugin generated code

### ISSUE THREAD

**Issue by oberluz** [cutelyst/cutelyst#209]
Hi Daniel,

In the [Cutelyst Plugins](https://github.com/cutelyst/cutelyst/wiki/Tutorial_03_MoreCutelystBasics#cutelyst-plugins) section of the tutorial it states:

> Take a look at the file src/myapp.cpp that the helper created above. By default, Cutelyst enables one plugin:

(missing snippet?)

> Cutelyst::StaticSimple StaticSimple provides an easy way to serve static content, such as images and CSS files, from within your application, it's much better to use cutelyst (or uwsgi) --static-map or serve them with your front web server
.

Did not generate the plugin code:

> $ cutelyst2 --create-app MyApp
>  created MyApp
>  created MyApp/CMakeLists.txt
>  created MyApp/build
>  created MyApp/root
>  created MyApp/src
>  created MyApp/src/CMakeLists.txt
>  created MyApp/src/root.h
>  created MyApp/src/root.cpp
>  created MyApp/src/myapp.h
>  created MyApp/src/myapp.cpp
> Change to application directory, then build directory and Run "cmake .." to make sure your install is complete
> naderp@hector:~/Development/software/cutelyst-tutorial$ cat created MyApp/src/myapp.cpp
> cat: created: No such file or directory
> #include "myapp.h"
> 
> #include "root.h"
> 
> using namespace Cutelyst;
> 
> MyApp::MyApp(QObject *parent) : Application(parent)
> {
> }
> 
> MyApp::~MyApp()
> {
> }
> 
> bool MyApp::init()
> {
>     new Root(this);
> 
>     return true;
> }

Also it seems the tutorial is possibly missing a code snippet between the paragraphs?

**Comment by dantti** [comment]
There was no missing code, it's just that I disable it by default, and the I just updated the tutorial.

Thanks

**Comment by oberluz** [comment]
Thanks Daniel
