### ISSUE TITLE
RenderView and empty body with error.

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#211]
Hello! I need to set default content type (JSON) if if has not been set earlier in my controller.
So, I use the following posthandler:

    C_ATTR(End, :ActionClass("RenderView"))

    void End(Context *c);

But RenderView::doExecute(Cutelyst::Context *c) returns 500 error when I set empty body and 400 error in my method.  What should I do? In my case Application::afterDispatch handler is too global (it is also used for some headers), I need per controller posthandler, which does not expect any views further.

**Comment by arietto** [comment]
Should I use the following annotation instead (for ignoring any views for the current controller)?

     C_ATTR(End, :ActionClass(REST))
     void End(Context *c);

**Comment by dantti** [comment]
hmm you can remove the RenderView and do it manually, eg:

void End() {
  c->forward(c->view());
}

**Comment by arietto** [comment]
Hello! I mean that I don't have any views (I just send QByteArray which contains JSON from my driver.dll). I just want to know is there any posthandler on the controller level? I mean adding some custom headers for ControllerA, add other custom headers for ControllerB. I know about postDispatch, but it is too global.

**Comment by dantti** [comment]
Well you can use the End() methods for that, but remove the RenderView annotation then.

**Comment by dantti** [comment]
Closing as I believe End() controllers methods is enough for your issue.
