### ISSUE TITLE
Tutorial Errata

### ISSUE THREAD

**Issue by oberluz** [cutelyst/cutelyst#212]
Hi Daniel,

A few more issues with the online tutorial (not trying to be picky here, but these are the issues I encountered):

In https://github.com/cutelyst/cutelyst/wiki/Tutorial_03_MoreCutelystBasics#register-a-cutelyst-view : 

```
target_link_libraries(Hello
    ...
    Cutelyst::View::Grantlee # Add this line
    ...
}
```

should be:

```
target_link_libraries(MyApp
    ...
    Cutelyst::View::Grantlee # Add this line
    ...
}
```
If the tutorial is followed sequentially then in https://github.com/cutelyst/cutelyst/wiki/Tutorial_03_MoreCutelystBasics#using-the-default-template-name it states:

> Open src/books.cpp in your editor and comment out this line to match the following:
> ```
> -    c->setStash("template", "books/list.html");
> +    // c->setStash("template", "books/list.html");
> ```

But in fact at that point src/books.cpp looks like:

```
 #include <QtSql>
 #include <Cutelyst/Plugins/Utils/Sql>
void Books::list(Context *c)
{
     QSqlQuery query = CPreparedSqlQueryThreadForDB("SELECT * FROM book", "MyDB");
     if (query.exec()) {
         c->setStash("books", Sql::queryToHashList(query));
     }
}
```
because it was modified in https://github.com/cutelyst/cutelyst/wiki/Tutorial_03_MoreCutelystBasics#enable-the-model-in-the-controller a few steps before.The next section https://github.com/cutelyst/cutelyst/wiki/Tutorial_03_MoreCutelystBasics#return-to-a-manually-specified-template should also reflect this.

In https://github.com/cutelyst/cutelyst/wiki/Tutorial_04_BasicCRUD#add-a-delete-action-to-the-controller the suggested Books::delete_obj method seems to give an error:

> 15520:15520 cutelyst.request[debug] "GET" request for "books/id/5/delete" from "127.0.0.1"
> 15520:15520 cutelyst.dispatcher[debug] Path is "/books/delete_obj"
> 15520:15520 default[debug] *** INSIDE BASE METHOD ***
> 15520:15520 default[debug] *** INSIDE OBJECT METHOD for obj id= "5"  ***
> 15520:15520 cutelyst.grantlee[debug] Rendering template "books/delete_obj.html"
> 15520:15520 cutelyst.core[critical] "Error while rendering template: Template not found, books/delete_obj.html"
> 15520:15520 cutelyst.view[critical] "Error while rendering template: Template not found, books/delete_obj.html"
> 15520:15520 cutelyst.stats[debug] Response Code: 200; Content-Type: text/html; charset=utf-8; Content-Length: 0
> 15520:15520 cutelyst.stats[info] Request took: 0.149688s (6.680/s)
> .---------------------------------+-----------.
> | Action                          | Time      |
> .---------------------------------+-----------.
> | /books/base                     | 0.000056s |
> | /books/object                   | 0.000371s |
> | /books/delete_obj               | 0.148713s |
> |  -> /books/list                 | 0.000045s |
> | /End                            | 0.000128s |
> | Cutelyst::GrantleeView->execute | 0.000116s |
> .---------------------------------+-----------.

and causes the browser to display:

> Error while rendering template: Template not found, books/delete_obj.html

I changed the method to that used in the cutelyst-tutorial repo and seems to work (although I could not see the status message):

```
void Books::delete_obj(Context *c)
{
    QVariantHash book = c->stash("object").toHash();
    QString statusMsg;

    // Delete the object on the database
    QSqlQuery query = CPreparedSqlQueryThreadForDB("DELETE FROM book WHERE id = :id", "MyDB");
    query.bindValue(":id", book.value("id"));
    if (query.exec()) {
        // Set a status message to be displayed at the top of the view
        statusMsg = "Book deleted.";
    } else {
        // Set an error message to be displayed at the top of the view
        statusMsg = query.lastError().text();
    }

    // Redirect the user back to the list page. Note the use
    // of actionFor as earlier in this section (BasicCRUD)
    c->response()->redirect(c->uriFor(CActionFor("list"), ParamsMultiMap{
                                {"status_msg", statusMsg }
                            }));
}
```
In https://github.com/cutelyst/cutelyst/wiki/Tutorial_04_BasicCRUD#try-the-delete-and-redirect-with-query-param-logic the delete action does display the green status message but when I reload the browser page it is still displayed (ie it doesn't disapear).

Finally, the tutorial finishes at 05, although other sections are mentioned. Maybe work in progress?

The tutorial is great by the way.

**Comment by dantti** [comment]
>Finally, the tutorial finishes at 05, although other sections are mentioned. Maybe work in progress?
Yes, sort of that, time is shot ....
The wiki is open do you mind fixing those yourself?

**Comment by oberluz** [comment]
ok, will do

**Comment by adriaandegroot** [comment]
I have addressed the first erratum (and then discovered that my packaging doesn't have the Grantlee templates, so I got stuck in following the tutorial). Also updated some other minor bits and pieces.

@oberluz if you're logged in to GitHub, each wiki page should have an *Edit* button (scroll to top) above the list of pages, and you can directly edit in your web browser.

@dantti cutelyst itself contains an *examples/hello-world* directory (which is not a stand-alone example, it works only within the cutelyst repo), perhaps it'd help to have the steps or chapters of the tutorials in there?

**Comment by dantti** [comment]
@adriaandegroot for the tutorial there is https://github.com/cutelyst/cutelyst-tutorial

**Comment by dantti** [comment]
Closing this since the tutorial now needs to be updated for v3 and Cutelee.
