### ISSUE TITLE
Asynchronous processing connection state

### ISSUE THREAD

**Issue by windymindy** [cutelyst/cutelyst#215]
Shouldn't there be a way to check context state when processing asynchronously?
https://github.com/cutelyst/cutelyst/blob/master/examples/hello-world/root.cpp#L195
I am concerned about scenario client disconnects while timer is still active.

**Comment by dantti** [comment]
If the client disconnects and the Context get's destroyed the timer will also be destroyed due it being child of Context.

**Comment by windymindy** [comment]
I would like to pass context pointer or request id to another thread via signal-slot and then return back to server thread to write response.
Do I have to track destroyed signal to update processed request contexts collection?

**Comment by dantti** [comment]
Sure, calling Context/Req/Res methods is not thread safe, but if you for example connect a thread signal to a lambda which has Context as the destination, then when Context gets destroyed the lambda connection will also be.

**Comment by windymindy** [comment]
Thanks. I thought of some method to check whether context still exists, but that is fine enough.
