### ISSUE TITLE
Upload files greater than 2Gb

### ISSUE THREAD

**Issue by haralambop** [cutelyst/cutelyst#216]
It seems to be a problem uploading files bigger than 2GB.

Following code

const auto uploads = c->request()->uploads();
        for (Upload *upload : uploads) {
             upload->save("/tmp/" + upload->filename());
           }
produces this error message and the file is empty in /tmp/ 
QIODevice::read (Cutelyst::Upload): Called with maxSize < 0

With files smaller than 2GB there is no problem except a warning

Cannot create /tmp/ for output

Although the file is created successfully

**Comment by dantti** [comment]
Did you set a post-buffer value? Without it, the upload is going to be stored into a QByteArray which has a int 31 bit addressing limitation which is 2GB, with post-buffer if the upload is bigger than some specified value say 8MB it will use instead a QTemporaryFile, which has 63bit for addressing.

**Comment by haralambop** [comment]
I set
post-buffering = 2147483648
in the [wsgi] section
but I get the same error
QIODevice::read (Cutelyst::Upload): Called with maxSize < 0

**Comment by dantti** [comment]
As I said with post-buffer if the upload is bigger than some value it will use a QTemporaryFile.

You just set a value that will not use the QTemporaryFile because it's too big, unless the file
is more than 2.1GB it will still try to use a QByteArray, try using 800000 for example.

I also have never worked with such big files but I believe this is the problem.

Also do a `qDebug() << c->request->body();` so that you can see the class name holding the upload data.

**Comment by dantti** [comment]
Did it work? Can I close this one?

**Comment by haralambop** [comment]
I set several values in the config.ini for

**Comment by dantti** [comment]
which class is holding your upload? (the qDebug() ouput I asked you for)

**Comment by haralambop** [comment]
The output of the

**Comment by haralambop** [comment]
The problem is cutelyst

**Comment by haralambop** [comment]
Found the problem:

**Comment by haralambop** [comment]
in 
https://github.com/cutelyst/cutelyst/blob/master/Cutelyst/multipartformdataparser.cpp

-  int endOffset = pos - len + i - boundarySize - 1;
+ qint64 endOffset = pos - len + i - boundarySize - 1;

If the file is bigger than 2 GB then the endOffset was negative

**Comment by dantti** [comment]
great, odd the compiler didn't warn about this, mind doing a PR?

**Comment by haralambop** [comment]
No.

**Comment by dantti** [comment]
2.9.0 release is already released, I could do a 2.9.1, but I prefer doing a 2.10.0, will do once this gets in, thanks.

**Comment by haralambop** [comment]
ok thanks

**Comment by dantti** [comment]
I'll probably do a new 2.10.0 on monday, thanks.
