### ISSUE TITLE
QNativeSocketEngine client instead of Cutelyst::Context

### ISSUE THREAD

**Issue by Khaledjallouli** [cutelyst/cutelyst#217]
Hello!

I am working with Cutelyst as C++ web framework for back-end.

When I have multiple clients connected to my server with different IP address, sometimes there is QNativeSocketEngine as a new client instead of Cutelyst::Context. In that moment, the back-end crash ! 

Do you have an idea of what might be the source of this problem, please?

Thanks in advance!

Best regards,
Khaled

**Comment by dantti** [comment]
hmm that sounds like some memory corruption, do you have some backtrace?

**Comment by Khaledjallouli** [comment]
Debug: void WebSocketServer::handleMessage(Cutelyst::Context*) Contexte:  Cutelyst::Context(0x1f743a8)
Debug: Context list :  (Cutelyst::Context(0x1f8ad60), Cutelyst::Context(0x1f59450), Cutelyst::Context(0x1f743a8))
Debug: void WebSocketServer::initSubscription(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits_GET(Cutelyst::Context*)
Debug: QThread(0x1e73660, name = "0")
Debug: QJsonObject({"DATA"})

Debug: void WebSocketServer::handleMessage(Cutelyst::Context*) Contexte:  Cutelyst::Context(0x1f9ff60)
16/11/19 - 15:39:29:363 : Debug: Context list :  (Cutelyst::Context(0x1f8ad60), Cutelyst::Context(0x1f59450), Cutelyst::Context(0x1f743a8), Cutelyst::Context(0x1f9ff60))
Debug: void WebSocketServer::initSubscription(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits_GET(Cutelyst::Context*)
Debug: QThread(0x1e73660, name = "0")
Debug: QJsonObject({"DATA"})

Debug: void WebSocketServer::handleMessage(Cutelyst::Context*) Contexte:  Cutelyst::Context(0x1fa1810)
Debug: Context list :  (Cutelyst::Context(0x1f8ad60), Cutelyst::Context(0x1f59450), QNativeSocketEngine(0x1f743a8), Cutelyst::Context(0x1f9ff60), Cutelyst::Context(0x1fa1810)) 

Debug: void WebSocketServer::initSubscription(Cutelyst::Context*)
Debug: CommClient::decode() iFrameId = 6
Debug: Got close 1001 "" at Cutelyst::Context(0x1f9ff60)
Debug: Context list :  (Cutelyst::Context(0x1f8ad60), Cutelyst::Context(0x1f59450), QNativeSocketEngine(0x1f743a8), Cutelyst::Context(0x1fa1810))
Debug: void WebSocketServer::handleMessage(Cutelyst::Context*) Contexte:  Cutelyst::Context(0x1fa0640)


Note : The 0x1f743a8 address was for the Cutelyst :: Context type and after it became QNativeSocketEngine. I found it strange! Do you have an exlanation please?

**Comment by dantti** [comment]
As I said this looks like memory corruption, perhaps some delete in your code, try to get a backtrace of the crash, gdb usually also gives hints if it was a memory corruption..

**Comment by Khaledjallouli** [comment]
The problem occurs when I close my websocket connection. It does not work every time, especially when I use my phone as a client. When I do not get a Got close message, the next connection on the same device hangs!

In the trace below, I show 3 clients, I close one of them, it works. When I close the second one, I do not get the Get close message. When I add another client, instead of having 2, I have 3, one of them is QNativeSocketEngine which is normally deleted : 

Debug: Context list :  (Cutelyst::Context(0x1bacd08), Cutelyst::Context(0x1baefe0), Cutelyst::Context(0x1bd06e8))
Debug: void WebSocketServer::initSubscription(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits(Cutelyst::Context*)
Debug: virtual void ApiV1::tighteningUnits_GET(Cutelyst::Context*)
Debug: QThread(0x1ab2660, name = "0")
Debug: QJsonObject({"DATA"})

Debug: CommClient::decode() iFrameId = 6
Debug: Got close 1001 "" at Cutelyst::Context(0x1baefe0)
Debug: Context list :  (Cutelyst::Context(0x1bacd08), Cutelyst::Context(0x1bd06e8))
Debug: about to be destroyed QObject(0x1baefe0) QObject(0x1baefe0)

Debug: CommClient::decode() iFrameId = 6
Debug: CommClient::decode() iFrameId = 6

 !!!!!!!!!!!!!!!!!!!!!!!!!!!! NORMALLY I HAVE GET CLOSE MESSAGE HERE !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

Debug: about to be destroyed QObject(0x1bd06e8) QObject(0x1bd06e8)
Debug: CommClient::decode() iFrameId = 6
Debug: CommClient::decode() iFrameId = 6

Debug: void WebSocketServer::handleMessage(Cutelyst::Context*) Contexte:  Cutelyst::Context(0x1bd0958)
17/11/19 - 11:45:45:058 : Debug: Context list :  (Cutelyst::Context(0x1bacd08), QNativeSocketEngine(0x1bd06e8), Cutelyst::Context(0x1bd0958))


My code to do that is :  

 connect(req, &Cutelyst::Request::webSocketClosed, [=] (quint16 code, const QString &reason) {
             qDebug() << "Got close" << code << reason << "at" << c;
             m_listContext.removeAll(c);
         });

**Comment by Khaledjallouli** [comment]
I solved the problem ! 
I used destroyed method to remove the context from my list.

 connect(c, &Cutelyst::Context::destroyed, [=](QObject *obj) {
            qDebug() << "about to be destroyed" << obj << c;
            m_listContext.removeAll(c);
            qDebug() <<"Context list : " <<  m_listContext;
        });

         connect(req, &Cutelyst::Request::webSocketClosed, [=] (quint16 code, const QString &reason) {
            qDebug() << "Got close" << code << reason << "at" << c;
         });

Thanks for your help!

**Comment by dantti** [comment]
Ok, so the issue was only when using websockets?

The issue was that webSocketClosed didn't always emit?
