### ISSUE TITLE
Soft termination of user threads using slot for Application::shutdown signal

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#220]
Hello! I have a couple of threads which must be gently terminated in the Controller slot `slotShutdown()` linked with `Application::shutdown`.  I have typical worker objects (`QObject` descendants) and corresponding `QThread`s. I emit `finalize()` signal within `slotShutdown()`. Then I periodically check worker object atomic bool flag isFinalized in a loop. I quit worker `QThread` after that. 
AFAIK, I cannot rely on other slots within Controller after `Application::shutdown`, that's why I have to check other workers state in a loop using synchronized flag. But I expect that eventloops of other threads are still working when I emit signal within Controller `slotShutdown()`.  
Sometimes the signal is not catched within worker objects, so the loop is eternal. What can be done? 
I don't want to call methods of worker objects within Controller thread, because I've got Qt warnings about killing timers in the wrong threads etc.
BTW, I've used single process (master), single REST Controller thread for this experiment.

**Comment by dantti** [comment]
not sure I understood what you did, but why don't you call QThread::requestInterruption() then inside the thread you check for QThread::isInterruptionRequested() and outside the thread you waid() for it to finish?

**Comment by arietto** [comment]
My worker object has several slots. So, the corresponding thread can be idle sometimes. Is it reasonable to add  `QThread::isInterruptionRequested()` not only in my worker slots, but in `worker object` `timerEvent()`? BTW, what exact Qt signal in event queue prevents `Controller` thread to execute other slots after `slotShutdown()` execution? Non-controller threads process signals from `slotShutdown()` in ~50% of cases. It looks like (look-and-feel) description of  `void QCoreApplication::aboutToQuit()` signal - key phrase is *last-second cleanup*.
So, should I add signalFinalized() in worker object, which is linked with `QThread::quit()`?

    if (QThread::currentThread()->isInterruptionRequested())
    {
     //finalize some stuff
     //...
     emit signalFinalized();
    }

**Comment by arietto** [comment]
So, your hint was helpful, thank you, sir.
But there is another ~pain in the ass~ problem during termination - QtWebSockets module.
I use `QWebSocketServer` and `QWebSocket` table. I `close()` `QWebSocketServer` and call `abort()`/`deleteLater()` for items in `QWebSocket` table when I detected QThread::isInterruptionRequested().

If the websocket client connects to my service before SIGINT, then termination fails because of some running thread (I suppose it's internal `QWebSocket` thread). Termination is successful if there were no connections. Is it possible to fix? I've tested in on Linux Mint 18.3 x64, Qt 5.12.1.

**Comment by dantti** [comment]
Why do you use QtWebSockets if Cutelyst provides WebSockets?

**Comment by arietto** [comment]
Well, I prefer to use Qt official version, because it contains documentation.
I've found that you gave some samples here:
https://github.com/cutelyst/cutelyst/issues/123
I have to learn it.
What are the benefits of your version?

**Comment by dantti** [comment]
Well it's integrated, a little faster, doesn't has blocking code (which the Qt one had, not sure they fixed it).
There is a working chat in the examples, it's pretty easy to use, you can also look for Virtlyst to see a version that uses the binary streams.

**Comment by dantti** [comment]
Ah the the Qt version has some security issues with buffers getting too big as the WebSockets protocol was very badly designed on this matter.

**Comment by arietto** [comment]
OK, I'll study that.

**Comment by arietto** [comment]
I need to send notifications to all websocket clients (I've got one cutelyst-wsgi2 instance).
Sorry, I can't understand how to manage `QSet<Response*> websocketClients` when disconnection occurs. I've got disconnection signal from `Request*` instance. How can I detect `Response*` instance for removal for QSet?
I've studied the last sample:
https://github.com/cutelyst/cutelyst/issues/177#issuecomment-460071491
But I suppose that pair address+port as a key is not safe, because one can have multiple clients on the same machine.

**Comment by arietto** [comment]
Should I have `QHash<Request*, Response*>` websocketClients? What about their lifetime (memory management)?

**Comment by dantti** [comment]
I really need to improve the docs a bit, and provide a few more examples.

To track client disconnection the best way is to connect to Context::destroyed signal, this is because if you explicit close the client connection the webSocketClosed() signal is not emitted.

In one of my web applications I have a QMultHash<int, Context *c> where int is the device-id of my database and, so when something on the database changes, I get all Contexts and send a websocket message.

The best way to avoid leaks is to either be a child of Context or connect to it's destroyed signal.

**Comment by dantti** [comment]
closing this, feel free to open a new issue or ask questions on the mailing list.
