### ISSUE TITLE
Organizing multithreaded single-process REST controller with Websocket support.

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#222]
Hello! I use cutelyst-wsgi2 in a single-process mode. Is it possible to use Cutelyst websockets for multiple threads (multiple controller instances) within the same process?
AFAIK, there are warnings like these: `QSocketNotifier: socket notifiers cannot be disabled from another thread`. Actually, I'd like to have a separate thread for a sort of WebSocket manager which is shared among Controller instances.
BTW, I use some static members within controller in order to share them between controller instances. I adjust them in postFork, using mutex and checking isInitialized flag.
Examples of static members are worker object (with business logic) and corresponding worker thread. Controller emits signals for worker objects. Is it reasonable approach?

**Comment by arietto** [comment]
I suppose that I have to store the pointer (static member of Controller class) to Controller instance which was the first one in postForking, So, one of controller threads is set as the default one and is used for adjusting Controller static members and working with websocket stuff. Other contoller threads delegate working with websockets via signals/slots.
Then, we make connections like this:
connect(this, &Controller::signalHandshakeRequired, sDefaultControllerInstance, &Controller::slotaHandshakeRequired);

**Comment by arietto** [comment]
I use single-directional mode with websockets: REST controller notifies all websocket clients. But to the service requests are made using traditional HTTP verbs.

**Comment by arietto** [comment]
Oh, sharing `Context c*` for websocket handshaking between default and current controller threads is a bad idea.

**Comment by arietto** [comment]
There is still some problem with shutdown slot in Controller when I use websockets (whether Qt or Cutelyst websockets).
I call `webSocketClose()` for accumulated `QSet<Context*>` in `slotShutdown`. After that the cutelyst-wsgi2 is still active. If there were no websocket connections, then it quits normally.

**Comment by dantti** [comment]
Yes, don't share Controller classes between threads, you can send Qt Signals, to communicate but if your application might need to scale it's better to have some other sort of IPC like database notify..

There is some sort of issue I ran another day that once I hit CTRL+C the websockets clients calling close didn't have it's data sent, nor the disconnectFromHost() was working, these UNIX signals aren't my friends :)

**Comment by arietto** [comment]
I've checked cutelyst-hello-world example. It is not closed by Ctrl C when websocket connection has occured.

**Comment by arietto** [comment]
Is it possible to check that websocket is disconnected without using signal/slot mechanism? I mean a sort of check in a loop with delay within `slotShutdown`.

**Comment by dantti** [comment]
It's destroyed when disconnected the problem that I saw was that it wasn't closing after CTRL+C...

**Comment by arietto** [comment]
OK, Does using Cutelyst websockets mean using implicit additional threads under the hood?

**Comment by dantti** [comment]
No

**Comment by arietto** [comment]
I disconnect websockets manually, in `shutDown` slot of my controller.
I've noticed that `TcpServer::shutdown()` was called before `Context::destroyed`.

cutelyst/wsgi/tcpserverbalancer.cpp:412
`connect(engine, &CWsgiEngine::shutdown, server, &TcpServer::shutdown);` 

/home/elias/projects/current/cutelyst/wsgi/cwsgiengine.cpp:85
`connect(this, &CWsgiEngine::shutdown, this, [localApp] {
        std::cout << "Emitting shuttingDown signal\n";
        Q_EMIT localApp->shuttingDown(localApp);
    });`

**Comment by arietto** [comment]
I think that `TcpServer::shutdown()` must be called AFTER all websockets were closed.

**Comment by arietto** [comment]
Maybe, all Controllers should have some signal: signalFinished,
The default behaviour is to emit it. When all controllers emitted this signal (closed websockets), then it's possible to shutdown TCP server.

**Comment by dantti** [comment]
I think before I tell the TcpServer to shutdown I should go and close all websockets, they are long lived connections that it shouldn't be waiting to finish as they usually don't have a reason to.
Need to test if this works.

**Comment by arietto** [comment]
OK, glad to see your approach.

**Comment by dantti** [comment]
I have fixed shutdown issues, so I believe this is fixed
