### ISSUE TITLE
Overriding  CUTELYST_PLUGINS_DIR

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#225]
Hello! I've met the following snippet in 
`Component *Application::createComponentPlugin(const QString &name, QObject *parent)`:

`const QByteArrayList dirs = QByteArrayList{ QByteArrayLiteral(CUTELYST_PLUGINS_DIR) } + qgetenv("CUTELYST_PLUGINS_DIR").split(';');`

Why is CUTELYST_PLUGINS_DIR env appended to CUTELYST_PLUGINS_DIR define instead of overriding?

**Comment by dantti** [comment]
The idea is that both dirs can be used, specially an user defined one
