### ISSUE TITLE
Assigning headers in postdispatch and WebSockets

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#226]
Hello. I assign custom headers in postDispatch slot of `Application`. But it fails for websockets.
I'd like to skip assigning when I deal with handshaking. What is correct filter for that? At the moment, I compare the path of `res()` (detecting "handshake" method of the controller by name), but it's hardcoded (not elegant).
   
 `Q_ASSERT_X(!(d->engineRequest->status & EngineRequest::FinalizedHeaders),
               "setHeader",
               "setting a header value after finalize_headers and the response callback has been called. Not what you want.");`

**Comment by dantti** [comment]
I guess I should add a bool finalizedHeaders(); to response
