### ISSUE TITLE
Cannot install on macOS

### ISSUE THREAD

**Issue by KowalskiThomas** [cutelyst/cutelyst#227]
I've used Cutelyst in the past on Debian and Ubuntu without issues, though I recently tried to set it up on macOS Mojave and couldn't get it to work... 

Here's my procedure:
```
$ cd cutelyst
$ mkdir build
$ cd build
$ cmake ..
$ make
... Everything goes well ...
$ make install
... Build messages ...
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:44 (file):
  file cannot create directory: /usr/lib/cmake/Cutelyst2Qt5.  Maybe need
  administrative privileges.


make: *** [install] Error 1
$ sudo make install
... Build messages ...
Install the project...
-- Install configuration: ""
CMake Error at cmake_install.cmake:44 (file):
  file cannot create directory: /usr/lib/cmake/Cutelyst2Qt5.  Maybe need
  administrative privileges.


make: *** [install] Error 1
```

Would you happen to know what the issue is here? I didn't find anything of help googling the error message... most of the time it's people who forgot to run the command with `sudo` but it's clearly not the case here...

**Comment by dantti** [comment]
That error is exactly lack of privileges, either sudo or su should fix the issue, I have it installed on Majave just fine a few days ago, my Qt5, cmake was installed with brew in case that matters..
