### ISSUE TITLE
Example of HTTP 2 WSGI server and client

### ISSUE THREAD

**Issue by fro0m** [cutelyst/cutelyst#229]
I tried to understand how to use WSGI http2 server with client app wtitten in Qt. Please share an example how to make it work. It would be very helpful.

**Comment by dantti** [comment]
If you use a browser as a client you must setup the ssl cert for it, once that's done just add --https-h2 so that HTTP/1.1 HTTPS can be negotiated to H2

**Comment by fro0m** [comment]
I use qt websocket classes. Not a browser. Does it work with http 2 by default?

**Comment by dantti** [comment]
WebSocket protocol is not supported over HTTP/2, there is a draft for adding support for it but only Firefox seems to have implemented it, as for QtWebsockets they don't.
