### ISSUE TITLE
running error

### ISSUE THREAD

**Issue by SatyanarayanaEpigon** [cutelyst/cutelyst#235]
libServerREST.so    is in this path /home/yazmi/EdgeServer_Rest_API/src/ iam running from diffrent path i amgetting below error can u  tell what has to be done

yazmi@yazmi-NUC6CAYH:~$ cutelyst2 -r --server --app-file  /home/yazmi/EdgeServer_Rest_API/src/libServerREST.so 
Installing EPoll event loop
3790:3790 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Error: failed to find project
Cutelyst-WSGI terminated

**Comment by dantti** [comment]
cutelyst2 tries to find your project sources as it's a dev tool, if you want to run from another directory use cutelyst-wsgi2.
