### ISSUE TITLE
Distinguish async requests 

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#236]
Hello! Thank you for `detachAsync()/attachAsync()` feature. If the client sends multiple requests (with different params) to the same HTTP method, then I have multiple `Context*` instances. Each instance has lambda connected with some signal `infoReceived` (from external data source). But each `Context*` instance will handle non-relevant stuff and it can call `attachAsync()` prematurely (which is wrong). Should I put some unique request id via QObject::setProperty for  `Context*` instances?
The signal will have the following signature:
infoReceived(requestId, someData).  
So,  in lambda I will compare requestId with value saved in context. If mismatch detected then `attachAsync()` won't be called.

**Comment by dantti** [comment]
Sure, that sounds fine, I'd however use the stash as it's a little faster than setProperty();

**Comment by arietto** [comment]
Ok, thank you.
