### ISSUE TITLE
install package cannot be used in a cross compile environment

### ISSUE THREAD

**Issue by HenryMiller1** [cutelyst/cutelyst#241]
I'm working on an embedded system and trying Cutelyst.  I have successfully built Cutelyst and created an install package, but the package cannot be used in downstream cmake projects when it is installed into my sysroot.  (I use a [cmake toolchain](https://cmake.org/cmake/help/v3.6/manual/cmake-toolchains.7.html) file to find the sysroot and otherwise setup my enviornment)

When cmake gets to the ```FIND_PACKAGE(CutelystQt5)``` line I get the following error.

```
CMake Error at [sysroot]/usr/lib/cmake/Cutelyst2Qt5/Cutelyst2Qt5Targets.cmake:122 (message):
-- Configuring incomplete, errors occurred!

The imported target "Cutelyst::Core" references the file

     "/usr/lib/libCutelyst2Qt5.so.2.8.0"
```

I depend on other cmake packages that work. So this is a problem with Cutelyst cmake packages, not cmake or my enviornment.

**Comment by HenryMiller1** [comment]
The root cause of this problem is Cutelyst cmake files reference ${CMAKE_INSTALL_LIBDIR} instead of lib in the install command.  This forces cmake to hardcode looking in /usr/lib instead of looking in ${sysroot}/lib which means cutelyst cannot be used in a cross compile environment.  If the relative path lib is used instead of ${CMAKE_INSTALL_LIBDIR} the package seems to work.

```
install(...
   DESTINATION ${CMAKE_INSTALL_LIBDIR}/cmake/Cutelyst${PROJECT_VERSION_MAJOR}Qt5/
...
```
Change to
```
install(...
   DESTINATION lib/cmake/Cutelyst${PROJECT_VERSION_MAJOR}Qt5/
...
```

This needs to be done for everything installed underlib.  That includes the cmake config files (Cutelyst{version}Qt5Config.cmake and the EXPORT Cutelyst targets).

I mostly have a personal patch, but since this is for work I'd have to spend more time getting legal approval to submit the fix than it would take for someone else to apply the fixed based on this report.  (If we decide this project is useful I might do that, but we are still evaluating options)

**Comment by dantti** [comment]
@HenryMiller1 Well I do use it in a cross env using buildroot, this used to work fine.

@buschmann23 wouldn't changing this break distro packaging?

**Comment by buschmann23** [comment]
@dantti Yes, hard coding it to `lib/cmake/Cutelyst${PROJECT_VERSION_MAJOR}Qt5/` would brake packaging as on 64 bit systems it goes into `/usr/lib64/cmake/...`. Then I would have to patch it…

**Comment by HenryMiller1** [comment]
@dantti  If you use pkgconfig it may work.  If you have cmake project and use the cmake config files it does not.  Since I'm working in a cmake project I don't normally use the pkgconfig files.

I'm not sure what you mean by buildroot.

As far as I can tell this shouldn't break distro packages. In fact because this is using the cmake defaults not custom overrides I would expect this to work better for distro packagers because they can use their default cmake package rules without having to adjust anything. In any case all files go to the same location so I doubt they will even notice. 

Above assumes unix. Windows and Mac do their own thing, but there I would expect the cmake defaults to work better than a custom override.

**Comment by dantti** [comment]
I don't use pkgconfig.

[Buildroot](https://buildroot.org/)

Well I have worked on many CMake projects and they all always set paths like this and still work in cross enviroment.

In fact I do use is for cross compiling on Linux for Windows with CMake, so IMHO I think you might have done something wrong.

**Comment by HenryMiller1** [comment]
Looking again, instead of the change suggested previous, if where CMAKE_INSTALL_LIBDIR is set, ${CMAKE_INSTALL_PREFIX} is removed from the front so it is lib/${CMAKE_LIBRARY_ARCHTECTURE} everything works.  

This is a better fix: one line and it should address the concerns of @buschmann23

**Comment by HenryMiller1** [comment]
http://cmake.3232098.n2.nabble.com/CMAKE-INSTALL-LIBDIR-full-path-or-relative-td7302556.html

Has an interesting discussion on why absolute paths are bad here.

@dantti I'm sure it works for you.  There are many different possible configurations. I will admit the one I work in is somewhat obscure (in house built with some ugly warts I can't remove easily) but it still works well with most cmake projects.

**Comment by buschmann23** [comment]
@HenryMiller1 No, it won’t. ;) Not every distro uses `lib/<arch>`. openSUSE and Fedora for example are using `lib<arch>`

**Comment by buschmann23** [comment]
@HenryMiller1 But GNUInstallDirs is in use here, so `CMAKE_INSTALL_LIBDIR` is relative.

**Comment by HenryMiller1** [comment]
@bushmann23 I had to google GNUInstallDirs: it isn't in use! CMAKE_INSTALL_LIBDIR is being hardcoded via a SET call.

Replace the SET (CMAKE_INSTALL_LIBDIR) with
```include(GNUInstallDirs)```

and everything works for me, and should work for all distros where the current is wrong for at least some.

**Comment by buschmann23** [comment]
@HenryMiller1 It is in master. :)

**Comment by HenryMiller1** [comment]
I'm using the 2.8.0 release.  Which is the latest release.  (there is a 2.9.0, but it isn't marked as latest release... this is confusing and might be a different issue)

**Comment by dantti** [comment]
@HenryMiller1 if master works for you I can roll a new release today or tomorrow.

**Comment by dantti** [comment]
@HenryMiller1 v2.9.0 is doesn't have GNUInstallDirs, I forgot to mark it as lastest on GitHub, but stable releases are the ones tagged...

**Comment by HenryMiller1** [comment]
@dantti 

plugins are installed into /usr/local/lib/cutelyst2-plugins while the other libraries are installed in /usr/lib  I don't think this is what you intend. My embedded system is yocto linux system, so it shouldn't be too hard to duplicate this.

The install works for me and I can build a simple library that links Cutelyst but I reserve the right to open a new bug in a couple weeks when I try to use it...

**Comment by buschmann23** [comment]
@HenryMiller1 

This is intended as most distros have policies for packaging shared libraries like this one:

https://en.opensuse.org/openSUSE:Shared_library_packaging_policy#Plugins

GNU autotools are using pkglibdir for this:

https://www.gnu.org/software/automake/manual/html_node/Uniform.html
