### ISSUE TITLE
Chained attribute and controller namespace

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#242]
Hello! I'd like to add the following method
`POST http://127.0.0.1:5555/dummy/processes/{id}/shutdown`,
where "dummy" is a controller namespace.
How should I construct method signatures in the controller **considering namespace**?
Should "base" method (start of chain) have `:Chained("/")` or `:Chained("/dummy")`?
How should "_POST"-suffixed method attributes be organized in this case?

**Comment by dantti** [comment]
Chained actions always start the chain to "/" the namespace is then only used for naming the actions internally.
How do you mean by _POST? Are you using the REST action class? If so it's the same way as you will have a single endpoind which is the method without _POST once that is called the REST class checks if there is a _POST version of it.

**Comment by arietto** [comment]
Sorry for misleading. I mean the following workaround within REST action class (I have to repeat "dummy" namespace in the chain "starter" within `:PathPart`, instead of `:Chained("/dummy")`). Am I right?

    C_ATTR(processes, :Chained("/") :PathPart("dummy/processes") :CaptureArgs(1) : ActionClass(REST))
    void processes(Context *c, const QString& someParam);
    C_ATTR(processes_shutdown_POST, :Chained("processes") :PathPart("shutdown") :Args(0))
    void processes_shutdown_POST(Context *c);

**Comment by arietto** [comment]
So, is there any other approach to avoid intermediate method like `processes` above? It just stashes parameter which will be used in `processes_shutdown_POST`.

**Comment by dantti** [comment]
Yes you need to repeat that, afaik Catalyst works this way, which doesn't mean we couldn't have some special attribute to chain on the namespace.
The Action class unfourtunately works like that and it's not easy to change.

There is an open issue that asks for another implementation to deal with REST, which is simpler but I haven't had time to try coding it.

**Comment by arietto** [comment]
OK, thank you.
