### ISSUE TITLE
Upload files greater than 2Gb ( reopen ticket #216)

### ISSUE THREAD

**Issue by haralambop** [cutelyst/cutelyst#245]
I set several values in the config.ini for
post-buffering and
post-buffering-bufsize
without any success.
If the file is bigger than 2G then the file content is empty and the size is 0

**Comment by haralambop** [comment]
btw.

**Comment by dantti** [comment]
why not?
https://uwsgi-docs.readthedocs.io/en/latest/Options.html#post-buffering

**Comment by dantti** [comment]
the first is the size at which we will stop buffering and will write to file,
the second is the size of the buffer used to write to file
