### ISSUE TITLE
Error while rendering template: Template not found, hello.html

### ISSUE THREAD

**Issue by CubeEd** [cutelyst/cutelyst#247]
Hi @dantti 
 i created Qt Quick project at Qt Creator and linked your CuteLyst lib in **qmake**. Also linked **Cutelyst2Qt5ViewGrantlee**. added hello.html to root directory. I use this tutorial https://github.com/cutelyst/cutelyst/wiki/Tutorial_02_CutelystBasics
All compiles fine and run but have this error **_Error while rendering template: Template not found, hello.html._**
here is part of my **qmake** file

```
win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../../../../../usr/lib/release/ -lCutelyst2Qt5
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../../../../../usr/lib/debug/ -lCutelyst2Qt5
else:unix:!macx: LIBS += -L$$PWD/../../../../../../../usr/lib/ -lCutelyst2Qt5

INCLUDEPATH += $$PWD/../../../../../../../usr/include/cutelyst2-qt5
DEPENDPATH += $$PWD/../../../../../../../usr/include/cutelyst2-qt5

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../../../usr/lib/release/ -lCutelyst2Qt5Wsgi
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../../../usr/lib/debug/ -lCutelyst2Qt5Wsgi
else:unix:!macx: LIBS += -L$$PWD/../../../../../usr/lib/ -lCutelyst2Qt5Wsgi

INCLUDEPATH += $$PWD/../../../../../usr/include/cutelyst2-qt5/Cutelyst/WSGI
DEPENDPATH += $$PWD/../../../../../usr/include/cutelyst2-qt5/Cutelyst/WSGI

win32:CONFIG(release, debug|release): LIBS += -L$$PWD/../../../../../usr/lib/x86_64-linux-gnu/release/ -lCutelyst2Qt5ViewGrantlee
else:win32:CONFIG(debug, debug|release): LIBS += -L$$PWD/../../../../../usr/lib/x86_64-linux-gnu/debug/ -lCutelyst2Qt5ViewGrantlee
else:unix: LIBS += -L$$PWD/../../../../../usr/lib/x86_64-linux-gnu/ -lCutelyst2Qt5ViewGrantlee

INCLUDEPATH += $$PWD/../../../../../usr/lib/x86_64-linux-gnu
DEPENDPATH += $$PWD/../../../../../usr/lib/x86_64-linux-gnu
```

also my header file images.h which contain this function from example
    `C_ATTR(hello, :Local :AutoArgs)`
        `void hello(Context *c)`
       ` {`
        `    c->setStash("template", "hello.html");`
        `}`

also my **init()** function

```
bool Operator::init()
{
   new GrantleeView(this);
   new ImagesController(this);
   new VideoController(this);
    return true;
}

```
and **main.cpp**
#include <QGuiApplication>
#include <QQmlApplicationEngine>
#include <QQmlContext>
#include <QSettings>
#include <QQuickStyle>
#include <QIcon>
#include <Cutelyst/WSGI/wsgi.h>
#include "operator.h"

```
int main(int argc, char *argv[])
{
    QGuiApplication::setAttribute(Qt::AA_EnableHighDpiScaling);

    QGuiApplication app(argc, argv);

    Operator* server = new Operator();
    auto wsgi = new CWSGI::WSGI;
    wsgi->setHttpSocket({
                            { QStringLiteral(":3000") },
                                    });

    QIcon::setThemeName("DPI");

    QQmlApplicationEngine engine;
    engine.load(QUrl(QStringLiteral("qrc:/pages/MainWindow.qml")));
    if (engine.rootObjects().isEmpty())
    {
        return -1;
    }
```

    wsgi->exec(server);
}

What i did wrong ? have know idea. Can you help? Thanks

**Comment by dantti** [comment]
You forgot to set the GrantleeView include paths.

**Comment by CubeEd** [comment]
I did it where call **init()** function `#include <Cutelyst/Plugins/View/Grantlee/grantleeview.h>`

**Comment by dantti** [comment]
it's not a compilation or link error.
It's a runtime error because it's not finding your files, you need to set the include directory on the GrantleeView object

**Comment by CubeEd** [comment]
@dantti thank you now i see what you mean `GrantleeView::setIncludePaths();` Yes this fixed my problem.
