### ISSUE TITLE
How to map url to image

### ISSUE THREAD

**Issue by CubeEd** [cutelyst/cutelyst#248]
Hi @dantti  thanks for your work. I am new at CuteLyst and know how to map url to function(from your tutorial) but don't how map image. I know that for such files Cutelyst are using root directory.
What i want that for example when i write this in browser  **http://localhost:3000/someimage.png** i will be able to see that image. Thanks.

**Comment by dantti** [comment]
you can use StaticSimple plugin or static-map(2) configuration on WSGI server, the latter is better.

**Comment by CubeEd** [comment]
@dantti thanks for reply. You mean i should use 
`void setStaticMap2(const QStringList &staticMap);`
from `CWSGI::WSGI` class ?

**Comment by dantti** [comment]
yes

**Comment by CubeEd** [comment]
@dantti ok, thank you i will try.
