### ISSUE TITLE
wsgi error

### ISSUE THREAD

**Issue by SatyanarayanaEpigon** [cutelyst/cutelyst#249]
while i am running application  i am  getting below error

yazmi@yazmi-desktop:~/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST/src$ cutelyst2 -r --server --app-file libServerREST.so 
Installing EPoll event loop
3421:3421 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 8
spawned WSGI master process (pid: 3421)
spawned WSGI worker (and the only) (pid: 3422, cores: 1)
Loading application: libServerREST.so
3422:3422 wsgi[critical] Could not load application: "The shared library was not found."
DAMN ! worker 1 (pid: 3422) died, killed by signal 1 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 3423, cores: 1)
Loading application: libServerREST.so
3423:3423 wsgi[critical] Could not load application: "The shared library was not found."
DAMN ! worker 1 (pid: 3423) died, killed by signal 1 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 3424, cores: 1)
Loading application: libServerREST.so
3424:3424 wsgi[critical] Could not load application: "The shared library was not found."
DAMN ! worker 1 (pid: 3424) died, killed by signal 1 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 3426, cores: 1)
Loading application: libServerREST.so
3426:3426 wsgi[critical] Could not load application: "The shared library was not found."
DAMN ! worker 1 (pid: 3426) died, killed by signal 1 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 3427, cores: 1)
Loading application: libServerREST.so
3427:3427 wsgi[critical] Could not load application: "The shared library was not found."
DAMN ! worker 1 (pid: 3427) died, killed by signal 1 :( trying respawn ..
WSGI worker 1 respawned too much!
CHEAPING worker: 1
Cutelyst-WSGI terminated

**Comment by dantti** [comment]
The error is "The shared library was not found". You must be either at the root of the project or provide a full path to it

**Comment by SatyanarayanaEpigon** [comment]
yazmi@yazmi-desktop:~/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST/src$ cutelyst2 -r --server --app-file /home/yazmi/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST/src/libServerREST.so 
Installing EPoll event loop
11527:11527 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 8
spawned WSGI master process (pid: 11527)
spawned WSGI worker (and the only) (pid: 11528, cores: 1)
Loading application: /home/yazmi/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST/src/libServerREST.so
11528:11528 cutelyst.core[warning] Can not load translations from not existing directory: "/usr/local/share/cutelyst2/translations"
Changing directory2 to: /home/yazmi/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST

**Comment by dantti** [comment]
did it work? does this file exists?
`/home/yazmi/Yazmi_Cutelyst_Rest_API/BocServer_REST_API/ServerREST/src/libServerREST.so `

**Comment by SatyanarayanaEpigon** [comment]
it not worked file exists in that path

**Comment by dantti** [comment]
is the error the same with full path?

**Comment by dantti** [comment]
This https://github.com/cutelyst/cutelyst/commit/0aba7565a5b1305ccc29437b505dde79fe377eef
should improve this issue
