### ISSUE TITLE
cutelyst --server -r does not restart on file change

### ISSUE THREAD

**Issue by simonaw** [cutelyst/cutelyst#25]
Since Version 1.5.0 the development server does no longer restart on file change when started with `cutelyst --server -r`.
I am running Qt 5.8.0, grantlee 5.1.0, libsimplemail-qt-git 1.3.0

Can anyone reproduce this?

**Comment by simonaw** [comment]
Btw: the operaring system is Linux. So both defines `Q_OS_LINUX` and `Q_OS_UNIX` are set. The FileWatcher in wsgi.cpp never gets installed because of the early return.

**Comment by dantti** [comment]
Yeah, it's indeed a broken feature, it broke on cutelyst binary since now it uses cutelyst-wsgi library instead of uwsgi executable. This feature probably works on Windows which is funny since I only build it on CI to make sure it builds there.

**Comment by simonaw** [comment]
Well, I tried to look into this and moved the `if ( !masterChildProcess ) {...}` out of the `#ifdef` so that the file watcher gets installed. It triggers and I see in the debug log that it tries to terminate the process 5 times and then to kill it, but nothing happens and it gets stuck in an infinite loop.
Maybe you have an idea what I am missing here?

**Comment by dantti** [comment]
You made me almost rewrite wsgi :stuck_out_tongue: , just kidding thanks for the bug report.

**Comment by simonaw** [comment]
Oh my goodness, what a commit... Thank you very much for the quick action. Totally underestimated the complexity.

**Comment by Chaz6** [comment]
I installed the latest cutelyst from git today, and I am following the tutorial; the server stops when I recompile the application. Is there perhaps a regression?

```
File changed restarting... /home/linux/cutelyst-projects/Hello/build/src/libHello.so
File changed restarting... /home/linux/cutelyst-projects/Hello/build/src/libHello.so
Cutelyst-WSGI terminated
```
