### ISSUE TITLE
Making trailing path param optional

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#253]
Hello!
I'd like to have URL like `http://blabla.net/{id1}/{id2}`, where `id2` is an optional path param. 
How can I achieve this in my REST controller?
I am aware about query params, but appending `?id2={id2}` is more verbose.

**Comment by dantti** [comment]
I'd create two path controllers

    C_ATTR(foo1, :Path('foo') :AutoArgs)
    void foo1(Context *c, const QString &id1);
    
    C_ATTR(foo2, :Path('foo') :AutoArgs)
    void foo2(Context *c, const QString &id1, const QString &id2);
