### ISSUE TITLE
Set logging options for cutelyst-wsgi2

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#254]
Hello! How can I set logging options for cutelyst-wsgi2 via conf files?
In fact, at least I'd like to see available REST API methods table in console when cutelyst-wsgi2 starts (not cutelyst2).

**Comment by dantti** [comment]
Just enable/disable what do you want https://doc.qt.io/qt-5/qloggingcategory.html if you want the config on a file set QT_LOGGING_CONF.
