### ISSUE TITLE
installation in windows

### ISSUE THREAD

**Issue by SatyanarayanaEpigon** [cutelyst/cutelyst#258]
C:\Users\SYS\Downloads\cutelyst-2.11.0\build>cmake --build . --target INSTALL --config Release
mingw32-make.exe[1]: *** No rule to make target 'INSTALL'.  Stop.

i am trying to install in windows i am getting above error .how can  i install in windows

**Comment by dantti** [comment]
on Linux INSTALL is lowercase, no sure about Windows, VCPKG might be an easier way to install on Windows.
