### ISSUE TITLE
QSQLITE and threads

### ISSUE THREAD

**Issue by iastinf** [cutelyst/cutelyst#259]
How is it possible to run 

[Cutelyst]
DatabaseDriver = "QSQLITE"
and
threads = auto

I receive lots of segfaults
segfault at 7f8f74a1ff38 ip 00007f8f7497500b sp 00007f8f74a1ff30 error 6 in libsqlite3.so.0.8.6

**Comment by iastinf** [comment]
I open the sqlite db with

**Comment by iastinf** [comment]
I open the sqlite db successfully
auto name = "test_db_" + QString::number((quint64)QThread::currentThread(), 16)
auto db = QSqlDatabase::addDatabase(dbDriver,name);
db.setDatabaseName("path_to_db");
db.open()

but the following query fails

 QSqlQuery query = CPreparedSqlQueryThreadForDB("select * from foo","app_name");

default[warning] QSqlQuery::prepare: database not open 
cutelyst.utils.sql[critical] Failed to prepare query:

**Comment by dantti** [comment]
Take a look at how this is done on pastelyst:
https://github.com/cutelyst/pastelyst/blob/master/src/pastelyst.cpp#L80
