### ISSUE TITLE
Grantlee Templates no longer loaded

### ISSUE THREAD

**Issue by simonaw** [cutelyst/cutelyst#26]
Sorry, it's me again.
But unfortunately with cutelyst 1.6.0 (i.e. latest commit) Grantlee templates are no longer loaded. With the same setup and cutelyst 1.4.0 everything is fine.
The debug log shows that `Cutelyst::GrantleeView->execute` is executed but unfortunately `Content-Length` is returned as 0.

```
20513:20513 cutelyst.request[debug] "GET" request for "/" from "127.0.0.1"
20513:20513 cutelyst.dispatcher[debug] Path is "/"
20513:20513 cutelyst.grantlee[debug] Rendering template "index.html"
20513:20513 cutelyst.stats[debug] Response Code: 200; Content-Type: text/html; charset=utf-8; Content-Length: 0
20513:20513 cutelyst.stats[info] Request took: 0.000002s (500000.000/s)
.---------------------------------+-----------.
| Action                          | Time      |
.---------------------------------+-----------.
| /index                          | 0.000000s |
| /End                            | 0.000000s |
| Cutelyst::GrantleeView->execute | 0.000000s |
.---------------------------------+-----------.
```

**Comment by dantti** [comment]
Feel free to reopen if the bug persists :stuck_out_tongue:

**Comment by simonaw** [comment]
Excellent, works now! That, again, was fast.
Interesting though that I did not get any error like 'template not found' or something.

**Comment by dantti** [comment]
If you have Grantlee cache disabled and it's debug category I think it should display some template not found, sadly Grantlee maintainer is too busy and doesn't improve it at a good rate, I've considered forking it a few times already but I'm still trying to avoid that for the moment...
