### ISSUE TITLE
Trouble installing Cutelyst on Windows

### ISSUE THREAD

**Issue by sjkorvin** [cutelyst/cutelyst#262]
Hello. I am trying to install Cutelyst on Windows because I would like to use SimpleMail. I am new to building Qt-based applications. Using the Qt online installer, I had installed everything for Qt 5.15.0.

Running `cmake .. -G "MinGW Makefiles`, everything generates without an error; however, when I run `cmake --build . --config Release`, the build stops at 16% after `Linking CXX shared library ..\libCutelyst2Qt5.dll`.

I then get lines upon lines of undefined reference errors followed by:
```
collect2.exe: error: ld returned 1 exit status
Cutelyst\CMakeFiles\Cutelyst2Qt5.dir\build.make:443: recipe for target 'libCutelyst2Qt5.dll' failed
mingw32-make.exe[2]: *** [libCutelyst2Qt5.dll] Error 1
CMakeFiles\Makefile2:559: recipe for target 'Cutelyst/CMakeFiles/Cutelyst2Qt5.dir/all' failed
mingw32-make.exe[1]: *** [Cutelyst/CMakeFiles/Cutelyst2Qt5.dir/all] Error 2
Makefile:170: recipe for target 'all' failed
mingw32-make.exe: *** [all] Error 2
```
I am using the official MinGW build in `C:\MinGW\bin`. I would greatly appreciate any help in getting Cutelyst to build. Thank you.

**Comment by dantti** [comment]
First things first, do you want to use Cutelyst or only SimpleMail? If it's only SimpleMail they are not related you just need it.

About your error I can't see what's wrong there, and IMHO it's a lot easier to just use VCPKG on Windows.

**Comment by sjkorvin** [comment]
I just want to use SimpleMail. When I try to build SimpleMail using the MinGW Makefiles generator, I end up with the same kind of issue after `[ 43%] Linking CXX shared library libSimpleMail2Qt5.dll`.

I am part of an academic team and we are using Eclipse as the IDE. Is VCPKG only for Visual Studio?

**Comment by dantti** [comment]
VCPKG is a command tool not related with any IDE.
Closing this as it's not a Cutelyst issue, and for simple mail it's also too vague what the error you are having is.
