### ISSUE TITLE
Retrieving REST API

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#263]
Hello! Is it possible to have a method which returns REST API description (at least, as a plain text)?
I am aware that methods table can be printed within console. I'd like to have it in browser as well.

**Comment by dantti** [comment]
I'm not sure it's all public API, but I think it's, you could write a method which replies a JSON with that table.
IIRC there are some documents formats for documenting REST APIs but I've never looked deep into this.

**Comment by arietto** [comment]
OK, thanks.
