### ISSUE TITLE
Connection to port 

### ISSUE THREAD

**Issue by Loclay** [cutelyst/cutelyst#264]
The problem has been detected on CentOS 7 and Debian 9.12 (stretch).

I start:

```bash
cutelyst-wsgi2 -M -a /path/to/libMyApp.so --h1 localhost:3000
```
or from build directrory

```bash
cutelyst2 --server --app-file $PWD/libMyApp.so -- --chdir .. 
```

The programm starts with no error, but I have no connetction whith port 3000 (changing port or IP give same problem).
OS dos not listen the port. 

This problem I have only with last version (HEAD) 12.0. But I do not have this problem with "Commits on Apr 10, 2020". This is the last time I downloaded and used the cutelyst project before last week.

Forgive me for my English, I am not English speaker.

P.S The same problem with your cutelyst-tutorial project, not only with my libMyApp.so

**Comment by dantti** [comment]
It's a known bug I didn't have the time to fix it yet, it should work if you enable --reuse-port
