### ISSUE TITLE
Server: send an image as response.

### ISSUE THREAD

**Issue by alexandrosgk** [cutelyst/cutelyst#265]
Hello  @dantti,
First and foremost congratulation for your amazing work, it is really useful. I am complete a newbie about the whole situation. I have followed your instructions and I managed to succefuly  run the RESTful application. My goal is to create an  application, so that when my server accepts a request from a client, it sends an image as response. However, I have no clue how to start!! 
How can i listen the client's request? and more importantly how can my server send an Image back?
Thanks.

**Comment by dantti** [comment]
well if you still have no clue on how to start try the wiki tutorial, once you understand how to process a request replying an image is simply sending back a bunch of bytes of a QFile with proper mimetype, perhaps using static-map feature too.

**Comment by alexandrosgk** [comment]
Thanks for your response. I'm starting to understand the process.
Based on your server example, when i receive a get request, my server will send an image. 
Can the server response  be executed this way: c->response()->setBody();
Or 
do I need to use the static-map feature? If i use the second option I'm receiving an error about including the wsgi.

**Comment by alexandrosgk** [comment]
Finnally, I managed to send the image. I read it as Qfile and i sent it via response(). So far so good, when i visit the proper url, i can see the image. However, is it possible to send the image as file, namely, image.png?

**Comment by dantti** [comment]
static-map is a command line (or config file) feature of cutelyst-wsgi executable, it's preferred as it is faster, but it's for static content, ie not images that you create at run time, better still in this static case would be offloading to Nginx or some http front end as cutelyst serves files in a blocking way.

And yes c->response()->setBody() can be used too.

**Comment by alexandrosgk** [comment]
Thank you very much, I really appreciate your support. Finally, I managed to send succefully images via response (), when my server receives get requests.

**Comment by dantti** [comment]
you are welcome!

**Comment by alexandrosgk** [comment]
In order to avoid creating a new thread, may I ask you something else?
So far, my server is running in dev mode, namely, http://localhost:5000. How can I change the localhost, so that my server is accesible from other machines?

**Comment by dantti** [comment]
on cutelyst2 you need to add `--` then `--h1 IP:PORT` if `--h1 :5000` it will listen on all IPs

**Comment by dantti** [comment]
Everything after `--` is cutelyst-wsgi2 options

**Comment by alexandrosgk** [comment]
Hello Dantti!
May I ask you a dummy question?
Instead of running the server application via the cmd using this command "cutelyst2 -r --server --app-file path_to_it",
is it possible to build and run my application through the qt creator enviroment, creating a pro file?

**Comment by dantti** [comment]
It is, I only use QtCreator but not with qmake (that is going to die soon), you can create there a custom target that runs what is run on command line so you don't lose the auto reloading feature.
You can use Cutelyst with qmake by importing it's pkgconfig files or manually linking.
