### ISSUE TITLE
Unable to build!

### ISSUE THREAD

**Issue by mbnoimi** [cutelyst/cutelyst#266]
Hi,

I followed up the instructions mentioned in the wiki but I'm unable to build cutelyst successfully under my machine (Linux Mint 20 x64) because of:

```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ALL=on
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CUTELYST_PLUGINS_DIR: /usr/lib/x86_64-linux-gnu/cutelyst2-plugins
-- PLUGIN: View::Grantlee, enabled.
CMake Error at Cutelyst/Plugins/View/CMakeLists.txt:8 (find_package):
  By not providing "FindCutelee5.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Cutelee5",
  but CMake did not find one.

  Could not find a package configuration file provided by "Cutelee5" with any
  of the following names:

    Cutelee5Config.cmake
    cutelee5-config.cmake

  Add the installation prefix of "Cutelee5" to CMAKE_PREFIX_PATH or set
  "Cutelee5_DIR" to a directory containing one of the above files.  If
  "Cutelee5" provides a separate development package or SDK, be sure it has
  been installed.


-- Configuring incomplete, errors occurred!
See also "/mnt/Multimedia1/Downloads/cutelyst/build/CMakeFiles/CMakeOutput.log".

```
You can read the content of `CMakeOutput.log` [here](https://gist.github.com/mbnoimi/05505e35f1dbadd5d86b5b3b1ae7ec8b#file-cmakeoutput-log).

All the requirements are already installed.

```
apt install -y git cmake g++ uwsgi clearsilver-dev libgrantlee5-dev uuid-dev libcap-dev libzmq3-dev qtbase5-dev
```

**Comment by dantti** [comment]
you don't have all the requirements for BUILD_ALL, the first one is Cutelee which is a fork of Grantlee, https://github.com/cutelyst/cutelee, but surely there will be a bunch of others

**Comment by mbnoimi** [comment]
> you don't have all the requirements for BUILD_ALL, the first one is Cutelee which is a fork of Grantlee, https://github.com/cutelyst/cutelee, but surely there will be a bunch of others

Why you don't add all the dependencies as git submodule?

**Comment by mbnoimi** [comment]
> you don't have all the requirements for BUILD_ALL, the first one is Cutelee which is a fork of Grantlee, https://github.com/cutelyst/cutelee, but surely there will be a bunch of others

May you please guide me how to do it? The wiki doesn't mention anything about it!
I REALLY HATE CMAKE (I'm big fan of qmake) so I spent a hard time on `How to build cutelyst` (hours without gaining any progress)

**Comment by mbnoimi** [comment]
I installed `cutelee` and `simple-mail` using these commands:
```
mkdir build
cd build
cmake -DCMAKE_INSTALL_PREFIX=$prefix ..
cmake --build .
sudo cmake --build . --target install
```
But I still unable to build Cutelyst!
The new error is:
```
$ cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DBUILD_ALL=on
-- The CXX compiler identification is GNU 9.3.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- CUTELYST_PLUGINS_DIR: /usr/lib/x86_64-linux-gnu/cutelyst2-plugins
-- PLUGIN: View::Grantlee, enabled.
-- PLUGIN: View::Cutelee, enabled.
-- PLUGIN: View::ClearSilver, enabled.
-- PLUGIN: View::Email, enabled.
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29.1") 
-- Checking for one of the modules 'pwquality>=1.2.2'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'pwquality>=1.2.2' found
Call Stack (most recent call first):
  Cutelyst/Plugins/Utils/Validator/CMakeLists.txt:149 (pkg_search_module)


-- PLUGIN: Validator, enable PwQuality
-- PLUGIN: Memcached, enabled.
-- Checking for one of the modules 'libmemcached'
CMake Error at /usr/share/cmake-3.16/Modules/FindPkgConfig.cmake:707 (message):
  None of the required 'libmemcached' found
Call Stack (most recent call first):
  Cutelyst/Plugins/Memcached/CMakeLists.txt:2 (pkg_search_module)


-- PLUGIN: MemcachedSessionStore, enabled
-- PLUGIN: StaticCompressed, enabled
-- PLUGIN: CSRFProtection, enabled
CMake Error at /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:146 (message):
  Could NOT find JeMalloc (missing: JEMALLOC_LIBRARIES JEMALLOC_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/share/cmake-3.16/Modules/FindPackageHandleStandardArgs.cmake:393 (_FPHSA_FAILURE_MESSAGE)
  cmake/modules/FindJeMalloc.cmake:35 (find_package_handle_standard_args)
  wsgi/CMakeLists.txt:3 (find_package)


-- Configuring incomplete, errors occurred!

```

**Comment by mbnoimi** [comment]
At last I could build it with limited features using:
```
cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DPLUGIN_VIEW_CLEARSILVER=on -DPLUGIN_VIEW_GRANTLEE=on -DPLUGIN_VIEW_EMAIL=on
```

But I stuck once again with a new issue I'm not sure if it's related to bad building or there is something I missed!
I followed up the [wiki tutorial](https://github.com/cutelyst/cutelyst/wiki/Tutorial_02_CutelystBasics#create-a-cutelyst-project) but when I run the project nothing happened!!!
The system doesn't listen to port 3000 I tried to use another port but I get the same problem!
`cutelyst2` doesn't show anything error just warnings.
```
$ cutelyst2 -r --server --app-file src/libHello -- --chdir ..
Installing EPoll event loop
253345:253345 default[warning] QThread::setEventDispatcher: An event dispatcher has already been created for this thread
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 8
Changing directory to: ..
spawned WSGI master process (pid: 253345)
spawned WSGI worker (and the only) (pid: 253346, cores: 1)
Loading application: /mnt/Multimedia1/Downloads/HelloWeb/build/src/libHello.so
253346:253346 cutelyst.core[debug] Loaded translations for QLocale(German, Latin, Germany) from "/usr/share/cutelyst2/translations/cutelystcore.de.qm"
253346:253346 cutelyst.core[debug] Loaded translations for QLocale(English, Latin, United States) from "/usr/share/cutelyst2/translations/cutelystcore.en.qm"
Changing directory2 to: /mnt/Multimedia1/Downloads/HelloWeb
253346:253346 cutelyst.core[debug] Loaded Request Data Handlers:
.-----------------------------------.
| application/x-www-form-urlencoded |
| application/json                  |
| multipart/form-data               |
.-----------------------------------.
253346:253346 cutelyst.core[debug] Loaded dispatcher "Cutelyst::Dispatcher"
253346:253346 cutelyst.core[debug] Using engine "CWSGI::CWsgiEngine"
253346:253346 cutelyst.core[debug] Found home "/mnt/Multimedia1/Downloads/HelloWeb"
253346:253346 cutelyst.core[debug] Loaded components:
.-------+------------.
| Class | Type       |
.-------+------------.
| Root  | Controller |
.-------+------------.
253346:253346 cutelyst.dispatcher[debug] Loaded Private actions:
.--------------+-------+-------------.
| Private      | Class | Method      |
.--------------+-------+-------------.
| /defaultPage | Root  | defaultPage |
| /End         | Root  | End         |
| /index       | Root  | index       |
.--------------+-------+-------------.
253346:253346 cutelyst.dispatcher[debug] Loaded Path actions:
.------+--------------.
| Path | Private      |
.------+--------------.
| /... | /defaultPage |
| /    | /index       |
.------+--------------.
253346:253346 cutelyst.dispatcher[debug] 
253346:253346 cutelyst.core[info] cutelyst powered by Cutelyst 2.12.0, Qt 5.12.8.
253346:253346 cutelyst.core[debug] Default Application::postFork called on pid: 253346
```
I get same log in case I call:
```
$ cutelyst2 -p 3501 -r --server --app-file src/libHello -- --chdir ..
```
or even in case I called an absolute path:
```
$ cutelyst2 -r --server --app-file /mnt/Multimedia1/Downloads/Hello/build/src/libHello.so
```

OMG, I can't believe myself; I built a full REST web service using `django` within 8 hours although I've no experience with python (even I published it to the production) while `Cutelyst` took me 5 hours of failed attempts even I already know C++ & Qt!!!

**Comment by mbnoimi** [comment]
Finally I could see `Welcome to Cutelyst!` mesage but I reverted back to this commit https://github.com/cutelyst/cutelyst/commit/4add6975bf97af9f4c3428727e2fbae504991229. (master PR unstable)

Any way, this is the most painful test ever I with any framework used.
The project needs a real documentation the existing docs are very poor and lead the newcomers to leave the project at once.
I'll continue with Wiki tutorial hopeful to learn something from it.

**NOTE**: I'm unable to access [project's mailing list](https://groups.google.com/forum/#!forum/cutelyst)

**Comment by dantti** [comment]
Well you better start liking CMake as qmake days are counted.
The listen issue is a bug and is recommended to always use a stable tagged version since master is development, where I fixed SO_REUSE_PORT but broke the use without it.

Also you could use it prebuilt or follow more detailed instructions:
https://github.com/cutelyst/cutelyst/wiki/Installing-Cutelyst

**Comment by mbnoimi** [comment]
> Well you better start liking CMake as qmake days are counted.

Thanks @dantti I updated installing wiki page for needed Ubuntu packages and I wish -as a newcomer- to get a better docs about Cutelyst.

Personally I'll never use CMake until I forced to. 
Qt Creator is my preferred developing tool which currently supports qmake fine while creating any Qt project using cmake is not available using Qt Creator so I've to write `CMakeLists.txt` manually which is really a painful procedure.

**Comment by dantti** [comment]
>Qt Creator is my preferred developing tool which currently supports qmake fine while creating any Qt project using cmake is not available using Qt Creator so I've to write CMakeLists.txt manually which is really a painful procedure.

Sorry but this is plain wrong. QtCreator works just fine with CMake and Qt on Qt6 will only use CMake, all my coding is done with CMake and QtCreator since at least 10 years.

**Comment by dantti** [comment]
![image](https://user-images.githubusercontent.com/29507/87880367-8c6f4a00-c9c7-11ea-950e-68e18fb3635a.png)

**Comment by dantti** [comment]
Also Cutelyst can integrate with QtCreator:

![image](https://user-images.githubusercontent.com/29507/87880383-b163bd00-c9c7-11ea-8872-ed8be960e018.png)

**Comment by mbnoimi** [comment]
Yep, I already created Hello world demo using Cutelyst Qt Creator wizard
