### ISSUE TITLE
[Feature Request] Add submodules

### ISSUE THREAD

**Issue by mbnoimi** [cutelyst/cutelyst#267]
Hi,

This is my first time I use cutelyst, I read about it but practically I can't use it because it's hard to build it!
As I mentioned in issue #266 the steps mentioned in the wiki doesn't tell everything about cutelyst (which it suppose to be) so I suggest to add all the dependencies as git submodules thus the newcomers able to build cutelyst correctly whiteout wasting hours in just how to build cutelyst!

**Comment by dantti** [comment]
Sorry but every project has it's own dependencies and not all of them are controlled by me, adding them as submodules won't help you understand how CMake works, you could simply fire it's GUI and pick only the features you need with a few clicks.

https://github.com/cutelyst/cutelyst/wiki/Installing-Cutelyst
