### ISSUE TITLE
[Feature Request] Standalone Cutelyst Web Application

### ISSUE THREAD

**Issue by mbnoimi** [cutelyst/cutelyst#269]
May you please create a new Qt Creator wizard for Standalone Cutelyst Web Application?

I was looking for how to embed CWSGI in my web app for creating a standalone web app so I found https://github.com/cutelyst/cutelyst/issues/200#issuecomment-493061719 which encouraged me to ask you for this feature.

**Comment by dantti** [comment]
look at the cutelyst2 executable, it just needs to link to it and instantiate the Server class with the appropriate application pointer.

**Comment by dantti** [comment]
It's also counter productive to develop this way, because you won't be able to have auto-reloading.
Which is why I won't add an option to QtCreator, if you like please do a PR.

**Comment by mbnoimi** [comment]
I agree with you it's will missing "auto-reloading" but it's not "counter productive" because it's simply works as a desktop application; In this way the portability will be very high.

For example if I can create a portable web app using `linuxdeployqt` then sent the execute to my friend he simply run it without installing any dependencies of configure anything on his laptop.

**Comment by dantti** [comment]
Right but that doesn't depend on having the project created this way, you can just make it output two targets, use CPack for distribution or anything else, if you still want that please do a PR.
