### ISSUE TITLE
techempower plaintext benchmarks fail

### ISSUE THREAD

**Issue by devlo** [cutelyst/cutelyst#27]
As title states.

https://www.techempower.com/benchmarks/previews/round14/#section=data-r14&hw=ph&test=plaintext

**Comment by dantti** [comment]
This is a preview run, it fails due changes made on  test suite and they arr fixing it also that is the only test that I dont care. No user-agent do a pipelining flood...

**Comment by dantti** [comment]
Btw if you look at data table it fails it all tests, hopefuly preview 2 will have even better results as epoll tests failed..

**Comment by devlo** [comment]
> it also that is the only test that I dont care.

Can you elaborate on that? This is the only test that shows parsing/req-response overhead of the framework without other libs, so performance wise this is the most important test there.

**Comment by dantti** [comment]
To get good results there you must process a bunch of requests and send a big chunk with as many replies possible, if you process one connections reply then go the the other which is what webservers should do to not have a single user consume your site them you don't perform so well.
This is why I said I don't care much about this test, but if you look at the current results you will see that Cutelyst went well even on it.
