### ISSUE TITLE
Modify cutelyst2 compatibility 

### ISSUE THREAD

**Issue by mbnoimi** [cutelyst/cutelyst#270]
Hi,

I suggest to modify `cutelyst2` executable to be compatible with Qt Creator because by default Qt Creator creates build folder on same level of project's folder which means `cutelyst2` becomes unable to read `CMakeLists.txt` as I face [in this issue](https://github.com/ceciletti/example-qt-cutelyst-rest/issues/2#issuecomment-661226379)

**Comment by dantti** [comment]
While I understand the issue I don't have the time to fix it nor the will. I can accept a Pull Request though.
Thanks.
