### ISSUE TITLE
QSqlQuery

### ISSUE THREAD

**Issue by iastinf** [cutelyst/cutelyst#271]
How can I refer to the database connection related to any QSqlQuery query  
for example in 

https://github.com/cutelyst/pastelyst/blob/master/src/root.cpp

    QSqlQuery query = CPreparedSqlQueryThreadForDB(
                QStringLiteral("SELECT uuid, title, html, language, ip_address, user_agent, private, expires, created_at, password "
                               "FROM notes "
                               "WHERE uuid = :uuid"),
                QStringLiteral("pastelyst"));

and reopen the database in case the connection is broken?

**Comment by buschmann23** [comment]
Maybe [Cutelyst::Sql::databaseThread()](https://github.com/cutelyst/cutelyst/blob/1332c2d0642122526a745053b78cdce84d7a63f4/Cutelyst/Plugins/Utils/Sql/sql.h#L159) is what you are searching for.

**Comment by dantti** [comment]
If the connection is lost you will have to restart, that's a problem with QSql, if on postgres libpq will reopen the connection automatically, but the prepared statement will be invalid.
It's on my plans to write a QSql replacement that works async and fixes this use case...

**Comment by dantti** [comment]
ASql library is already available
