### ISSUE TITLE
Compressing JSON response

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#272]
Hello! I'd like to minimize JSON payload (using gzip or deflate) on the server-side (I have REST service, HTTP server is cutelyst-wsgi in local network). What would you advise?  How can I do it?

**Comment by dantti** [comment]
There is a plugin to serve static files compressed, you can use it to compress your data, this is not built in as requires an external lib, NGINX does this for me and for some projects where the clients are also Qt apps I use qCompress but it's output is not proper gzip.

**Comment by arietto** [comment]
OK, thank you!
