### ISSUE TITLE
Chained actions not flexible enough for REST APIs

### ISSUE THREAD

**Issue by davidchrista** [cutelyst/cutelyst#278]
I'm not sure if I just don't get it or if there is really something missing. I'm trying to develop a REST API with cutelyst.

I have a scenerio similiar to this:

- There are users
- every user has an ID
- every user can have multiple files

I want to do typical things:

`GET /users` - get a list of all users
`POST /users/<id>` - create a user with a certain ID
`GET /users/<id>/files` - get a list of all files owned by the user with the given ID
`POST /users/<id>/files/<filename>` - add a file with a certain name to user
...

So I have something like

```
C_ATTR(base, :Chained("/") :PathPart("api/v1") :CaptureArgs(0))
void base(Context *c);

C_ATTR(users, :Chained("base") :PathPart("users") :Args(0) :ActionClass(REST))
void users(Context *c);

C_ATTR(users_GET, :Private)
void users_GET(Context *c);

C_ATTR(users_id, :Chained("base") :PathPart("users") :CaptureArgs(1) :ActionClass(REST))
void users_id(Context *c, const QString &id);

// not working
C_ATTR(users_id_POST, :Private)
void users_id_POST(Context *c, const QString &id);

C_ATTR(users_id_files, :Chained("users_id") :PathPart("files") :Args(0) :ActionClass(REST))
void users_id_files(Context *c);

C_ATTR(users_id_files_GET, :Private)
void users_id_files_GET(Context *c);
```

But the` POST /users/<id>` does not work.

So I think the problem here is that the action with `:CaptureArgs(1)` only forwards the request to the next station in the chain, but it does not process the POST request.

I think it is quite usual for a REST API to have such a scenario, where object are identified by some variable path element (like <id>) and also have child objects (like files in my case).

Or is there something I'm missing?

**Comment by dantti** [comment]
Sorry for the late reply, pretty busy ATM, but yes, CaptureArgs() is not for ending a chain, I think you would need 2 user_id methods, or for the ending the chaing and another to continue it

**Comment by davidchrista** [comment]
Oh yes, of course!

So I added another REST action

```
C_ATTR(users_id_end, :Chained("base") :PathPart("users") :Args(1) :ActionClass(REST))
void users_id_end(Context *c, const QString &id);

C_ATTR(users_id_end_POST, :Private)
void users_id_end_POST(Context *c, const QString &id);
```

and, in fact, it works exactly as expected.

Thank you very much!

**Comment by dantti** [comment]
You're welcome
