### ISSUE TITLE
Handle multiple versions in a REST API

### ISSUE THREAD

**Issue by mardy** [cutelyst/cutelyst#279]
Hi there!
  Please bear with me, I'm totally new to Cutelyst (I just read the tutorial) and what I'm asking might not make any sense at all. :-)

So, I would like to create a versioned REST API. [This blog post](https://cutelyst.org/2018/05/17/creating-restful-applications-with-qt-and-cutelyst) shows how one can create an `ApiV1` controller with a method `user` inside it, so that it will be exposed as

    /api/v1/users

So far, so good. But in the end my API will be something like

    /api/v1/users
    /api/v1/books
    /api/v1/places
    ...

and I wouldn't like to handle all these endpoints in the same `ApiV1` object. I would like to have separate controllers `Users`, `Books`, `Places` and hook them up on top of the `ApiV1` controller. I tried creating a `Users` controller as a child of the `ApiV1` one, but it does not get registered:
```cpp
    auto v1 = new ApiV1(this);
    new Users(v1);
```
I *guess* I could use the `Chained` attribute (though, I have to admit, I still haven't grasped that concept), but then I would have the `Users` class hardcoded on top of the `ApiV1` namespace, and this (unless I'm missing something) will force me to do a lot of code duplication when I'll introduce the v2 API, because I would need to duplicate all the classes that have not changed. Whereas, I'd like to be able to do just something like this:

```cpp
    // Suppose that only the Books class has changed its API, and it's now Books2
    auto v2 = new ApiV2(this);
    new Users(v2); // same class as in v1, no code duplication
    new Books2(v2);
    new Places(v2);

    // Continue serving the v1 API as before
    auto v1 = new ApiV1(this);
    new Users(v1);
    new Books(v1);
    new Places(v1);
```

What is the recommended way in Cutelyst to achieve this?

**Comment by dantti** [comment]
It's not a good idea to subclass controlers depending on the case the actions might not be properly registered, it's possible but you must take some extra care.
What you need to do in this case is to create
ApiV1Users and in case of V2 you can either subclass it as ApiV2Users with some care with virtual actions, or just create an entirely new ApiV2Users, which might make more sense if you want legacy (v1) code still running.

**Comment by dantti** [comment]
You can also use chained indeed but it's usage is a bit more complex, so in simple cases I still prefer path.

**Comment by mardy** [comment]
Thanks @dantti! This is for the case where the API of the specific controller has not changes, so the subclassing idea should work fine. Feel free to close this issue, if you think that supporting controllers as children of other controllers is not something valuable. :-)

**Comment by dantti** [comment]
Actually as said subclassing is fine, it just doesn't work the way you might expect, but using C_NAMESPACE would probably fix your issue.
