### ISSUE TITLE
uriFor in Grantlee Template

### ISSUE THREAD

**Issue by simonaw** [cutelyst/cutelyst#28]
Hi!  This is not really an issue but more like a question of best practice.
In Catalyst or Flask/Jinja2 I can access the `uri_for` method directly for creating links for an action. Unfortunately in Grantlee there is no direct way of calling a function with a string parameter. E.g. `{{c.uriFor("authen/logout")}}` does not work.  The Parser is choking on the parameter `"Could not parse the remainder, (\"authen/logout\") from c.uriFor(\"authen/logout\")`

Right now, as a workaround, I created a two-level map so that I can access the routes via dot-lookup:
```C++
QVariantHash controllers;
for( Controller *controller: c->app()->controllers() ) {
  QVariantHash routes;
  for( Action *action: controller->actions() ) {
    routes[action->name()] = c->uriFor(action);
  }
  controllers[controller->objectName()] = routes;
}
c->setStash("controllers", controllers);
```

Having this routes map on my stash I can do something like this in the template:
```HTML
<p> <a href="{{controllers.Authen.logout}}">Logout</a> </p>
```
Sure, better have it in the init method to not have the map generated on every request.

Or is there another (easier) way to do this? -- Besides creating a Grantlee Filter that appearently accepts string parameters.

**Comment by dantti** [comment]
Hehe, this is something that I wanted to do a while ago, basically Grantlee stance is to no call object method, so I'm thinking in writting a custon filter like
`{{ c|uriFor "action name" }}`
Still I dunno if Grantlee exposes API for this, if you how please do a PR, otherwise I might look at this later this week.

**Comment by dantti** [comment]
For the moment I have been using relative urls..

**Comment by simonaw** [comment]
Yes, a filter was also my first thought. But since the Grantlee documentation is a little bit sparse on that topic I am still investigating. As far as I know one can only add new filters by loading Qt plugins that implement a certain interface.

**Comment by dantti** [comment]
It doesn't look so complex [http://www.grantlee.org/apidox/extension.html](http://www.grantlee.org/apidox/extension.html)

**Comment by simonaw** [comment]
Yeah, I know, I know ;) I already went through this but got stuck at the cmake macros. But I am on it...

**Comment by simonaw** [comment]
OK, I don't know what I am doing wrong. I've been trying to build a simple filter that just prefixes a variable with a static string:

myfilter.hpp:
```c++
#ifndef __myfilter_hpp                                                      
#define __myfilter_hpp                                                      
                                                                            
#include <grantlee/filter.h>                                                
#include <grantlee/safestring.h>                                            
#include <grantlee/util.h>                                                  
                                                                            
class MyFilter : public Grantlee::Filter {                                  
  QVariant doFilter( const QVariant &input, const QVariant &arg,            
      bool autoescape) const;                                               
                                                                            
  bool isSafe() const { return true; }                                      
};                                                                          
                                                                            
#endif
```
myfilter.cpp:
```c++
#include "myfilter.hpp"                                                     
                                                                            
QVariant MyFilter::doFilter(                                                
    const QVariant &input,                                                  
    const QVariant &arg = QVariant(),                                       
    bool autoescape = false                                                 
  ) const {                                                                
                                                                           
  Grantlee::SafeString str = Grantlee::getSafeString(input);               
  return "MyFilter Says: " + str + "//";                                   
}
```
mylib.hpp:
```c++
#ifndef __mylib_hpp                                                         
#define __mylib_hpp                                                         
                                                                            
#include <QDebug>                                                           
#include <grantlee/taglibraryinterface.h>                                   
                                                                            
#include "myfilter.hpp"                                                     
                                                                            
#define MyFilterLib_iid "de.chronowerks.qtplugins.MyFilterPlugin"           
                                                                            
class MyFilterLib : public QObject, public Grantlee::TagLibraryInterface { 
  Q_OBJECT                                                                  
  Q_PLUGIN_METADATA(IID "de.chronowerks.qtplugins.MyFilterPlugin" FILE "mylib.json")
  Q_INTERFACES(Grantlee::TagLibraryInterface)                               
                                                                            
  public:                                                                   
    MyFilterLib( QObject *parent = 0 ) : QObject(parent) {                  
      m_filters.insert("myfilter", new MyFilter());                         
    }                                                                       
                                                                            
    QHash<QString, Grantlee::Filter*> filters(const QString &name = QString()) {
      Q_UNUSED(name);                                                       
      return m_filters;                                                     
    }                                                                       
};                                                                          
                                                                            
#endif
```
CMakeLists.txt:
```make
cmake_minimum_required(VERSION 3.7)                                         
project(myfilterlib)                                                        
                                                                            
add_library(myfilterlib MODULE                                              
  myfilter.cpp                                                              
  myfilter.hpp                                                              
  mylib.hpp                                                                 
)                                                                           
                                                                            
find_package(Qt5 COMPONENTS Core REQUIRED)                                  
find_package(Grantlee5 REQUIRED)                                           
                                                                            
set_property(TARGET myfilterlib PROPERTY EXPORT_NAME myfilterlib)          
                                                                            
target_link_libraries(myfilterlib Grantlee5::Templates)                     
grantlee_adjust_plugin_name(myfilterlib)
```

Everything seems fine to me.  The resulting library lib is located in the build directory under `grantlee/5.1/myfilterlib.so` and builds without error.

In a very simple test program I tried to add the library:
```c++
Grantlee::Engine *e = new Grantlee::Engine();                             
e->addPluginPath("plugins");                                              
e->addDefaultLibrary("myfilterlib");
```

but to no avail:

```
grantlee.template: "Plugin library 'myfilterlib' not found."
```

Even though `strace` confirmed it's been opened:

```shell
> grep myfilter trace.txt
stat("[...]plugins/grantlee/5.1/myfilterlib.so", {st_mode=S_IFREG|0755, st_size=19256, ...}) = 0
...
open("[...]plugins/grantlee/5.1/myfilterlib.so", O_RDONLY|O_CLOEXEC) = 4
```

But I can't see anything wrong with the interface implementation.
Do you have any idea?

**Comment by dantti** [comment]
Ok, I finally managed to setup this, you can look at grantlee_uri_for branch, but it seems
that a Filter is not good for uri_for since you can only pass one argument, and requires you to put the Contex variable.

A tag on the other hand could probably be used like:
`{% c_uri_for "action" "query" %}`
which since has access to the Parser can get the Context automatically.

Grantlee is a project I'm trying to avoid forking but the maintainer doesn't have time to even accept PR, and doesn't seem to be willing to add me as a contributor... I'd like to add an API to not require creating a plugin which has no use outside Cutelyst...

**Comment by simonaw** [comment]
> I'd like to add an API to not require creating a plugin which has no use outside Cutelyst...

Exactly. That's what I thought.
Maybe there is a possibility to fill `c->config()` with a hash of the controllers (like in the first posting) so that something like `{{c.config.urlfor.Authen.logout}}` would be possible...

**Comment by dantti** [comment]
it's too much work to build such a hash, not to mention it won't work for chained, I think a tag will be fine.

**Comment by simonaw** [comment]
OK

**Comment by dantti** [comment]
I have updated the branch with a tag now, please try it, I guess c_uri_for_action will also be needed, and some euristics in parsing arguments.

**Comment by dantti** [comment]
And there you go :D

**Comment by simonaw** [comment]
Nice! :D Works like a charme!
