### ISSUE TITLE
Using the Session class in a REST application

### ISSUE THREAD

**Issue by mardy** [cutelyst/cutelyst#286]
Hi, I'm developing a server which should offer a REST API, most of which should be available only after the user has been authenticated. I was playing with the idea of using the Session class to store the authentication info, like this:

1. When the user authenticates, I would repeatedly call `Session::setValue()` to store the information about the authenticated user (like his ID)
2. Return the `Session::id()` to the client, аs an authentication token
3. In the following calls, the client will set the ID we returned in the X-Authentication-Token header
4. I read the token in the server from the header and set it as the session ID for the context, so that the proper session data gets loaded

I'm not sure about point 4, because looking at the API I cannot find an obvious way to achieve what I need. Looking at the source code, it would appear that I could do something like:

```cpp
c->setStash("_c_session_id", authenticationToken);
QString userId = Session::value(c, "userId");
// ...and get any other useful info from the session...
```

But indeed, the `_c_session_id` is a string defined in the cpp file, which is supposed to be private. So, I guess there must be some better way to achieve my goal, but I cannot find the right API for it. Any hints? :-)

**Comment by mardy** [comment]
After spending some more time on Cutelyst source code, I convinced myself that there isn't a better way to do this. For the record, you can see the solution I've implemented [here](https://gitlab.com/studentario/studentario-server/-/commit/7cb32fb11a2d081bbe4a181ca51e58a872724630).

I would like to propose some changes to the Session class to make it more friendly for REST APIs:
1. Add a `static void Session::setSendCookie(bool sendCookie)` method to decide whether Cutelyst should send the session as a cookie, as it currently does (the default value should be `true`). People implementing REST APIs might want to set this to `false`. I wonder if we can do without the `Context` parameter, or if it needs to be there.
2. Add a way to load the session even if cookies are not used. Possible implementations:
   1. Add a `static void Session::loadSession(Context *c, const QString &id)`, which loads the session
   2. Implicitly load the session if a certain header is found. The header name could be configurable with an additional method, like `void Session::setHeaderName(const QString &headerName)`.

If you think that some of these changes are desirable, please let me know: I can try implementing them.

**Comment by dantti** [comment]
Take a look at https://metacpan.org/pod/Catalyst::Plugin::Session#RECOMENDED-BACKENDS
They said the sane way to store the session was by using cookies, that's likely because some bearer might end up being updated and it would match a session key anymore.
I've used JWT but then I usually store the session data there, this way I avoid a memcache roundtrip for example..

I'm closing this as you have already worked around any limitation, might try creating a MR but I'm not so sure I get the benefits
