### ISSUE TITLE
Win10 : make: *** No targets specified and no makefile found. Stop.

### ISSUE THREAD

**Issue by x9valentin** [cutelyst/cutelyst#287]
Hello,
i would like to use cutelyst for a university projet (french student), in order to have my dynamic website in a usb key :).
I'm happy because i have a working cutelyst on my linux hard disk ! But, for my project, i have to give a win version ^^.
In order to test my Windows installation, i am following command line of [Tutorial_02_CutelystBasics](https://github.com/cutelyst/cutelyst/wiki/Tutorial_02_CutelystBasics), but i work on Windows.
After doing `cutelyst2 --create-app Hello`, `cd Hello/build;cmake ..` when i try "make", he unfortunately say that i don't have `makefile` present into my Hello/build directory.

```
x9val@DESKTOP-5TLID2D MINGW64 ~/epita/ps2/Hello2/build
$ cmake ..
-- Building for: Visual Studio 16 2019
-- The C compiler identification is MSVC 19.25.28614.0
-- The CXX compiler identification is MSVC 19.25.28614.0
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - skipped
-- Detecting C compile features
-- Detecting C compile features - done
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.25.28610/bin/Hostx64/x64/cl.exe - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: C:/Users/x9val/epita/ps2/Hello2/build

x9val@DESKTOP-5TLID2D MINGW64 ~/epita/ps2/Hello2/build
$ ls
ALL_BUILD.vcxproj          CMakeFiles/         ZERO_CHECK.vcxproj.filters
ALL_BUILD.vcxproj.filters  Hello2.sln          cmake_install.cmake
CMakeCache.txt             ZERO_CHECK.vcxproj  src/

x9val@DESKTOP-5TLID2D MINGW64 ~/epita/ps2/Hello2/build
$ make
bash: make: command not found

x9val@DESKTOP-5TLID2D MINGW64 ~/epita/ps2/Hello2/build
$ C:/MinGW/bin/mingw32-make.exe
make: *** No targets specified and no makefile found.  Stop.

x9val@DESKTOP-5TLID2D MINGW64 ~/epita/ps2/Hello2/build
$ C:/MinGW/msys/1.0/bin/make.exe
make: *** No targets specified and no makefile found.  Stop.
```

This is my Windows path :
`%USERPROFILE%\AppData\Local\Microsoft\WindowsApps;%JetBrains Rider%;C:\Program Files\CMake\bin;C:\usr\bin;C:\Qt\5.9.9\msvc2015\bin;C:\Qt\5.9.9\msvc2017_64\bin;C:\Qt\5.9.9\msvc2015_64\bin;C:\Qt\5.9.9\mingw53_32\bin;`

But what i've failed to have no present makefile in my build dir ?
Thank you and have a good year !

**Comment by x9valentin** [comment]
After following this https://stackoverflow.com/questions/55583232/cmake-does-not-create-make-file
my project seems to be working, i'm so happy :))
That was just because (on my computer maybe i'm the only one) : `make ` needed to be converted to something like ->`cmake --build .` and `cmake --build . --config Release`
So here i'm on the deployment of cutelyst+ mydll :)))
Thanks to all !
Merci à tous !

**Comment by dantti** [comment]
cmake --build is actually the safer way to build because it will issue the proper make tool (be it gnu-make, ninja...).
On Windows a perhaps easier way to get Cutelyst built is with VCPKG
