### ISSUE TITLE
Development server timing

### ISSUE THREAD

**Issue by petoknm** [cutelyst/cutelyst#29]
I am having weird timing issue with the development server. For some reason it is off by a factor of exactly 1000... For example request calculating something that takes 8.5s realtime shows up as only 0.008494s in the server output. 
```918:918 cutelyst.request[debug] "GET" request for "fibonacci/1000000" from "::1"
918:918 cutelyst.dispatcher[debug] Path is "fibonacci"
918:918 cutelyst.dispatcher[debug] Arguments are "1000000"
918:918 cutelyst.stats[debug] Response Code: 200; Content-Type: application/json; Content-Length: 208999
918:918 cutelyst.stats[info] Request took: 0.008500s (117.647/s)
.------------------+-----------.
| Action           | Time      |
.------------------+-----------.
| /fibonacci/index | 0.008494s |
| /End             | 0.000000s |
.------------------+-----------.
```
![screenshot_20170404_215046](https://cloud.githubusercontent.com/assets/5087675/24675830/d8a376ee-1980-11e7-9b8b-17d67bc999aa.png)
I am using cutelyst 1.6.0 that was compiled from master during the last couple days. It would be nice to have precise timing on the development server.
Thank you.

**Comment by dantti** [comment]
Hopefuly this fixes the issue :)

**Comment by petoknm** [comment]
wow... such fast... much thanks :)

**Comment by dantti** [comment]
Hi, I'm not sure if it was you that noted on IRC that apache-bench (ab) wasn't working with cutelyst, if it was you it's fixed now. Thanks.

**Comment by petoknm** [comment]
yeah that was me. im going to check it out right now. thanks for the fix.

**Comment by petoknm** [comment]
is the master not working? because previously i was getting
```
19632:19632 cutelyst.core[info] cutelyst powered by Cutelyst 1.6.0, Qt 5.8.0.
19632:19632 cutelyst.core[debug] Default Application::postFork called on pid: 19632
```
but now im getting only
```
23221:23221 cutelyst.core[info] cutelyst powered by Cutelyst 1.6.0, Qt 5.8.0.
```
and the server does not work

**Comment by dantti** [comment]
hmm it was working for me, what command line?

**Comment by petoknm** [comment]
just the barebone `cutelyst -r --server --app-file $APP_FILE`

**Comment by dantti** [comment]
ok, should be fixed now, it was an issue of --laze which is implicity with -r

**Comment by petoknm** [comment]
apache-bench seems to work fine now. good job 👍

**Comment by dantti** [comment]
Great thanks :)
