### ISSUE TITLE
Is websocket Context::destroyed() signal available?

### ISSUE THREAD

**Issue by zhmc** [cutelyst/cutelyst#290]
I am using the cutelyst websocket to implement a real-time game server. I am worring about the deconstruction of a websocket connection, because of the reconnecting in the mobile phone network shifting.I have read the source code and found that 

[https://github.com/cutelyst/cutelyst/blob/47e9a206c9e2acca54bf7d05ecdc172c6fd463ac/Cutelyst/response.h#L376](response.h)

373  you need to track when the connection was closed, the proper way is to rely on
374   Context::destroyed() signal.
375 
376  bool webSocketClose(quint16 code = Response::CloseCodeNormal, const QString &reason = QString());

But in current source code base, there is no such signal in Context Class.
[https://github.com/cutelyst/cutelyst/blob/master/Cutelyst/context.h](url)
So how to manage the lifecircle of a websocket connection? Any help would be appreciated.

**Comment by dantti** [comment]
destroyed() signal is from QObject.

**Comment by zhmc** [comment]
> destroyed() signal is from QObject.

Thanks for the answer.
Currently, I matained a map like QMap<user_id, context*>.So when the server has recieved a client reconnecting request with a user_id already in the map, how can the server destroy the old context?

**Comment by zhmc** [comment]
changed to new topic: [How to close a websocket in cutelyst server without using the webSocketClose() ? #291](https://github.com/cutelyst/cutelyst/issues/291)
