### ISSUE TITLE
How to close a websocket in cutelyst server without using the webSocketClose() ?

### ISSUE THREAD

**Issue by zhmc** [cutelyst/cutelyst#291]
I am using the cutelyst websocket to implement a real-time game server.  Because of the scenario of reconnecting in the mobile phone network shifting, I use "sending a message every 5 second in chrome browser" to keep alive. When I haven't receive any  message from the client for 5 seconds, I just do this:
**context->deleteLater();**
Then I  tested that websocket client in browser, no message can be sended.But after clicking the disconnect button , the server crashed.
Maybe there is a better way to close a websocket connection? Any help would be appreciated.

**Comment by dantti** [comment]
NEVER do this -> context->deleteLater();

you should use websocket PING command **Response->websocketPing()** your browser, and websocketClose() if you want to close.
