### ISSUE TITLE
Fails to find project on Windows

### ISSUE THREAD

**Issue by Plaristote** [cutelyst/cutelyst#296]
Hey,
I've been developing an app on Linux, and I'm trying to have it run on Windows now. I managed to build both Cutelyst and my application, but whenever I try to use Cutelyst in the same fashion I would do on Linux, I get the following output:

    $> cutelyst2 -p 3000 -r --server --app-file ../build-mercompta-Desktop-Debug/src/server/MercaBack -- --chdir ../mercompta
    Error: failed to find project
    Cutelyst-WSGI terminated

Using `MercaBack.dll` or `MercaBack.lib` will also fail.

I've been using Qt 5.12, MSVC 2017 and Cutelyst 2.15.
I'll look into it myself, but it might take me a lot of time before I'm familiar enough with the source to figure out what's happening, so I'm leaving this here, just in case, and I'll come back with more details once I've investigated how Cutelyst loads those plugins.

--
EDIT:
First, I noticed that the process looks for a CMakeLists file through Helper::findProjectDir, seemingly ignoring the --app-file option... if it finds a CMakeLists file, it then looks for any file matching the mimetype `application/x-sharedlib`. However, I noticed that my built files, which are a dll and a lib, respectively have the mimetypes `application/x-msdos-executable` and `application/x-archive`. When I checked over the linux side, the built file over there has the expected mimetype indeed.

I'm suspecting the application file auto-detect feature might not work on Windows then, since it seems shared librairies on windows have a different mimetype. But I wasn't trying to use auto-detect anway, so I'll carry on and see what else is there.

--
EDIT2:
Alright, I've got it. The problem lies between lines 512 to 516 in `cmd/main.cpp`. As I've said before, project auto-detect probably won't work on Windows, due to the different mimetypes for shared libraries. Plus, it only works if the build directory is somewhere below the folder containing the project's CMakeLists file (which isn't the default behavior for QtCreator, so it probably won't be so uncommon to have people struggling with that).

**Comment by dantti** [comment]
I recommend just using cutelyst-wsgi, cutelyst executable is meant for newcommers and bootstraping the project, as you said it works on linux and is what I've tested, if you want please do a PR for a fix to it.
