### ISSUE TITLE
Deploying in a strict environment

### ISSUE THREAD

**Issue by mardy** [cutelyst/cutelyst#298]
Hi! I'm trying to deploy my cutelyst REST server at my hosting provider machine (Ubuntu 18.04 running in a Docker container), and I'm having some issues.

The server is running Apache + nginx, but I do not have any control over their configuration and I cannot open TCP ports myself. The way that sites are supposed to run on this server is via [Passenger](https://www.phusionpassenger.com/library/dev/), which seems to be very simple to use but, alas, only supports Ruby, Python, Node.js and Meteor. I'm not an expert of web application deployments, so if I might be missing some options, please suggest.

The `mod_proxy` module is installed, along with `mod_proxy_http` (but not `mod_proxy_fcgi`), but I cannot setup the `ProxyPass` directive since it's not allowed in `.htaccess` files.

So, I'm quite stuck. Is it possible, maybe, to create a small python wrapper that would be run as a WSGI and internally spawn `cutelyst-wsgi2`, and forward the socket to it? Or would this have a horrible performance?

**Comment by dantti** [comment]
hi, sorry for the delay.
Do you have ssh access into the docker? with root user?
Well cutelyst applications are regular executables, if you can build locally on a machine running 18.04 you can send it to your server, you just need to open a tcp local port or an Unix local socket, and apache or nginx proxy the connections to the app.

**Comment by mardy** [comment]
Hi Daniel, thanks for your reply. No, unfortunately I don't have root access to docker, and I'm not allowed to open any TCP port for listening. My provider confirmed that they don't support FastCGI, and given how Passenger is limited to Python, I'm afraid my only option is to acquire a more expensive plan.

But what confused me is the "WSGI" name in the cutelyst binary: WSGI is a way to start python applications only, whereas it would look like cutelyst-wsgi2 is in fact a FastCGI application. I thought that maybe the name was chosen because one could write a python WSGI application that would start the Cutelyst app as a bridge, but it doesn't look like it's possible.

**Comment by dantti** [comment]
Web Server Gateway Interface although coined by Python for Python frameworks is just an interface for web servers, Apache and the like, if you look at uWSGI it is written in C, has support for HTTP/FastCGI/uWSGI protocols which Cutelyst-wsgi only doesn't support the later, but the 2 previous ones we are much faster.
So it's not only a FastCGI app, it also has HTTP2, websockets and HTTP, I'm actually thinking in renaming it to just server in Cutelyst 3 as this WSGI name was inherited from uWSGI and doen't make much sense imo.
That said it's odd that you can't choose to run uWSGI there for example.
IMO there are many cheap data centers that can provide what you need for probably the same amount of money.

**Comment by mardy** [comment]
Yes, no worries, I will migrate to another plan, they are not expensive at all anyway :-)

I'm closing this, as I don't think there's anything you should be doing here (other than, maybe, renaming the executable :-) ).
