### ISSUE TITLE
Large response handling

### ISSUE THREAD

**Issue by petoknm** [cutelyst/cutelyst#30]
Hi,
I am experiencing some issues with sending large responses. It also behaves a bit inconsistently (sometimes ok sometimes not). 
My request handler looks like this
```
c->response()->body() = QByteArray("abcd").repeated(1024*1024);
```
and it is not able to send the data and I don't know why
```
curl $URL
curl: (52) Empty reply from server
```
and I also tried wget
```
wget $URL
--2017-04-09 10:48:12--  URL
Resolving localhost... ::1, 127.0.0.1
Connecting to localhost|::1|:3000... connected.
HTTP request sent, awaiting response... 200 OK
Length: 0 [text/html]
Saving to: ‘$FILE’

$FILE                                                  [ <=>                                                                                                                                     ]       0  --.-KB/s    in 0s      

2017-04-09 10:48:12 (0.00 B/s) - ‘$FILE’ saved [0/0]
```
and that's just a 4MiB response. I tried it with 4KiB response and it is fine. I was also able to send responses 10s of MBs in size but not consistently. Maybe it's something I'm doing wrong with QByteArray. Is there any extra restriction on body size of responses? For large responses it would maybe be easier to implement some stream interface. Do you experience the same issues/Can you replicate the behaviour?

Thanks!

**Comment by dantti** [comment]
I'll take a look.
About a stream interface you can use the Response class which is a QIODevice interface, so issuing ->write() will send headers and start sending data.

**Comment by dantti** [comment]
BTW I might deprecate body() member, since setBody() can also set content-length.
So I'm not sure If I should get rid of this method that is Catalyst's legacy...
