### ISSUE TITLE
Overriding headers for static files

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#303]
Hello! I use Qt Web Assembly application under Cutelyst HTTP server. I've noticed that it used `"Cache-Control: public"` pair. I'd like to override this value. Is it possible to do it  via some `"postDispatch()"` style method?
At the moment, when I update heavy wasm file (17 Mb) on the server side, Firefox browser is lazy for refetching it during tab reload.
BTW, what value for `Cache-Control` is recommended for heavy *.wasm files?

**Comment by dantti** [comment]
sorry, forgot to reply your question, so what do you use for serving the file? StaticSimple, --static-map, setting a QFile* on response?
I'm not sure what cache-control is best for you, it should certainly have etags to know if the content changed but I'm don't recall Cache-Control RFC

**Comment by arietto** [comment]
Hello! Never mind, I use `static-map` setting in the INI file. At the moment, I use locally patched version of cutelyst-wsgi server, which determines file extension before assigning default `Cache-Control: public`. If it is `*.js` or `*.wasm`, the cache is switched off (which is fine just for my project). I just wanted to know about more elegant solution (if some "interceptor" existed).

**Comment by dantti** [comment]
for static-map there's no way to intercept, it was just borrowed from uWSGI and it doesn't reach your Cutelyst::Application, it's rather limited as it's mostly about getting dev files served as usually you run it behind nginx, but you can achieve a reload way with /url/to/file?somerandomvalue which your browser will just think it's an entirely new file

**Comment by arietto** [comment]
OK, thanks
