### ISSUE TITLE
Can't find CWSGI

### ISSUE THREAD

**Issue by Bemte** [cutelyst/cutelyst#306]
Hi guys,

I just started with Cutelyst and hope you can help me.
I followed the tutorial to get the Hello-App to run (https://github.com/cutelyst/cutelyst/wiki/Tutorial_02_CutelystBasics). Next, I looked for ways to start the server from within my program, as that is the goal. Unfortunately I wasn't able to find information on that in the tutorial, but I found this question: https://github.com/cutelyst/cutelyst/issues/181
The CWSGI seems to do more or less what I want, so I tried using it. However, there is no such file to include in my Cutelyst folder.
Do I need to install it somehow? Where do I find it in the include-folder?

Also is this the right way to launch an API-server from within a bigger C++-program, without the use of the external program cutelyst2 (now cutelyst3) mentioned in the tutorial?

**Comment by dantti** [comment]
Cutelyst v3 (master - not release) CWSGI is now Server class, and yes, with it you can have your app on the same bigger C++ program. But has a few issues (that can be addressed)
