### ISSUE TITLE
ParamsMultiMap’ {aka ‘class QMultiMap<QString, QString>’} has no member named ‘insertMulti’

### ISSUE THREAD

**Issue by MikePooh** [cutelyst/cutelyst#311]
I was trying to rebuild Cutelyst with Qt 5.15.2 and got following error

Cutelyst/Plugins/View/Grantlee/urifor.cpp:122: error: ‘Cutelyst::ParamsMultiMap’ {aka ‘class QMultiMap<QString, QString>’} has no member named ‘insertMulti’

As I found in documentation insertMulti is removed now from QMultiMap class in Qt 5.15. However it was present in Qt 5.12.

**Comment by dantti** [comment]
insertMulti is deprecated in QMap, and I think was never available in QMultiMap (not sure), on v3 ParamsMultiMap is actually a MultiMap, I fixed this for Cutelee plugin but since I'm not using Grantlee anymore I forgot about it, let me fix it too.

**Comment by MikePooh** [comment]
QMultiMap inherits from QMap, so it was available.

**Comment by dantti** [comment]
hmm but Cutelyst v2 ParamsMultiMap is a QMap, in v3 it is a QMultiMap as they are separate types in Qt6

**Comment by dantti** [comment]
https://doc.qt.io/qt-5/qmap-obsolete.html
As you can see they are not removed otherwise ABI would break, they are obsolete to help with porting to Qt6

**Comment by dantti** [comment]
oh and I recommend you using Cutelee instead btw, as it has several fixes that take years to get in Grantlee

**Comment by MikePooh** [comment]
I will try Cutelee, thank you.

But If insertMulti still present as member function though obsolete, why I am getting compile error?

**Comment by dantti** [comment]
I think you shouldn't get that as a compiler error anymore as I lowered the QT_DISABLE_DEPRECATED to 5.14 iirc, maybe a git pull will make it ignore that.
