### ISSUE TITLE
Parallel processing of requests

### ISSUE THREAD

**Issue by cppusta** [cutelyst/cutelyst#315]
I am new here and recently I am dealing with Cutelyst. My englich is not gut ;). I have studied the tutorials and implemented.
When I have many requests and the processing of one takes 2 seconds (waiting for response from embedded devices), the other requests wait. Is there a possibility in Cutelyst to process the requests in parallel. A simple example would be very helpful.

**Comment by dantti** [comment]
Yes, you can either spawn more process or threads but even better is to not block the procress/thread when asking for date from the device.

**Comment by cppusta** [comment]
Sorry, the library to the device is already there and the functions blocked.
You mean:
`class Device : public Controller {
C_ATTR(list, :Local)
void info(Context* c);
}`
`void Device::info(Context* c)
{
// Pseudocode
QThread t = new QThread;
t->setContext(c);
t->start();
}`
Where can I create the threads?
Is the CWSGI server configured so that each request is processed by a thread?

**Comment by dantti** [comment]
cutelyst-wsgi or cutelystd have --process and --threads. You can also create your own QThreads and use Async class to wait for the response to finish the request.

**Comment by cppusta** [comment]
Thank you. I tested it with cutelyst-wsgi and it worked. cutelyst-wsgi2 has the --thread and --process option but cutelyst2 does not. What is the difference between the programs? Thanks again.

**Comment by dantti** [comment]
cutelyst2 has all the cutelyst-wsgi2 options, but only after --, it's a developer tool aiming at easing bootstraping new projects once you get used it's better use cutelyst-wsgi or cutelystd (v3)

**Comment by dantti** [comment]
It's important to notice that --thread or --process it still might block request, that eventually didn't need to block, such as a login page, if you get more connections than threads/process which is why creating your QThreads and using ASync is a better option so non blocking requests can always be served.

**Comment by cppusta** [comment]
I try like this, as in tutorials.
$ cutelyst2 -r --server --threads 3 --app-file build/src/libMyApp -- --chdir ..
Unbekannte Option 'threads'.

**Comment by dantti** [comment]
Which tutorial?
as I said must be after --
`$ cutelyst2 -r --server --app-file build/src/libMyApp --  --threads 3 --chdir ..`

**Comment by cppusta** [comment]
Which tutorial? -> Tutorial_02_CutelystBasics
Sorry, now i understand :)). Thanks.
What is --, where can i learn about it?

**Comment by dantti** [comment]
https://unix.stackexchange.com/questions/11376/what-does-double-dash-mean

**Comment by dantti** [comment]
Ok, tutorial is fine I thought you copied the line with --threads before --
