### ISSUE TITLE
Using SSL with elliptic curve?

### ISSUE THREAD

**Issue by cppusta** [cutelyst/cutelyst#321]
I found description using SSL in #50 "How can i use cutelyst with SSL?".

I would like to use SSl with certificate with elliptic curve (EC).
I run app with --hs1 0.0.0.0:8443,server.crt,server.key
but app terminate with error: "Failed to parse SSL private key"

@louwers say: Just look at the documentation.
I show in source code.
In https://github.com/cutelyst/cutelyst/blob/master/server/tcpserverbalancer.cpp:121

```
QSslKey key(&keyFile, QSsl::Rsa);
    if (key.isNull()) {
    std::cerr << "Failed to parse SSL private key" << std::endl;
    return false;
}
```
In QSslKey constructor is patameter QSsl::Rsa embeded.
Can I use SSL with EC -> QSsl:ec?

**Comment by dantti** [comment]
Well I dunno what that change for browsers/clients, but if changing QSsl::Rsa to QSsl::Ec is enough then the cmd line could have a last optional parameter like:
`--hs1 0.0.0.0:8443,server.crt,server.key,**ec**`

**Comment by cppusta** [comment]
Yes, for the clients it doesn't matter, but for the server. Because the certificate with EC is there and I have to use it.
As optional last parameter is ok. Would you add it in source code?
