### ISSUE TITLE
Error: could not load translations

### ISSUE THREAD

**Issue by neuroassault** [cutelyst/cutelyst#328]
Running `cutelyst3-qt5` prints the above error message to stdout.

Responsible for this is the line https://github.com/cutelyst/cutelyst/blob/657893c9758d75b3a92c3dfdc258af60e2f616ae/cmd/main.cpp#L423

`QLatin1String("qt_") % QLocale::system().name()` results on my machine in `qt_en_US`. There are nowhere files prefixed with that string.

Cutelyst's translation files are installed to share/cutelyst3 and look like this:

```
share
│   ├── cutelyst3
│   │   └── translations
│   │       ├── cutelystcmd.de.qm
│   │       ├── cutelystcmd.en.qm
│   │       ├── cutelystcore.de.qm
│   │       ├── cutelystcore.en.qm
│   │       ├── cutelystwsgi.de.qm
│   │       ├── cutelystwsgi.en.qm
│   │       ├── plugin_csrfprotection.de.qm
│   │       ├── plugin_csrfprotection.en.qm
│   │       ├── plugin_memcached.de.qm
│   │       ├── plugin_memcached.en.qm
│   │       ├── plugin_utils_validator.de.qm
│   │       ├── plugin_utils_validator.en.qm
│   │       ├── plugin_view_cutelee.de.qm
│   │       ├── plugin_view_cutelee.en.qm
│   │       ├── plugin_view_grantlee.de.qm
│   │       └── plugin_view_grantlee.en.qm
```
Do I miss something?

**Comment by dantti** [comment]
this has given me this error while loading the translations since I think @buschmann23  added them, but since I don't rely on them never tried to fix, feel free to do a PR to fix it :)

**Comment by neuroassault** [comment]
Yea, maybe @buschmann23  can just change line 423 to:
```
bool loadedTr = qtTranslator.load(QLatin1String("cutelystcmd.") % QLocale::system().name(),
```
This solved it for me -- given I installed the files to `/usr/share/qt/translations/cutelystcmd.de_DE.qm` But I want to understand what he had in mind with the `qt_` prefix. Maybe he relied on the package manager to install them that way?

**Comment by neuroassault** [comment]
Please ignore this issue.
Everything works flawlessly -- given you have the Qt package translation files installed.

On most systems there should exist a package called something like `qt6-translations` in your package manager. You guessed it, that is where the `qt_{locale}`-prefixed qm files are coming from.
