### ISSUE TITLE
Query Parameters in input order

### ISSUE THREAD

**Issue by cppusta** [cutelyst/cutelyst#332]
Hi und happy new year,
I get the query parameters with the method queryParameters() and it returns a multimap. When I iterate over map, I get the query parameters in alphabetical order. But I want them input order. I have searched, unfortunately not found. Any idea?

**Comment by dantti** [comment]
Well input order is not important in most web frameworks, but if you want you can parse them manually using c->request()->uri()->query().
QUrlQuery can parse that but I don't know if it returns them in order.

**Comment by dantti** [comment]
the only order that is guaranteed is the values() order ie  foo=1&foo=2&foo=3 will make values("foo") return ("1", "2", "3").
