### ISSUE TITLE
Please make it avalable for PyQt

### ISSUE THREAD

**Issue by Advik-B** [cutelyst/cutelyst#335]

**Comment by dantti** [comment]
I can possibly accept contributions but since I don't like python it's high unlikely for me to do it, besides py world has already several other options.

**Comment by Advik-B** [comment]
aww, please @dantti you can use cython if you want but... at least try.

**Comment by Advik-B** [comment]
besides, pyqt was written in c++

**Comment by Advik-B** [comment]
I choose to make an issue because this is the only GOOD qt-to-web addon

**Comment by dantti** [comment]
Sorry, but I don't have time to work on this, nor am familiar with it
