### ISSUE TITLE
How can i use Upload Class?

### ISSUE THREAD

**Issue by phantomxe** [cutelyst/cutelyst#35]
I need some document about "Upload Class".

**Comment by dantti** [comment]
Upload is a QIODevice: [Upload](http://api.cutelyst.org/classCutelyst_1_1Upload.html)
you need to send a POST with "multipart/form-data" content-type, and access it
via c->request()->uploads();
It has a save() method to save the upload to disk.

**Comment by phantomxe** [comment]
`
QVector<Upload> _up = c->request()->uploads();
for(int i = 0; i < _up.size(); i++)
{
  __up.at(i)->save();
}
`
Like this? @dantti

**Comment by dantti** [comment]
There are many ways, this one will work. you can also use some C++11 goodies like:

    const auto uploads = c->request->uploads();
    for (Upload *upload : uploads) {
        upload->save("/tmp/" + upload->filename());
    }

Or getting an specific upload:

    auto imageUpload = c->request->upload("image-field");

**Comment by phantomxe** [comment]
thanks @dantti

**Comment by phantomxe** [comment]
I got this error message

```
/home/m3/LastDevelopment/cutelystFirstProject/FirstApp/src/upload.cpp:26:22: error: invalid use of incomplete type ‘class Cutelyst::Upload’
   bool done = _upload->save("/tmp/uploads/" + _upload->filename());
                      ^~

In file included from /usr/include/cutelyst-qt5/Cutelyst/context.h:29:0,
                 from /usr/include/cutelyst-qt5/Cutelyst/action.h:28,
                 from /usr/include/cutelyst-qt5/Cutelyst/controller.h:26,
                 from /usr/include/cutelyst-qt5/Cutelyst/Controller:1,
                 from /home/m3/FirstApp/src/upload.h:5,
                 from /home/m3/FirstApp/src/upload.cpp:1:
/usr/include/cutelyst-qt5/Cutelyst/request.h:36:7: note: forward declaration of ‘class Cutelyst::Upload’
 class Upload;
       ^~~~~~
```

**Comment by dantti** [comment]
You need to #include <Cutelyst/Upload> to use it.

**Comment by phantomxe** [comment]
I did include it already.

**Comment by dantti** [comment]
So it's working now?

**Comment by phantomxe** [comment]
My controller file name was "upload.cpp" :smile: . I fixed this without a problem. But i got a new one in uploading a file.

```
4639:4639 cutelyst.dispatcher[debug] Path is "uploadf"
4639:4639 cutelyst.upload[warning] "Cannot create /tmp/uploads/photo_2017-03-26_14-01-06.jpg for output"
4639:4639 cutelyst.upload[warning] "Cannot create /tmp/uploads/ for output"
DAMN ! worker 1 (pid: 4639) died, killed by signal 0 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 4661, cores: 1)
Loading application: /home/m3/LastDevelopment/cutelystFirstProject/FirstApp/build/src/libFirstApp.so
4661:4661 wsgi[debug] Loaded application:  "cutelyst"
Threads:0
```
