### ISSUE TITLE
Improvements for Qt Creator Project Behaviors

### ISSUE THREAD

**Issue by maidis** [cutelyst/cutelyst#351]
It would be nice to have some simple integrations like:

- Run server within Qt Creator
- Open default browser automatically with http://localhost:3000/ url after running
- Stop server on Qt Creator

Running server within Qt Creator can be easily accomplished from the Qt Creator Project's run settings:

- Executable: /usr/bin/cutelyst3-qt5
- Command line arguments: -r --server --app-file src/lib%{Project:Name} -- --chdir ..
- Working directory: %{buildDir}

![Run server within Qt Creator](https://i.imgur.com/apQNgNu.png)

For running web app manually after ~compilation~ running server, custom external tools can be used:

- Run with Default Browser
- Run with Google Chrome
- Run with Mozilla Firefox

![Run web app manually](https://i.imgur.com/6SBvYdh.png)

I think these three basic behaviors will be the first step to get closer to the compatibility of Visual Studio and ASP.NET Core.

**Comment by dantti** [comment]
Waiting for PRs
