### ISSUE TITLE
Debugging Cutelyst app

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#352]
Seems with default cmake configuration app is build without debugging possibilities.
Although in terminal I can see "[debug]", I can`t attach GDB to running Cutelyst process.
When I try add DEBUG build type then cmake stop with error 
":-1: error: No "Debug" CMake configuration found. Available configuration: "".
Make sure that CMAKE_BUILD_TYPE variable matches the "Build type" field."

How can I debug my server side Cutelyst app?

**Comment by dantti** [comment]
Just set CMAKE_BUILD_TYPE to Debug or RelWithDebInfo, usually cmake uses Debug by default not sure why it didn't for you.

**Comment by cezaryece** [comment]
No... not this is problem but ptrace permissions.
I found this using CLion instead CtCreator.
If anybody have same issue look at https://www.jetbrains.com/help/clion/attaching-to-local-process.html
But.... I can attach to process right now, but breakpoints doesn't working so debugging is still impossible.

**Comment by dantti** [comment]
if you are running on unix make sure not to fork so that you debug the right process

**Comment by cezaryece** [comment]
Solved by you example with embedded application - thank You very much @dantti 
Now I am able to debug Cutelyst application like any other in QtCreator.
My little advice - write few words about embedding example in tutorial, because not everybody is looking at whole repository content.
