### ISSUE TITLE
Cutelyst with ASql

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#355]
Hi Danti,
could you provide some example of use ASql in Cutelyst app?

I have problem that Context is not accessible in lambda after exec query. With this simple code I got exception because "c" seems to be null (or undefined) on lambda part (I check that it has proper value before query exec).

ASql::APool::database().exec(queryStr, values, [=] (ASql::AResult &result) {
        if (!result.error()) {
            c->response()->setStatus(Response::OK);
        }
        else {
            c->response()->setStatus(Response::Forbidden);
        }
    });

**Comment by dantti** [comment]
pass the Context *c as the last parameter to the exec() function, but you must also use:
ASync a(c);
and pass it explicit to the lambda captures so that cutelyst doesn't finish the request immediately

**Comment by cezaryece** [comment]
Yes, seems works now.
