### ISSUE TITLE
Asynchronous REST API using GUI mode

### ISSUE THREAD

**Issue by look4pritam** [cutelyst/cutelyst#358]
Thank you very much for HTTP server using C++.

I am able to use it for REST (JSON) based communication between the server and the client.

I am using it in GUI mode for both server and client using example available [at](https://github.com/cutelyst/cutelyst/blob/8ddbd5a22d3758cbc187494ad6a9acf72447262b/examples/embedded-widgets/embeddedapp.cpp#L23)

I am able to use in an asynchronous mode using example available [at](https://github.com/cutelyst/cutelyst/blob/8ddbd5a22d3758cbc187494ad6a9acf72447262b/examples/hello-world/root.cpp#L175)
I am using pcsContext->detachAsync() and pcsContext->attachAsync() as per the example.

I am able to handle the REST based POST request and corresponding response asynchronously with these calls.

But I am having one problem.
It looks the event loop is not completed for the asynchronously processed POST requests.
Am missing somethig from cutelyst API ?
Or 
Just [pcsContext->detachAsync()](https://github.com/cutelyst/cutelyst/blob/8ddbd5a22d3758cbc187494ad6a9acf72447262b/examples/hello-world/root.cpp#L185) and [pcsContext->attachAsync()](https://github.com/cutelyst/cutelyst/blob/8ddbd5a22d3758cbc187494ad6a9acf72447262b/examples/hello-world/root.cpp#L182) are suffcient.

I will not be able to share the complete source code.

Once again thank you very much for Qt based HTTP server.
You should try to get it integrated with main Qt source code. Then everybody will able to use it.

**Comment by dantti** [comment]
everything is complete, in fact I've just updated the async example to reflect the best way to do it, without a code sample of the issue I can't help with yout problem.

Every one can use Cutelyst it's BSD-3-Clause is more liberal than the Qt one. And it's up to them to talk to me if they would like it integrated, unlikely due their new QHttp.

**Comment by look4pritam** [comment]
I have seen changes in example.
I will implement those changes.
If there is issue then I will post it.

Thanks for reply as well as changes in source code.
