### ISSUE TITLE
routing with numbers

### ISSUE THREAD

**Issue by phantomxe** [cutelyst/cutelyst#36]
I built a new controller, name is "v5". And i saw on the console output, 
```
.--------------------------+----------------------.
| Path                     | Private              |
.--------------------------+----------------------.
| /...                     | /defaultPage         |
| /                        | /index               |
| /v/5                     | /v/5/index 
```

I need only "/v5" but cutelyst convert it to "/v/5". How can i solve it?

**Comment by dantti** [comment]
If the automatic namespace doesn't fit your needs you can use C_NAMESPACE macro.

**Comment by phantomxe** [comment]
Could you give a short example about C_NAMESPACE macro?

**Comment by dantti** [comment]
sure:

    class v2 : public Controller
    {
        Q_OBJECT
        C_NAMESPACE("v2")
    public:
    ....
