### ISSUE TITLE
Question about Response::redirect

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#370]
I have backend in Cutelyst which serves data for React web application served by Apache.
After user logout I would like to redirect browser to root page.
But... c->uriFor("/") return whole host address with port used by Cutelyst.
Browser should send request to Apache for root page, not to Cutelyst.

I know that it can be fixed by Response::setHeader, but maybe there is other way with Response::redirect I dont know yet?

PS. I would like to have this as dynamic as it can be, because application will work in different places with different addresses.

**Comment by dantti** [comment]
c->response->redirect() is will redirect to any location you want, now c->uriFor() will give you an url that can be accessed for that action, and that has to have some host logic to point to the right server, if you are not using FastCGI which would give you the right URL easily then you need to configure the proper headers in your proxy and enable `--using-frontend-proxy` or https://github.com/cutelyst/cutelyst/blob/master/server/server.h#L426 if using Server class
