### ISSUE TITLE
Question about default change server/plugins default config

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#380]
Due to lack in documentation I am not able to change default values of server config.
I don`t know where to find default config file (if there is any) or how to create it.
For example I would like to change default session expiring timeout.
And I am curious what else I can change...

**Comment by dantti** [comment]
Cutelyst uses ini files with `--ini` cmd option and the doc for session is here [https://api.cutelyst.org/classCutelyst_1_1Session.html](https://api.cutelyst.org/classCutelyst_1_1Session.html)

**Comment by cezaryece** [comment]
What about server embedded in Qt application?

**Comment by dantti** [comment]
same thing, you can either parse the cmd line with the Server method to do so, or Server::setIni() with a QRC file, I also believe you can change that by code, but don't recall
