### ISSUE TITLE
How prevent from session expire time change on some request?

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#381]
I would like to not reset Session::expires on some request, but returns current value.
Purpose is to show some kind of timer on client page and check value by some request invoked automatically on page idle (without user action).
For now any such request resets expire time to new value.

**Comment by dantti** [comment]
Session doesn't work like that, you can manually do that with Session::setValue('max_ts', current_ts) and at each request check that and them logout based on a max TS, also return your time with current_ts - Settion::value('max_ts')
