### ISSUE TITLE
RoleACL problem

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#383]
In AuthStoreSql::findUser I set "roles" for authenticated user:
user.insert(QStringLiteral("roles"), QStringList{typeStr});

I have endpoint defined with:
C_ATTR(get_guardians, :Local :Does(RoleACL) :RequiresRole(admin) :ACLDetachTo(denied))

At the beginning of get_guardians function I have:
void GuardianController::get_guardians(Context *c) {
    qDebug()  << "Authentication::user roles:" << Authentication::user(c).value(QStringLiteral("roles"));

and in log I see:
Authentication::user roles: QVariant(QStringList, ("pm"))

I am expecting of call of "denied" function, as pm is not admin or at least empty result in response.
But all works like ReleACL was not doing anything and I got results like without any ACL.

What is wrong with my approach?

PS.
C_ATTR(get_guardians, :Local :Does(RoleACL)) is working as well, but should not as "Failure to include the following required attributes will result in a fatal error when the RoleACL action's constructor is called."

**Comment by dantti** [comment]
seems it should work fine. Does replacing RequiredRole by AllowedRole works?

**Comment by cezaryece** [comment]
No, no matter if I put RequiresRole, AllowedRole or none of them - I got all results regardless od logged user role.
In case when I put only Does(RoleACL) I should get "fatal error when the RoleACL action's constructor is called", but seems it is not called at all (how to check this while using Cutelyst as binary library?).

I am using Cutelyst code from Github, not precompiled packages. Enviroment is Ubuntu 22.10.

**Comment by cezaryece** [comment]
OK, sorry by that false issue, it was something with my build of Cutelyst libraries.
I have clean all files with libCutelist in /usr and subfolders and recompile from current sources.
Now ACL feature is working like a charm.
