### ISSUE TITLE
How to access Request inside custom tag processing?

### ISSUE THREAD

**Issue by sanekt197** [cutelyst/cutelyst#385]
What is the normal way to get the Context or Request in the object of the new added custom tag loaded with insertDefaultLibrary in CuteleeView? When processing a tag, there was a need to GET access to the Request parameters of the current request (when sending the post form, as well as take into account the GET-parameters passed to the page where the tag will be displayed).
Until I figured something out

**Comment by sanekt197** [comment]
Understood. Was very unfocused.
The contents of c->stackHash are available in the render method of Cutelee and the Cutelist::Context is available in it.
As an example, look at the UriFor tag class.
It seems to be decided..) Sorry

**Comment by dantti** [comment]
sorry didn't understand the question and forgot to ask more details :) glad you figured out
