### ISSUE TITLE
Cutelyst "Authentication plugin not registered" error message when running multithreaded in Kubernetes

### ISSUE THREAD

**Issue by mike23456** [cutelyst/cutelyst#389]
Hi Daniel,

I am getting a weird error message when running Cutelyst in a Kubernetes cluster (containerized) on nodes having 2 cores (multiple threads). The error doesn't happen when running Cutelyst on my local machine (16 threads). It happens only for REST endpoints that are using RoleACL running in a container on nodes having multiple threads. I also noticed that it doesn't happen on the first API request which succeeds but then the second request logs "Authentication plugin not registered" to the console. Sometimes i get this message several times and Cutelyst doesn't crash but unauthorized gets reported to the HTTP client.

It's my first attempt to run Cutelyst on K8s. However in single threaded mode everything runs just fine (nodes having 1 core). Did i miss any dependency which could be required for multi threading to work with RoleACL / authentication plugin? 

Qt 5.12
Cutelyst version: 3.5.0

Please find the console output below
`
30:31 cutelyst.plugin.authentication[critical] Authentication plugin not registered
30:30 default[warning] QObject: Cannot create children for a parent that is in a different thread.
(Parent is Cutelyst::Context(0x7fa0340348b0), parent's thread is QThread(0x5581ab706890), current thread is QThread(0x5581ab6922a0)
DAMN ! worker 1 (pid: 30) died, killed by signal 0 :( trying respawn ..
Respawned WSGI worker 1 (new pid: 33, cores: 2)
`

I am looking for some guidance on what could cause such a weird error so i can start debugging it. Let me know what u think ?

**Comment by dantti** [comment]
well it should just work, it's odd that it seems to complain about not finding the role acl plugin, but you said it works in single threaded so I'm clueless. I usually run with multiple process but each thread has basically an entirely new application to make isolation easy..

**Comment by mike23456** [comment]
This output confirms its a multi threading issue (Parent is Cutelyst::Context(0x7fa0340348b0), parent's thread is QThread(0x5581ab706890), current thread is QThread(0x5581ab6922a0). I will try to run it in the container on local machine and see what happens cuz i only tested running locally in QtCreator debugging mode hoping to find the source of the crash.

**Comment by mike23456** [comment]
I was able to reproduce the bug in QtCreator on my local machine (not running in a container). It happens the most if i set the number of processes to 1 and the number of threads to 2. In this case the bug shows after the second or third request. Yet the debugger didn't catch it. The worker died and respawned (app didn't crash).  Any ideas how to make the debugger find it?

**Comment by dantti** [comment]
You must disable the master process

**Comment by mike23456** [comment]
Even with enabling/disabling master i can't debug the application. BTW i have some controllers in a shared library. I tried building the library and the app in debug mode (by doing set(DEFAULT_BUILD_TYPE "Debug") ) in CMakeLists.
The code which is failing in multithreaded and multiprocess mode is  in the shared library and its calling
`Authentication::findUser()`  in the root method.

**Comment by dantti** [comment]
if you create some simple app to reproduce I can try to fix it.

**Comment by dantti** [comment]
closing, as needs more info
