### ISSUE TITLE
Qt 6.5 compatibility and broken QMetaMethod::invoke()

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#391]
Trying to create a new Cutelyst application using Qt 6.5.1 I hit the following warning/error:

`QMetaMethod::invoke: cannot convert formal parameter 0 from Cutelyst::Context* in call to Root::Auto(Context*)`

This seems to be related to this Qt bug report: https://bugreports.qt.io/browse/QTBUG-105616

It stops calling the method. So trying to call a route results in an empty response.

Any idea how to solve this?

**Comment by dantti** [comment]
yeah, related to https://codereview.qt-project.org/c/qt/qtbase/+/422745 , I got complaints that 6.5 broke it, but since I don't use it I didn't look at the issue yet. Gammaray did a workaround, but I'm afraid it wouldn't work on Qt7.

**Comment by hheld** [comment]
> yeah, related to https://codereview.qt-project.org/c/qt/qtbase/+/422745 , I got complaints that 6.5 broke it, but since I don't use it I didn't look at the issue yet. Gammaray did a workaround, but I'm afraid it wouldn't work on Qt7.

Can you give some details what that workaround is? I'm also trying to get cutelyst to work with Qt 6.5.1 and it doesn't seem to work at all ...

**Comment by buschmann23** [comment]
I think it is this one mentioned before to be applied in GammaRay:

https://github.com/KDAB/GammaRay/pull/778
