### ISSUE TITLE
Cutelyst not working with Qt 6.5

### ISSUE THREAD

**Issue by WakamTech** [cutelyst/cutelyst#394]

**Comment by Danxomme** [comment]
Hi
Please can anyone help me
When trying to start the server with cutelyst command "cutelyst3-qt6 --server --restart --app-file ./src/libMyApp.so"
It, does not work, I got as error : 
      Plugin uses incompatible Qt library (6.5.0) [release]
26663:26663 cutelyst.server[critical] Could not load application: The plugin uses incompatible Qt library (6.5.0) [release]

I use Qt 6.5.2
How can I solve this problem ?

**Comment by dantti** [comment]
The fix was merged
