### ISSUE TITLE
Problem with call Root::Auto

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#421]
I have simple root controller like this:
class Root : public Controller {
    Q_OBJECT
    C_NAMESPACE("");
public:
    explicit Root(QObject *parent = nullptr): Controller(parent) {};

    C_ATTR(Auto, :Private)
    static bool Auto(Context *c) {
        return Helper::checkIfUserIsLogged(c);
    }
};

When I try to call any endpoint it should check if user is already logged in.
But I got error:
QMetaMethod::invoke: cannot convert formal parameter 1 from QString in call to Root::Auto(Context*)
and any code from Root::Auto is not called.

My Cutelyst is build from Github 3.x.x branch

**Comment by dantti** [comment]
try changing to:
```
private Q_SLOTS:
    bool Auto(Cutelyst::Context *c);
```

**Comment by cezaryece** [comment]
It nothing changes...
But... it is new way of defining controllers? Where it is described?

**Comment by cezaryece** [comment]
I have old Cutelyst application based on Cutelyst3Qt5 and it is working still very good.
I have problem with my new app based on Cutelyst3Qt6.
Do you have any example for similar configuration?
Maybe I have some wrong in CMakeList.txt?

**Comment by dantti** [comment]
Qt5 to Qt6 makes no difference, Qt6.5 broke cutelyst but was fixed in 3.9

**Comment by dantti** [comment]
no, not new way, Auto is an special method that only needs to be a slot or invokable, I was more afraid of it being static.

**Comment by cezaryece** [comment]
OK, so it is not problem with Auto. I comment it out and nothing works better. Each endpoint I call return empty response with status 200. Server responds with 500 "Unknown resource" if try to call any non-existing endpoint.

**Comment by dantti** [comment]
you can create:

```
    C_ATTR(defaultPage, :Path)
    void defaultPage(Context *c);
```
for a custom 404

**Comment by cezaryece** [comment]
It is not my problem.
My problem is none of my enpoints works properly.
Now I think this is problem with installation of Cutelyst3Qt6.
I just copied CMakeList from my old project with 
target_link_libraries(${PROJECT_NAME} PRIVATE
        Cutelyst::Core
        Cutelyst::Utils::Sql... [etc]
and this is compiling and starts but not working properly.
Looking in examples I think it should be 
target_link_libraries(${PROJECT_NAME} PRIVATE
        Cutelyst3Qt6::Core
        Cutelyst3Qt6::Utils::Sql...[etc]
but Target "OtsBackend" links to:
    Cutelyst3Qt6::Core
  but the target was not found.

How I should build / install Cutelyst3Qt6 alongside with Cutelyst3Qt5 on one Ubuntu machine?

**Comment by dantti** [comment]
nothing special, totally possible to install both, or just use the .deb files at github

**Comment by dantti** [comment]
also better use versionless link targets Cutelyst::Core

**Comment by cezaryece** [comment]
You have right, us usual, all my problems is result of mishmash in Cutelyst libraries installed from deb package and created by local build from source. Seems CMake build has different paths for install libraries and cmake files and system is fulled by this and try to configure different version of files during build.
I clean this by hand and install only from debs and now it is working.
