### ISSUE TITLE
Qt 6.5.3 problem [was 'Problem with call Root::Auto']

### ISSUE THREAD

**Issue by cezaryece** [cutelyst/cutelyst#423]
No I know what is real problem.
My Cutelyst app generate message "QMetaMethod::invoke: cannot convert formal parameter 0 from Cutelyst::Context * in call to Root::Auto(Context*)" when I build it with Qt 6.5.3.

When I set CMAKE_PREFIX_PATH to Qt 6.4.3 all is working well.

**Comment by dantti** [comment]
I already told you that Qt 6.5 broke Cutelyst so you need last version either v3 or v4 which has the fix

**Comment by cezaryece** [comment]
I have installed cutelyst3-qt6_3.9.0_amd64.deb

**Comment by dantti** [comment]
The fix is conditional at build time unfortunately so you need to build it by hand with Qt 6.5. https://github.com/cutelyst/cutelyst/commit/c7e805627fb34dc66bcce9d29167f4a552bcc188

**Comment by dantti** [comment]
I'm researching how to publish packages from github actions, once I figure out I might publish a .deb file for both versions.
```
cmake .. -GNinja -DCMAKE_BUILD_TYPE=RelWithDebInfo  -DCMAKE_INSTALL_PREFIX=/usr -DPLUGIN_VIEW_CUTELEE=on -DPLUGIN_MEMCACHED=on -DPLUGIN_VALIDATOR_PWQUALITY=on -DPLUGIN_CSRFPROTECTION=on -DPLUGIN_VIEW_EMAIL=on
```
for now I build it with these flags, then call `cpack` , so append the CMAKE_PREFIX_PATH of Qt 6.5 or greater and you will have it.

**Comment by cezaryece** [comment]
Same problem is with qt 6.6.0 I suppose?

**Comment by buschmann23** [comment]
Yes, if your Cutelyst version was compiled against a Qt version below 6.5.0.
