### ISSUE TITLE
Get started with QT Server

### ISSUE THREAD

**Issue by ganeshkbhat** [cutelyst/cutelyst#43]
New to this. How and where do I get started with a perl or a php fastcgi app using cutelyst server?

**Comment by buschmann23** [comment]
Cutelyst is not a WSGI to execute PHP or Perl applications. It is a framework to write and execute web applications in C++/Qt. It is _inspired_ by the Catalyst web framework that is written in Perl, but itself has nothing to do with Perl.

**Comment by ganeshkbhat** [comment]
Ok here is a silly question. Can I strip off the server and the fastcgi implementation and use it for my purpose. How do I get started? I saw the benchmarks

**Comment by dantti** [comment]
You can of course it's LGPLv2, still if you want to use Perl or PHP I recommend using uwsgi or something else, the benchmarks results are account for the good framework perfomance, not just the server part.
