### ISSUE TITLE
Multiple configuration files

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#436]
Looking at the code in [server.cpp](https://github.com/cutelyst/cutelyst/blob/730bd3a7da422072ef76ba0b01941972f4d3b87c/server/server.cpp#L1236) it is possible to use multiple configuration files by adding `--ini` or `--json` multiple times. But the behavior is IMHO a bit weird.

Having two INI files for example with the following content:
```
; file1.ini

[Cutelyst]
hello=world1
onlyin1=hello

[Testsection1]
foo=bar
```
```
; file2.ini

[Cutelyst]
hello=world2
onlyin2=world

[Testsection2]
fu=baz
```

In my app init I want to see the loaded configuration:
```
bool MyApp::init()
{
    ...

    qDebug() << "[Cutelyst]" << engine()->config("Cutelyst");
    qDebug() << "[Testsection1]" << engine()->config("Testsection1");
    qDebug() << "[Testsection2]" << engine()->config("Testsection2");

    return true;   
}
```

Using only one file with `cutelystd4-qt6 -M -a build/src/libctest.so --h1 localhost:3000 --ini file1.ini` I get what I would expect:
```
[Cutelyst] QMap(("hello", QVariant(QString, "world1"))("onlyin1", QVariant(QString, "hello")))
[Testsection1] QMap(("foo", QVariant(QString, "bar")))
[Testsection2] QMap()
```

But if I try try to use both files with `cutelystd4-qt6 -M -a build/src/libctest.so --h1 localhost:3000 --ini file2.ini --ini file1.ini` I get:
```
[Cutelyst] QMap(("foo", QVariant(QString, "bar"))("hello", QVariant(QString, "world2"))("onlyin1", QVariant(QString, "hello"))("onlyin2", QVariant(QString, "world")))
[Testsection1] QMap()
[Testsection2] QMap(("fu", QVariant(QString, "baz")))
```

`hello=world2` overwrites `hello=world1` as expected, also `onlyin1` and `onlyin2` are joined together in the `Cutelyst` section. But `foo=baz` from `Testsectoin1` in file1 is joined into the `Cutelyst` section, while `fu=baz` from `Testsection2` in file2 is correct.

**Comment by dantti** [comment]
I have no clue why it went into that group, maybe the section is the app name?

**Comment by buschmann23** [comment]
No, application name is not set by me, it is `cutelystd`.

**Comment by buschmann23** [comment]
I would also have expected that the later file on the command line overwrites the previous one, not like now, where the first one overwrites the second one. (but that might be stylistic :) )

**Comment by dantti** [comment]
I usually use this fron within a ini file like a shared db credentials file:
[database]
ini = db.ini

**Comment by buschmann23** [comment]
But that will not be loaded automatically, wouldn’t it?

I would like to use multiple configuration file to support usrEtc/atomic update like described here:
https://en.opensuse.org/openSUSE:Packaging_UsrEtc
https://github.com/thkukuk/atomic-updates_and_etc/blob/master/README.md

**Comment by dantti** [comment]
Yes it is, ApplyConfig set the ini property of Server class so it loads my db config as well. This is good because I have multiple apps using the same db, and db.ini is not a file that CPack packs so it won't overwrite my hand made changes.

**Comment by buschmann23** [comment]
That should still work. I will expand the tests for that case.
