### ISSUE TITLE
Setting HTTP status leads to bugs

### ISSUE THREAD

**Issue by arietto** [cutelyst/cutelyst#458]
Hello! I use Cutelyst 3.9.1 as an embedded REST server within Qt desktop application under Windows. When I send GET request and return default HTTP status, everything is OK.
When I assign non-default status (227), then I have multiple calls of `TcpServer::incomingConnection`.
I've got error string "Error: Connection closed" in the REST client.

**Comment by dantti** [comment]
Can we close this one as it seems you found the issue on #464 ?

**Comment by arietto** [comment]
OK, thank you for quick fix.
