### ISSUE TITLE
Session data not saved to file

### ISSUE THREAD

**Issue by buschmann23** [cutelyst/cutelyst#46]
Since updating to Cutelyst 1.7.0, the session data is not saved to file anymore using the SessionStoreFile. The session file is created as it should be in `/tmp/<Appname>/session/data/36a0d035a21c40d881...`, but it is empty. So, performing a login using `Authentication::authenticate()` is not possible.

I will check if this is the same behavior using the memcached session store.

**Comment by dantti** [comment]
Right, I believe I fixed this yesterday, it only affected FastCGI protocol of WSGI, I think I'll tag it as 1.7.1 if you confirm it works for you.
Odd that just doing delete c; didn't issue the destructor which would emit destroyed(), I had to add the include line, I always thought delete would be smart enough...

**Comment by buschmann23** [comment]
Ah, great. :) I already extracted the commit from yesterday into a patch for my openSUSE and Fedora packages that are currently building. Will report if it fixed the issue.

**Comment by buschmann23** [comment]
👍 commit 2b22f66ae2bd3e88d734aa192bea9c323337fa2a fixes it

**Comment by dantti** [comment]
Just tagged 1.7.1
