### ISSUE TITLE
How can i use cutelyst with SSL?

### ISSUE THREAD

**Issue by phantomxe** [cutelyst/cutelyst#50]
I couldnt find document about SSL.

**Comment by dantti** [comment]
The same way as http://uwsgi-docs.readthedocs.io/en/latest/HTTPS.html

I'll copy that page to the wiki...

**Comment by louwers** [comment]
Just look at the [documentation](https://github.com/cutelyst/cutelyst/blob/7a820d089d434c1d9a2d73e5c9efe769616d6bba/wsgi/tcpserverbalancer.cpp#L83). 😉 

Like this:

```
cutelyst-wsgi --hs1 0.0.0.0:8443,foobar.crt,foobar.key
```

**Comment by cppusta** [comment]
I would like to use SSl with certificate with elliptic curve (EC).
I run app with --hs1 0.0.0.0:8443,server.crt,server.key
but app terminate with error:   "Failed to parse SSL private key"

@louwers say: Just look at the documentation.
I show in source code.
In https://github.com/cutelyst/cutelyst/blob/master/server/tcpserverbalancer.cpp:121
```
QSslKey key(&keyFile, QSsl::Rsa);
    if (key.isNull()) {
    std::cerr << "Failed to parse SSL private key" << std::endl;
    return false;
}
```
In QSslKey constractor is patameter QSsl::Rsa embeded.
Can I use SSL with EC -> QSsl:ec?
