### ISSUE TITLE
Building with MSVC, the dll's are installed apart from the runtime

### ISSUE THREAD

**Issue by texpert** [cutelyst/cutelyst#51]
dll's are installed into the `\cutelyst\build\Cutelyst` folder, while the runtime - into the `\cutelyst\build\Debug` or `\cutelyst\build\Release`.

MSVC 2017 x64
CMake 3.9.0-rc4
Qt 5.9.0

**Comment by dantti** [comment]
I don't use Windows, I just make sure MSVC builds it fine on AppVeyor, can you make a patch?
