### ISSUE TITLE
Example on Authentication in Chapter 5 not working

### ISSUE THREAD

**Issue by sptrakesh** [cutelyst/cutelyst#55]
https://github.com/cutelyst/cutelyst/wiki/Tutorial_05_Authentication

On windows 10 MSVC 2017 with everything running on localhost (so last note about clock skew should not be an issue), and every time I get authentication failure.

Ran same test on a Docker image (Alpine 3.6) and same issue.

```259:259 cutelyst.request[debug] "POST" request for "login" from "172.17.0.1"
259:259 cutelyst.request[debug] Body Parameters are:
.-----------+--------.
| Parameter | Value  |
.-----------+--------.
| password  | mypass |
| submit    | Submit |
| username  | test01 |
.-----------+--------.
259:259 cutelyst.dispatcher[debug] Path is "login"
259:259 default[debug] FOUND USER ->  1
259:259 cutelyst.plugin.credentialpassword[debug] Password didn't match
259:259 cutelyst.grantlee[debug] Rendering template "login.html"
```

**Comment by dantti** [comment]
Hmm interesting, I thought building Authentication User class would fail on MSVC, though you are using 2017, so they probably fixed their compiler. Will review the tutorial, tho it might be an issue on Windows.

**Comment by sptrakesh** [comment]
I get the same issue (Chrome/Safari) when running cutelyst off a Docker image.  The above log was actually from Docker.

**Comment by dantti** [comment]
It's not a browser issue, it might be a Windows/MSVC issue, since I only run Linux I'll have to think on how to debug this.

**Comment by sptrakesh** [comment]
It looks like some difference between the material in the tutorial page and the sources from the tutorial project.  I was able to get it to work when I check out the tutorial project.  Will update if I find the difference.

**Comment by sptrakesh** [comment]
I tried a directory diff, but could not really find the reason.  Anyway, it is not an issue as the sources from the tutorial repository works fine.
