### ISSUE TITLE
My Thought About Grantlee

### ISSUE THREAD

**Issue by MohdFahmiNoorain** [cutelyst/cutelyst#6]
Should we just drop Grantlee from building process? 
1. The link is broken and I couldn't find any new repo related to it.
2. Its only tested against Qt4 (although it can be build against Qt5) and its hard to support legacy app.
3. It makes the cmake result looks ugly...

**Comment by dantti** [comment]
Here https://github.com/steveire/grantlee
the 5.0.0 version is Qt5 only, and it's not legacy at all, upstream is a bit slow on accepting my patches so you can use this for a more complete version https://github.com/cutelyst/grantlee

If I remember correctly if it does not fount it won't build it's plugin.

Best.
