### ISSUE TITLE
I have complie cutelyst-tutorial on windows ,how can I run it on the server

### ISSUE THREAD

**Issue by fanhenghui** [cutelyst/cutelyst#60]
my command is cutelyst -r --server --app-file C:/Program Files/Cutelyst/bin/fhh/build/src/Release/MyApp.dll
error tip is:
 23988:12796 default[debug] Error: failed to find project
Cutelyst-WSGI terminated

**Comment by dantti** [comment]
Window sadly isn't first-class platform, the code should work fine on Windows (it is tested).

The cutelyst command is a "helper" command, it is basicaly cutelyst-wsgi with some "magic". The error you see happens when you run it not on the proper directory which is the build one. Are you running there? Or maybe we got into some Windows specific issue?

**Comment by fanhenghui** [comment]
hello,I have success run the Hello application with cutelyst,but when I run with MyApp demo application,I got error as blow:
Cutelyst-WSGI starting
Cutelyst-WSGI starting
WSGI socket 0 bound to TCP address 0.0.0.0:3000 fd 724
Loading application: MyApp
12424:24356 wsgi[critical] Could not load application: "无法加载库.\\MyApp.dll：找不到指定的模块。"
5784:17020 wsgi.win[debug] Master child finished 1 QProcess::ExitStatus(NormalExit)
Cutelyst-WSGI terminated
means that could not load dependencies of MyApp,
now I has copy the dependencies  dll to the correct dir(include qsqlite.dll and all of other),still has this error,and the  dependencies  is
  Image has the following dependencies:

    cutelyst-qt5.dll
    cutelyst_qt5_plugin_staticsimple.dll
    cutelyst_view_grantlee.dll
    cutelyst_qt5_plugin_utils_sql.dll
    cutelyst_qt5_plugin_session.dll
    cutelyst_qt5_plugin_authentication.dll
    Qt5Sql.dll
    Qt5Core.dll
    VCRUNTIME140.dll
    api-ms-win-crt-string-l1-1-0.dll
    api-ms-win-crt-runtime-l1-1-0.dll
    api-ms-win-crt-heap-l1-1-0.dll
    KERNEL32.dll

**Comment by dantti** [comment]
Is your application properly linked to the plugins you use?

**Comment by dantti** [comment]
Can I close @fanhenghui  ?

**Comment by dantti** [comment]
Please open a new one if needed
