### ISSUE TITLE
Users Need Single RoleACL Example

### ISSUE THREAD

**Issue by MarkTurney** [cutelyst/cutelyst#61]
I am very interested in using RoleACL, but the documentation in the headers is pretty sparse.

Could you create one code example on the Wiki demonstrating it's use?

**Comment by dantti** [comment]
I'll try to improve it's headers docs (I'll keep this open till I fix it).
Meanwhile you can check the docs of the original module at:
http://search.cpan.org/~converter/Catalyst-Action-Role-ACL-0.01/lib/Catalyst/Action/Role/ACL.pm
The usage is pretty similar, feel free to ask me questions if you fail to use it, It would probably be better at the Mailing list as it's better indexed by google for future users I guess.

**Comment by dantti** [comment]
Sorry that was the deprecated class this is the right one
http://search.cpan.org/~bobtfish/Catalyst-ActionRole-ACL-0.07/lib/Catalyst/ActionRole/ACL.pm
