### ISSUE TITLE
Specify controllername when Action conflicts

### ISSUE THREAD

**Issue by louwers** [cutelyst/cutelyst#63]
If it's easy to do, it might be worthwhile to specify the name of the controller of the action that it is in conflict. Maybe even better if it only does so if it's a different action than the action that was not registered:

Current error:

```
17163:17163 cutelyst.dispatcher[critical] Not registering Action "index" of controller "Root2" because it conflicts with  "index"
```

Proposed error:

```
17163:17163 cutelyst.dispatcher[critical] Not registering Action "index" of controller "Root2" because it conflicts with  "index" of controller "Root"
```

I'll look into this myself if you think it's an improvement.

**Comment by dantti** [comment]
Done thanks.

**Comment by louwers** [comment]
Ha! That was quick.

**Comment by dantti** [comment]
Was looking at the editor wondering which TODO item would try to implement ;)
