### ISSUE TITLE
Document that `multipart/form-data` is available as `uploads`

### ISSUE THREAD

**Issue by louwers** [cutelyst/cutelyst#75]
Requests with `multipart/form-data` in their bodies can be uploaded files (uploads), but they can also be simple key value pairs (akin to `application/x-www-form-urlencoded` parameters). This happens for example when using the [Fetch API](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch):
```js
var formData = new FormData();
formData.append('value1', 'key1');
formData.append('value2', 'key2');
fetch('foo/bar', {
    method: 'POST',
    data: formData
});
```
You would need to get these key value pairs with `c->request()->uploadMap()` or `c->request()->uploads()`. I think that the formulation is a bit awkward considering that `multipart/form-data` does not have to contain binary files. But I can get over that. 😉 

However, I believe it should at least be documented that `uploads` and friends actually contain `multipart/form-data`. I had to scratch my head for some time before I realized why these parameters weren't available from `c->request()->bodyParameters()`.

**Comment by dantti** [comment]
Hi, I've just pushed a change which will make these simple pairs available on bodyParameters() also.

They are included there when the part's "filename" and "Content-Type" are empty.

Hope this makes your usage easier!

**Comment by louwers** [comment]
That's great. Thanks. :+1:
