### ISSUE TITLE
Hello Daniel!

### ISSUE THREAD

**Issue by AlekseyGorodetsky** [cutelyst/cutelyst#78]
Look please, the project does not build under Windows for the generator - NMake Makefiles.

Cmake command: 
cmake ..\cutelyst -G"NMake Makefiles"
-- The C compiler identification is MSVC 19.11.25547.0
-- The CXX compiler identification is MSVC 19.11.25547.0
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe
-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe
-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Enterprise/VC/Tools/MSVC/14.11.25503/bin/Hostx64/x64/cl.exe -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- PLUGIN: View::Grantlee, disabled.
-- PLUGIN: View::ClearSilver, disabled.
-- PLUGIN: View::Email, disabled.
-- PLUGIN: Memcached, disabled.
-- PLUGIN: MemcachedSessionStore, disable
-- PLUGIN: StaticCompressed, disabled
-- PLUGIN: CSRFProtection, disbaled
-- Found Doxygen: C:/Program Files/doxygen/bin/doxygen.exe (found version "1.8.13") found components:  doxygen dot
-- Doxygen and dot found. make docs target is available
-- Configuring done
-- Generating done
-- Build files have been written to: E:/Cutelyst/cutelyst/build_NMake_Makefiles

Cmake command:
cmake --build . --config Release
...
[ 87%] Building CXX object tests/CMakeFiles/testactionroleacl_exec.dir/testactionroleacl_exec_autogen/mocs_compilation.cpp.obj
mocs_compilation.cpp
[ 88%] Linking CXX executable ..\testactionroleacl_exec.exe
LINK Pass 1: command "C:\PROGRA~2\MICROS~1\2017\ENTERP~1\VC\Tools\MSVC\1411~1.255\bin\Hostx64\x64\link.exe /nologo @CMakeFiles\testactionroleacl_exec.dir\objects1.rsp /out:..\testactionroleacl_exec.exe /implib:testactionroleacl_exec.lib /pdb:E:\Cutelyst\cutelyst\build_NMake_Makefiles\testactionroleacl_exec.pdb /version:0.0 /machine:x64 /debug /INCREMENTAL /subsystem:console ..\Cutelyst\Plugins\Authentication\cutelyst_qt5_plugin_authentication.lib ..\Cutelyst\Plugins\Session\cutelyst_qt5_plugin_session.lib coverage_test.lib ..\Cutelyst\cutelyst-qt5.lib C:\Qt\5.10.0\msvc2017_64\lib\Qt5Networkd.lib C:\Qt\5.10.0\msvc2017_64\lib\Qt5Testd.lib C:\Qt\5.10.0\msvc2017_64\lib\Qt5Cored.lib kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTFILE:CMakeFiles\testactionroleacl_exec.dir/intermediate.manifest CMakeFiles\testactionroleacl_exec.dir/manifest.res" failed (exit code 1169) with the following output:
coverage_test.lib(coverageobject.cpp.obj) : error LNK2005: "public: __cdecl QMap<class QString,class QVariant>::QMap<class QString,class QVariant>(void)" (??0?$QMap@VQString@@VQVariant@@@@QEAA@XZ) єцх юяЁхфхыхэ т cutelyst_qt5_plugin_authentication.lib(cutelyst_qt5_plugin_authentication.dll)
coverage_test.lib(coverageobject.cpp.obj) : error LNK2005: "public: __cdecl QMap<class QString,class QVariant>::~QMap<class QString,class QVariant>(void)" (??1?$QMap@VQString@@VQVariant@@@@QEAA@XZ) єцх юяЁхфхыхэ т cutelyst_qt5_plugin_authentication.lib(cutelyst_qt5_plugin_authentication.dll)
coverage_test.lib(coverageobject.cpp.obj) : error LNK2005: "public: class QMap<class QString,class QVariant>::iterator __cdecl QMap<class QString,class QVariant>::insert(class QString const &,class QVariant const &)" (?insert@?$QMap@VQString@@VQVariant@@@@QEAA?AViterator@1@AEBVQString@@AEBVQVariant@@@Z) єцх юяЁхфхыхэ т cutelyst_qt5_plugin_authentication.lib(cutelyst_qt5_plugin_authentication.dll)
..\testactionroleacl_exec.exe : fatal error LNK1169: юсэрЁєцхэ ьэюуюъЁрЄэю юяЁхфхыхээ√щ ёшьтюы - юфшэ шыш сюыхх
NMAKE : fatal error U1077: "C:\Program Files\CMake\bin\cmake.exe" : возвращенный код "0xffffffff"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\nmake.exe" : возвращенный код "0x2"
Stop.
NMAKE : fatal error U1077: "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Tools\MSVC\14.11.25503\bin\HostX64\x64\nmake.exe" : возвращенный код "0x2"
Stop.

Success in your hard and extremely important work!
Aleksey
Aleksey.Gorodetsky@gmail.com

**Comment by dantti** [comment]
I can't understand the error messages, but two cutelyst 1 plugins have issues with MSVC I believe that's the case

**Comment by AlekseyGorodetsky** [comment]
## Dear Daniel!
Cmake project with a generator **"Visual Studio 15 2017 Win64"** well built!
Cmake command:
`cmake ..\cutelyst -G"Visual Studio 15 2017 Win6"`

As a result, we get the compiled files, which can be viewed with the command dir:
`E:\Cutelyst\cutelyst\build_Visual_Studio_15_2017_Win64\Release>dir`
...
17.12.2017  18:06           429 568 cutelyst-qt5.dll
17.12.2017  18:08            14 336 cutelyst-wsgi.exe
17.12.2017  18:08            61 440 cutelyst.exe
17.12.2017  18:07           129 536 cutelyst_qt5_plugin_authentication.dll
17.12.2017  18:06            74 240 cutelyst_qt5_plugin_session.dll
17.12.2017  18:08            32 256 cutelyst_qt5_plugin_staticsimple.dll
17.12.2017  18:07            33 280 cutelyst_qt5_plugin_statusmessage.dll
17.12.2017  18:07            60 928 cutelyst_qt5_plugin_utils_pagination.dll
17.12.2017  18:08            35 840 cutelyst_qt5_plugin_utils_sql.dll
17.12.2017  18:08           212 480 cutelyst_qt5_plugin_utils_validator.dll
17.12.2017  18:07            28 672 cutelyst_qt5_plugin_view_json.dll
17.12.2017  18:08           221 184 cutelyst_wsgi_qt5.dll
17.12.2017  18:08            31 744 plugin_action_renderview.dll
17.12.2017  18:08            34 816 plugin_action_rest.dll
17.12.2017  18:08            37 376 plugin_action_roleacl.dll
17.12.2017  18:09            96 768 testactionrenderview_exec.exe
17.12.2017  18:09            85 504 testactionrest_exec.exe
17.12.2017  18:09           159 232 testcontext_exec.exe
17.12.2017  18:09            72 704 testdispatcherchained_exec.exe
17.12.2017  18:09            79 872 testdispatcherpath_exec.exe
17.12.2017  18:09            66 048 testheaders_exec.exe
17.12.2017  18:09            52 736 testpagination_exec.exe
17.12.2017  18:09            48 128 testpbkdf2_exec.exe
17.12.2017  18:09           233 472 testrequest_exec.exe
17.12.2017  18:09           208 384 testresponse_exec.exe
17.12.2017  18:09            94 208 teststatusmessage_exec.exe
17.12.2017  18:10           532 480 testvalidator_exec.exe
17.12.2017  18:08            92 672 testviewjson_exec.exe
              29 файлов      3 259 904 байт
               2 папок  94 912 077 824 байт свободно

And everything works great!

It seems to me that the problem in the Cmake scripts, when building a project with the generator **"NMake Makefiles"**, the linker can not find the path to some libraries.
If the project with the generator **"NMake Makefiles"** was being built, then you can build a project with **Qt Creator**, which is very convenient!
Regards, Aleksey

**Comment by dantti** [comment]
Appveyor does build Cutelyst with nmake, there is an issue on the Authentication plugin that MSVC doesn't like, and on CMake I disabled the build but I might have not disabled the build for your specif generator

**Comment by AlekseyGorodetsky** [comment]
## Dear Daniel!
Did I understand correctly that the Authentication plugin I built with the MSVC compiler (with the Cmake generator "Visual Studio 15 2017 Win64") will not work properly?

Regards, Aleksey

**Comment by dantti** [comment]
Well it's likely, I don't use Windows, but Appveyor build failed due subclassing container classes like QHash, so if you can please test if it works, usually building authentication tests would trigger the issue.

**Comment by AlekseyGorodetsky** [comment]
OK!

**Comment by dantti** [comment]
Closing as I'm assuming that was the issue.
